//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLB00700FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GLB00700FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GLB00700FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLB00700FrontResources.GLB00700FrontResources_msgrsc", typeof(GLB00700FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string _btn_no {
            get {
                return ResourceManager.GetString("_btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _btn_process {
            get {
                return ResourceManager.GetString("_btn_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string _btn_yes {
            get {
                return ResourceManager.GetString("_btn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _lbl_date {
            get {
                return ResourceManager.GetString("_lbl_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _lbl_dept {
            get {
                return ResourceManager.GetString("_lbl_dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Processed Date.
        /// </summary>
        internal static string _lbl_lastprocesseddate {
            get {
                return ResourceManager.GetString("_lbl_lastprocesseddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Rate Revaluation For.
        /// </summary>
        internal static string _lbl_procesfor {
            get {
                return ResourceManager.GetString("_lbl_procesfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * GL Balance for AR/AP account is equal to total AR/AP ageing amount.
        /// </summary>
        internal static string _lbl_warning_1 {
            get {
                return ResourceManager.GetString("_lbl_warning_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Revaluation accounts are set up for each AR/AP account.
        /// </summary>
        internal static string _lbl_warning_2 {
            get {
                return ResourceManager.GetString("_lbl_warning_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that : .
        /// </summary>
        internal static string _lbl_warning_header {
            get {
                return ResourceManager.GetString("_lbl_warning_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Complete.
        /// </summary>
        internal static string _msg_batchComplete {
            get {
                return ResourceManager.GetString("_msg_batchComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Procedure will recalculate all multi-currency transaction balance and will create the different amount into the currency deviation account..
        /// </summary>
        internal static string _msg_confirm1 {
            get {
                return ResourceManager.GetString("_msg_confirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please maintain Currency Rate before running this process for certain period that you want to Reevaluate..
        /// </summary>
        internal static string _msg_confirm2 {
            get {
                return ResourceManager.GetString("_msg_confirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure there is no other user entry any transaction. Continue?.
        /// </summary>
        internal static string _msg_confirm3 {
            get {
                return ResourceManager.GetString("_msg_confirm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Procedure will recalculate all multi-currency transaction balance and will create the different amount into the currency deviation account.
        ///
        ///Please maintain Currency Rate before running this process for certain period that you want to Reevaluate.
        /// 
        ///Make sure there is no other user entry any transaction. Continue?.
        /// </summary>
        internal static string _msg_confirmationprocess {
            get {
                return ResourceManager.GetString("_msg_confirmationprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string _pagetitle_confirmationProcess {
            get {
                return ResourceManager.GetString("_pagetitle_confirmationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Payable .
        /// </summary>
        internal static string _radio_ap {
            get {
                return ResourceManager.GetString("_radio_ap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Receivable.
        /// </summary>
        internal static string _radio_ar {
            get {
                return ResourceManager.GetString("_radio_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash/Bank.
        /// </summary>
        internal static string _radio_cb {
            get {
                return ResourceManager.GetString("_radio_cb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Revaluation.
        /// </summary>
        internal static string _title_page {
            get {
                return ResourceManager.GetString("_title_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Department!.
        /// </summary>
        internal static string _val_dept {
            get {
                return ResourceManager.GetString("_val_dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string btn_no {
            get {
                return ResourceManager.GetString("btn_no", resourceCulture);
            }
        }
    }
}
