//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMR00170FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMR00170FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMR00170FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMR00170FrontResources.PMR00170FrontResources_msgrsc", typeof(PMR00170FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _btn_cancel {
            get {
                return ResourceManager.GetString("_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string _btn_save {
            get {
                return ResourceManager.GetString("_btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string _label_saveas {
            get {
                return ResourceManager.GetString("_label_saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _labelDepartment {
            get {
                return ResourceManager.GetString("_labelDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string _labelFrom {
            get {
                return ResourceManager.GetString("_labelFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string _labelMonth1 {
            get {
                return ResourceManager.GetString("_labelMonth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string _labelMonth10 {
            get {
                return ResourceManager.GetString("_labelMonth10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string _labelMonth11 {
            get {
                return ResourceManager.GetString("_labelMonth11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string _labelMonth12 {
            get {
                return ResourceManager.GetString("_labelMonth12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string _labelMonth2 {
            get {
                return ResourceManager.GetString("_labelMonth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string _labelMonth3 {
            get {
                return ResourceManager.GetString("_labelMonth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string _labelMonth4 {
            get {
                return ResourceManager.GetString("_labelMonth4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string _labelMonth5 {
            get {
                return ResourceManager.GetString("_labelMonth5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string _labelMonth6 {
            get {
                return ResourceManager.GetString("_labelMonth6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string _labelMonth7 {
            get {
                return ResourceManager.GetString("_labelMonth7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string _labelMonth8 {
            get {
                return ResourceManager.GetString("_labelMonth8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string _labelMonth9 {
            get {
                return ResourceManager.GetString("_labelMonth9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string _labelPeriod {
            get {
                return ResourceManager.GetString("_labelPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _labelPrint {
            get {
                return ResourceManager.GetString("_labelPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTY.
        /// </summary>
        internal static string _labelProperty {
            get {
                return ResourceManager.GetString("_labelProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string _labelReportType {
            get {
                return ResourceManager.GetString("_labelReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string _labelReportType1 {
            get {
                return ResourceManager.GetString("_labelReportType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string _labelReportType2 {
            get {
                return ResourceManager.GetString("_labelReportType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman.
        /// </summary>
        internal static string _labelSalesman {
            get {
                return ResourceManager.GetString("_labelSalesman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string _labelTo {
            get {
                return ResourceManager.GetString("_labelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC Event.
        /// </summary>
        internal static string _pageTitle {
            get {
                return ResourceManager.GetString("_pageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string _title_saveas {
            get {
                return ResourceManager.GetString("_title_saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period (To) is higher than Period (From)!.
        /// </summary>
        internal static string _validation_TO_nothigherthan_FROM {
            get {
                return ResourceManager.GetString("_validation_TO_nothigherthan_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Department.
        /// </summary>
        internal static string _validationDepartement {
            get {
                return ResourceManager.GetString("_validationDepartement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select period.
        /// </summary>
        internal static string _validationPeriod {
            get {
                return ResourceManager.GetString("_validationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Salesman.
        /// </summary>
        internal static string _validationSalesman {
            get {
                return ResourceManager.GetString("_validationSalesman", resourceCulture);
            }
        }
    }
}
