//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLI00100BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GLI00100BackResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GLI00100BackResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLI00100BackResources.GLI00100BackResources_msgrsc", typeof(GLI00100BackResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string ACCOUNT_NO {
            get {
                return ResourceManager.GetString("ACCOUNT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string ACCOUNT_TYPE {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget No..
        /// </summary>
        internal static string BUDGET {
            get {
                return ResourceManager.GetString("BUDGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string CENTER {
            get {
                return ResourceManager.GetString("CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string COLUMN_BUDGET {
            get {
                return ResourceManager.GetString("COLUMN_BUDGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Month.
        /// </summary>
        internal static string COLUMN_CURRENT_MONTH {
            get {
                return ResourceManager.GetString("COLUMN_CURRENT_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year.
        /// </summary>
        internal static string COLUMN_CURRENT_YEAR {
            get {
                return ResourceManager.GetString("COLUMN_CURRENT_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        internal static string COLUMN_LAST_YEAR {
            get {
                return ResourceManager.GetString("COLUMN_LAST_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string CURRENCY {
            get {
                return ResourceManager.GetString("CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Journal.
        /// </summary>
        internal static string NORMAL_JOURNAL {
            get {
                return ResourceManager.GetString("NORMAL_JOURNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening.
        /// </summary>
        internal static string OPENING {
            get {
                return ResourceManager.GetString("OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 01.
        /// </summary>
        internal static string PERIOD_01 {
            get {
                return ResourceManager.GetString("PERIOD_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 02.
        /// </summary>
        internal static string PERIOD_02 {
            get {
                return ResourceManager.GetString("PERIOD_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 03.
        /// </summary>
        internal static string PERIOD_03 {
            get {
                return ResourceManager.GetString("PERIOD_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 04.
        /// </summary>
        internal static string PERIOD_04 {
            get {
                return ResourceManager.GetString("PERIOD_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 05.
        /// </summary>
        internal static string PERIOD_05 {
            get {
                return ResourceManager.GetString("PERIOD_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 06.
        /// </summary>
        internal static string PERIOD_06 {
            get {
                return ResourceManager.GetString("PERIOD_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 07.
        /// </summary>
        internal static string PERIOD_07 {
            get {
                return ResourceManager.GetString("PERIOD_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 08.
        /// </summary>
        internal static string PERIOD_08 {
            get {
                return ResourceManager.GetString("PERIOD_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 09.
        /// </summary>
        internal static string PERIOD_09 {
            get {
                return ResourceManager.GetString("PERIOD_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 10.
        /// </summary>
        internal static string PERIOD_10 {
            get {
                return ResourceManager.GetString("PERIOD_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 11.
        /// </summary>
        internal static string PERIOD_11 {
            get {
                return ResourceManager.GetString("PERIOD_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 12.
        /// </summary>
        internal static string PERIOD_12 {
            get {
                return ResourceManager.GetString("PERIOD_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 13.
        /// </summary>
        internal static string PERIOD_13 {
            get {
                return ResourceManager.GetString("PERIOD_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 14.
        /// </summary>
        internal static string PERIOD_14 {
            get {
                return ResourceManager.GetString("PERIOD_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 15.
        /// </summary>
        internal static string PERIOD_15 {
            get {
                return ResourceManager.GetString("PERIOD_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
    }
}
