//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APR00300BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APR00300BackResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APR00300BackResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APR00300BackResources.APR00300BackResources_msgrsc", typeof(APR00300BackResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Total.
        /// </summary>
        internal static string AGE_TOTAL {
            get {
                return ResourceManager.GetString("AGE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string AMOUNT {
            get {
                return ResourceManager.GetString("AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curr.
        /// </summary>
        internal static string CURR {
            get {
                return ResourceManager.GetString("CURR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string CURRENT {
            get {
                return ResourceManager.GetString("CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Off Date.
        /// </summary>
        internal static string CUT_OFF_DATE {
            get {
                return ResourceManager.GetString("CUT_OFF_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total Supplier.
        /// </summary>
        internal static string GRAND_TOTAL_SUPPLIER {
            get {
                return ResourceManager.GetString("GRAND_TOTAL_SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Zero Balance.
        /// </summary>
        internal static string INCLUDE_ZERO_BALANCE {
            get {
                return ResourceManager.GetString("INCLUDE_ZERO_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        internal static string INVOICE_DATE {
            get {
                return ResourceManager.GetString("INVOICE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        internal static string INVOICE_NO {
            get {
                return ResourceManager.GetString("INVOICE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 120 Days.
        /// </summary>
        internal static string MORE_THAN_120_DAYS {
            get {
                return ResourceManager.GetString("MORE_THAN_120_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 30 Days.
        /// </summary>
        internal static string MORE_THAN_30_DAYS {
            get {
                return ResourceManager.GetString("MORE_THAN_30_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 60 Days.
        /// </summary>
        internal static string MORE_THAN_60_DAYS {
            get {
                return ResourceManager.GetString("MORE_THAN_60_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 90 Days.
        /// </summary>
        internal static string MORE_THAN_90_DAYS {
            get {
                return ResourceManager.GetString("MORE_THAN_90_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Due.
        /// </summary>
        internal static string NOT_DUE {
            get {
                return ResourceManager.GetString("NOT_DUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string ORIGINAL {
            get {
                return ResourceManager.GetString("ORIGINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding.
        /// </summary>
        internal static string OUTSTANDING {
            get {
                return ResourceManager.GetString("OUTSTANDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string PERIOD {
            get {
                return ResourceManager.GetString("PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string PROPERTY {
            get {
                return ResourceManager.GetString("PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Age Total.
        /// </summary>
        internal static string SHOW_AGE_TOTAL {
            get {
                return ResourceManager.GetString("SHOW_AGE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Date.
        /// </summary>
        internal static string STATEMENT_DATE {
            get {
                return ResourceManager.GetString("STATEMENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        internal static string SUB_TOTAL {
            get {
                return ResourceManager.GetString("SUB_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total Period.
        /// </summary>
        internal static string SUB_TOTAL_PERIOD {
            get {
                return ResourceManager.GetString("SUB_TOTAL_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string SUPPLIER {
            get {
                return ResourceManager.GetString("SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unallocated Payment.
        /// </summary>
        internal static string UNALLOCATED_PAYMENT {
            get {
                return ResourceManager.GetString("UNALLOCATED_PAYMENT", resourceCulture);
            }
        }
    }
}
