using APR00600COMMON.DTOs.Print;
using BaseHeaderReportCOMMON;
using System;
using System.Collections.Generic;
using System.Text;

namespace APR00600COMMON.Model
{
    public class APR00600DummyData
    {
        public static APR00600ReportResultDTO DefaultData()
        {
            var loCollection = new List<APR00600DataResultDTO>
            {
                new APR00600DataResultDTO { INO=1, CCOMPANY_ID="BSI", CPROPERTY_ID="ASHMD", CSUPPLIER_ID="SP-01", CSUPPLIER_NAME="PERUMDA AIR MINUM JAYA", CCATEGORY_ID="CSP-01", CCATEGORY_NAME="Category Supplier 01", CJRNGRP_CODE="AP", CJRNGRP_NAME="AP", CSUPPLIER_ID_NAME="SP-01 - PERUMDA AIR MINUM JAYA", NBEG_BAL=4275499.57m, NPURCHASE_INVOICE=2073795100, IINVOICE=336, NPURCHASE_RETURN=-2046000, IPURCHASE_RETURN=7, NPURCHASE_DEBIT_NOTE=-1322000, IPURCHASE_DEBIT_NOTE=5, NPURCHASE_CREDIT_NOTE=343000, IPURCHASE_CREDIT_NOTE=5, NPURCHASE_DEBIT_ADJ=305000, IPURCHASE_DEBIT_ADJ=3, NPURCHASE_CREDIT_ADJ=80000, IPURCHASE_CREDIT_ADJ=2, NSUPP_PAYMENT=-2800000, ISUPP_PAYMENT=12, NALLOC_DISCOUNT=0, IPURCHASE_DP=0, NPURCHASE_DP=0, NALLOC_DP=0, NGAIN_LOSS=0, NEND_BAL=4142150200, CFR_PERIOD="2025-01", CTO_PERIOD="2025-10", CFILTER_VALUE="SP-01-PERUMDA AIR MINUM JAYA - Supplier 8-Sup", CFILTER_BY="Supplier ID", CCURRENCY="IDR (Local Currency)" },
                new APR00600DataResultDTO { INO=2, CCOMPANY_ID="BSI", CPROPERTY_ID="ASHMD", CSUPPLIER_ID="SP-02", CSUPPLIER_NAME="Supplier 2", CCATEGORY_ID="ASHMD", CCATEGORY_NAME="Harco Mas", CJRNGRP_CODE="AP", CJRNGRP_NAME="AP", CSUPPLIER_ID_NAME="SP-02 - Supplier 2", NBEG_BAL=0, NPURCHASE_INVOICE=2070500, IINVOICE=12, NPURCHASE_RETURN=-560000, IPURCHASE_RETURN=1, NPURCHASE_DEBIT_NOTE=-560000, IPURCHASE_DEBIT_NOTE=1, NPURCHASE_CREDIT_NOTE=560000, IPURCHASE_CREDIT_NOTE=1, NPURCHASE_DEBIT_ADJ=0, IPURCHASE_DEBIT_ADJ=0, NPURCHASE_CREDIT_ADJ=0, IPURCHASE_CREDIT_ADJ=0, NSUPP_PAYMENT=-2200000, ISUPP_PAYMENT=3, NALLOC_DISCOUNT=0, IPURCHASE_DP=0, NPURCHASE_DP=0, NALLOC_DP=0, NGAIN_LOSS=0, NEND_BAL=1381000, CFR_PERIOD="2025-01", CTO_PERIOD="2025-10", CFILTER_VALUE="SP-01-PERUMDA AIR MINUM JAYA - Supplier 8-Sup", CFILTER_BY="Supplier ID", CCURRENCY="IDR (Local Currency)" },
                new APR00600DataResultDTO { INO=3, CCOMPANY_ID="BSI", CPROPERTY_ID="ASHMD", CSUPPLIER_ID="SP-AP", CSUPPLIER_NAME="Khusus AP", CCATEGORY_ID="CSP-01", CCATEGORY_NAME="Category Supplier 01", CJRNGRP_CODE="AP", CJRNGRP_NAME="AP", CSUPPLIER_ID_NAME="SP-AP - Khusus AP", NBEG_BAL=0, NPURCHASE_INVOICE=6080000, IINVOICE=18, NPURCHASE_RETURN=-50000, IPURCHASE_RETURN=1, NPURCHASE_DEBIT_NOTE=0, IPURCHASE_DEBIT_NOTE=0, NPURCHASE_CREDIT_NOTE=0, IPURCHASE_CREDIT_NOTE=0, NPURCHASE_DEBIT_ADJ=0, IPURCHASE_DEBIT_ADJ=0, NPURCHASE_CREDIT_ADJ=0, IPURCHASE_CREDIT_ADJ=0, NSUPP_PAYMENT=-550000, ISUPP_PAYMENT=2, NALLOC_DISCOUNT=0, IPURCHASE_DP=0, NPURCHASE_DP=0, NALLOC_DP=0, NGAIN_LOSS=0, NEND_BAL=11560000, CFR_PERIOD="2025-01", CTO_PERIOD="2025-10", CFILTER_VALUE="SP-01-PERUMDA AIR MINUM JAYA - Supplier 8-Sup", CFILTER_BY="Supplier ID", CCURRENCY="IDR (Local Currency)" },
                new APR00600DataResultDTO { INO=4, CCOMPANY_ID="BSI", CPROPERTY_ID="ASHMD", CSUPPLIER_ID="SP02", CSUPPLIER_NAME="Supplier02", CCATEGORY_ID="CSP-01", CCATEGORY_NAME="Category Supplier 01", CJRNGRP_CODE="AP", CJRNGRP_NAME="AP", CSUPPLIER_ID_NAME="SP02 - Supplier02", NBEG_BAL=0, NPURCHASE_INVOICE=0, IINVOICE=0, NPURCHASE_RETURN=0, IPURCHASE_RETURN=0, NPURCHASE_DEBIT_NOTE=0, IPURCHASE_DEBIT_NOTE=0, NPURCHASE_CREDIT_NOTE=0, IPURCHASE_CREDIT_NOTE=0, NPURCHASE_DEBIT_ADJ=0, IPURCHASE_DEBIT_ADJ=0, NPURCHASE_CREDIT_ADJ=0, IPURCHASE_CREDIT_ADJ=0, NSUPP_PAYMENT=0, ISUPP_PAYMENT=0, NALLOC_DISCOUNT=0, IPURCHASE_DP=0, NPURCHASE_DP=0, NALLOC_DP=0, NGAIN_LOSS=0, NEND_BAL=0, CFR_PERIOD="2025-01", CTO_PERIOD="2025-10", CFILTER_VALUE="SP-01-PERUMDA AIR MINUM JAYA - Supplier 8-Sup", CFILTER_BY="Supplier ID", CCURRENCY="IDR (Local Currency)" },
                new APR00600DataResultDTO { INO=5, CCOMPANY_ID="BSI", CPROPERTY_ID="ASHMD", CSUPPLIER_ID="SPSC", CSUPPLIER_NAME="Supplier Test", CCATEGORY_ID="ASHMD", CCATEGORY_NAME="Harco Mas", CJRNGRP_CODE="AP", CJRNGRP_NAME="AP", CSUPPLIER_ID_NAME="SPSC - Supplier Test", NBEG_BAL=0, NPURCHASE_INVOICE=4940000, IINVOICE=24, NPURCHASE_RETURN=-5400000, IPURCHASE_RETURN=8, NPURCHASE_DEBIT_NOTE=-1050000, IPURCHASE_DEBIT_NOTE=2, NPURCHASE_CREDIT_NOTE=1000000, IPURCHASE_CREDIT_NOTE=1, NPURCHASE_DEBIT_ADJ=1300000, IPURCHASE_DEBIT_ADJ=4, NPURCHASE_CREDIT_ADJ=1880000, IPURCHASE_CREDIT_ADJ=8, NSUPP_PAYMENT=-1380000, ISUPP_PAYMENT=6, NALLOC_DISCOUNT=0, IPURCHASE_DP=0, NPURCHASE_DP=0, NALLOC_DP=0, NGAIN_LOSS=0, NEND_BAL=6230000, CFR_PERIOD="2025-01", CTO_PERIOD="2025-10", CFILTER_VALUE="SP-01-PERUMDA AIR MINUM JAYA - Supplier 8-Sup", CFILTER_BY="Supplier ID", CCURRENCY="IDR (Local Currency)" },
                new APR00600DataResultDTO { INO=6, CCOMPANY_ID="BSI", CPROPERTY_ID="ASHMD", CSUPPLIER_ID="SUP10", CSUPPLIER_NAME="Hendra Sendra", CCATEGORY_ID="ASHMD", CCATEGORY_NAME="Harco Mas", CJRNGRP_CODE="AP", CJRNGRP_NAME="AP", CSUPPLIER_ID_NAME="SUP10 - Hendra Sendra", NBEG_BAL=0, NPURCHASE_INVOICE=90000, IINVOICE=2, NPURCHASE_RETURN=0, IPURCHASE_RETURN=0, NPURCHASE_DEBIT_NOTE=0, IPURCHASE_DEBIT_NOTE=0, NPURCHASE_CREDIT_NOTE=0, IPURCHASE_CREDIT_NOTE=0, NPURCHASE_DEBIT_ADJ=0, IPURCHASE_DEBIT_ADJ=0, NPURCHASE_CREDIT_ADJ=0, IPURCHASE_CREDIT_ADJ=0, NSUPP_PAYMENT=0, ISUPP_PAYMENT=0, NALLOC_DISCOUNT=0, IPURCHASE_DP=0, NPURCHASE_DP=0, NALLOC_DP=0, NGAIN_LOSS=0, NEND_BAL=180000, CFR_PERIOD="2025-01", CTO_PERIOD="2025-10", CFILTER_VALUE="SP-01-PERUMDA AIR MINUM JAYA - Supplier 8-Sup", CFILTER_BY="Supplier ID", CCURRENCY="IDR (Local Currency)" },
                new APR00600DataResultDTO { INO=7, CCOMPANY_ID="BSI", CPROPERTY_ID="ASHMD", CSUPPLIER_ID="Supplier 8", CSUPPLIER_NAME="Sup", CCATEGORY_ID="ASHMD", CCATEGORY_NAME="Harco Mas", CJRNGRP_CODE="AP", CJRNGRP_NAME="AP", CSUPPLIER_ID_NAME="Supplier 8 - Sup", NBEG_BAL=0, NPURCHASE_INVOICE=1000000, IINVOICE=2, NPURCHASE_RETURN=0, IPURCHASE_RETURN=0, NPURCHASE_DEBIT_NOTE=0, IPURCHASE_DEBIT_NOTE=0, NPURCHASE_CREDIT_NOTE=0, IPURCHASE_CREDIT_NOTE=0, NPURCHASE_DEBIT_ADJ=0, IPURCHASE_DEBIT_ADJ=0, NPURCHASE_CREDIT_ADJ=0, IPURCHASE_CREDIT_ADJ=0, NSUPP_PAYMENT=0, ISUPP_PAYMENT=0, NALLOC_DISCOUNT=0, IPURCHASE_DP=0, NPURCHASE_DP=0, NALLOC_DP=0, NGAIN_LOSS=0, NEND_BAL=2000000, CFR_PERIOD="2025-01", CTO_PERIOD="2025-10", CFILTER_VALUE="SP-01-PERUMDA AIR MINUM JAYA - Supplier 8-Sup", CFILTER_BY="Supplier ID", CCURRENCY="IDR (Local Currency)" }
            };

            var loData = new APR00600ReportResultDTO
            {
                Title = "AR CUSTOMER ANALYSIS",
                Label = new APR00600ReportLabelDTO(),
                Header = new APR00600ReportHeaderDTO
                {
                    CPROPERTY = "Harco Mas(ASHMD)",
                    CSUPPLIER_DISPLAY = loCollection[0].CFILTER_VALUE,
                    CPERIOD_DISPLAY = "2025-01 2025-10",
                    CCURRENCY = loCollection[0].CCURRENCY,
                    CFILTER_BY = loCollection[0].CFILTER_BY
                },
                Data = loCollection
            };
            return loData;
        }

        public static APR00600ReportWithBaseHeaderDTO DefaultDataWithHeader()
        {
            var loParam = new BaseHeaderDTO
            {
                CCOMPANY_NAME = "PT. Realta Chakradarma",
                CPRINT_CODE = "001",
                CPRINT_NAME = "AP SUPPLIER ANALYSIS",
                CUSER_ID = "ZF"
            };

            var loData = new APR00600ReportWithBaseHeaderDTO
            {
                BaseHeaderData = loParam,
                Data = DefaultData()
            };

            return loData;
        }
    }
}
