using System;
using System.Collections.Generic;
using System.Text;

namespace PMT02100COMMON
{
    public class ContextConstant
    {
        public const string PMT02100_GET_HANDOVER_LIST_STREAM_CONTEXT = "PMT02100_GET_HANDOVER_LIST_STREAM_CONTEXT";
        public const string PMT02100_GET_HANDOVER_BUILDING_LIST_STREAM_CONTEXT = "PMT02100_GET_HANDOVER_BUILDING_LIST_STREAM_CONTEXT";

        public const string PMT02100_TAB_OPEN_SCHEDULE_PROCESS_PROPERTY_ID = "PMT02100_TAB_OPEN_SCHEDULE_PROCESS_PROPERTY_ID";
        public const string PMT02100_TAB_OPEN_SCHEDULE_PROCESS_SCHEDULED_HO_DATE = "PMT02100_TAB_OPEN_SCHEDULE_PROCESS_SCHEDULED_HO_DATE";
        public const string PMT02100_TAB_OPEN_SCHEDULE_PROCESS_SCHEDULED_HO_TIME = "PMT02100_TAB_OPEN_SCHEDULE_PROCESS_SCHEDULED_HO_TIME";

        public const string PMT02120_GET_EMPLOYEE_LIST_STREAM_CONTEXT = "PMT02120_GET_EMPLOYEE_LIST_STREAM_CONTEXT ";
        public const string PMT02120_GET_RESCHEDULE_LIST_STREAM_CONTEXT = "PMT02120_GET_RESCHEDULE_LIST_STREAM_CONTEXT ";
        public const string PMT02120_GET_HANDOVER_UTILITY_LIST_STREAM_CONTEXT = "PMT02120_GET_HANDOVER_UTILITY_LIST_STREAM_CONTEXT ";

        public const string PMT02125_HANDOVER_PROCESS_PROPERTY_ID = "PMT02125_HANDOVER_PROCESS_PROPERTY_ID";
        public const string PMT02125_HANDOVER_PROCESS_CDEPT_CODE = "PMT02125_HANDOVER_PROCESS_CDEPT_CODE";
        public const string PMT02125_HANDOVER_PROCESS_CTRANS_CODE = "PMT02125_HANDOVER_PROCESS_CTRANS_CODE";
        public const string PMT02125_HANDOVER_PROCESS_CREF_NO = "PMT02125_HANDOVER_PROCESS_CREF_NO";
        public const string PMT02125_HANDOVER_PROCESS_CHO_ACTUAL_DATE = "PMT02125_HANDOVER_PROCESS_CHO_ACTUAL_DATE";

        public const string PMT02130_GET_HANDOVER_UNIT_LIST_STREAM_CONTEXT = "PMT02130_GET_HANDOVER_UNIT_LIST_STREAM_CONTEXT ";
        public const string PMT02130_GET_HANDOVER_UNIT_CHECKLIST_LIST_STREAM_CONTEXT = "PMT02130_GET_HANDOVER_UNIT_CHECKLIST_LIST_STREAM_CONTEXT ";
    }
}
