//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APR00500BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APR00500BackResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APR00500BackResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APR00500BackResources.APR00500BackResources_msgrsc", typeof(APR00500BackResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add On.
        /// </summary>
        internal static string ADD_ON {
            get {
                return ResourceManager.GetString("ADD_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string ADDITION {
            get {
                return ResourceManager.GetString("ADDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curr..
        /// </summary>
        internal static string CURR {
            get {
                return ResourceManager.GetString("CURR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string CURRENCY {
            get {
                return ResourceManager.GetString("CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Off Date.
        /// </summary>
        internal static string CUT_OFF_DATE {
            get {
                return ResourceManager.GetString("CUT_OFF_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Late.
        /// </summary>
        internal static string DAYS_LATE {
            get {
                return ResourceManager.GetString("DAYS_LATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction.
        /// </summary>
        internal static string DEDUCTION {
            get {
                return ResourceManager.GetString("DEDUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string DEPT {
            get {
                return ResourceManager.GetString("DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string DISCOUNT {
            get {
                return ResourceManager.GetString("DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string DUE_DATE {
            get {
                return ResourceManager.GetString("DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string GRAND_TOTAL {
            get {
                return ResourceManager.GetString("GRAND_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Amount.
        /// </summary>
        internal static string INV_AMT {
            get {
                return ResourceManager.GetString("INV_AMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Period.
        /// </summary>
        internal static string INVOICE_PRD {
            get {
                return ResourceManager.GetString("INVOICE_PRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string PROPERTY {
            get {
                return ResourceManager.GetString("PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Date.
        /// </summary>
        internal static string REF_DATE {
            get {
                return ResourceManager.GetString("REF_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        internal static string REF_NO {
            get {
                return ResourceManager.GetString("REF_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        internal static string REMAINING {
            get {
                return ResourceManager.GetString("REMAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        internal static string SUB_TOTAL {
            get {
                return ResourceManager.GetString("SUB_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string SUPPLIER {
            get {
                return ResourceManager.GetString("SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string TAX {
            get {
                return ResourceManager.GetString("TAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string TOTAL_AMT {
            get {
                return ResourceManager.GetString("TOTAL_AMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Period.
        /// </summary>
        internal static string TOTAL_PRD {
            get {
                return ResourceManager.GetString("TOTAL_PRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string UNIT {
            get {
                return ResourceManager.GetString("UNIT", resourceCulture);
            }
        }
    }
}
