//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMM01500FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LMM01500FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LMM01500FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMM01500FrontResources.LMM01500FrontResources_msgrsc", typeof(LMM01500FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Group Code is required.
        /// </summary>
        internal static string _1501 {
            get {
                return ResourceManager.GetString("1501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Group Name is required.
        /// </summary>
        internal static string _1502 {
            get {
                return ResourceManager.GetString("1502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Limit Invoice Date cannot be smaller than Limit Invoice Dates*.
        /// </summary>
        internal static string _1503 {
            get {
                return ResourceManager.GetString("1503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Limit Invoice Date cannot be smaller than Limit Invoice Dates*.
        /// </summary>
        internal static string _1504 {
            get {
                return ResourceManager.GetString("1504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Id and Name is required.
        /// </summary>
        internal static string _1505 {
            get {
                return ResourceManager.GetString("1505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Template Is Required.
        /// </summary>
        internal static string _1506 {
            get {
                return ResourceManager.GetString("1506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departement Is Required.
        /// </summary>
        internal static string _1507 {
            get {
                return ResourceManager.GetString("1507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Is Required.
        /// </summary>
        internal static string _1508 {
            get {
                return ResourceManager.GetString("1508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Is Required.
        /// </summary>
        internal static string _1509 {
            get {
                return ResourceManager.GetString("1509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Id is required.
        /// </summary>
        internal static string _1511 {
            get {
                return ResourceManager.GetString("1511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut of Date by is required.
        /// </summary>
        internal static string _1512 {
            get {
                return ResourceManager.GetString("1512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Id.
        /// </summary>
        internal static string _AdditionalId {
            get {
                return ResourceManager.GetString("_AdditionalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Limit.
        /// </summary>
        internal static string _AfterLimit {
            get {
                return ResourceManager.GetString("_AfterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Department.
        /// </summary>
        internal static string _AllDept {
            get {
                return ResourceManager.GetString("_AllDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string _Bank {
            get {
                return ResourceManager.GetString("_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        internal static string _BankAccount {
            get {
                return ResourceManager.GetString("_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Receipt Info.
        /// </summary>
        internal static string _BankReceiptInfo {
            get {
                return ResourceManager.GetString("_BankReceiptInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Departement.
        /// </summary>
        internal static string _ByDept {
            get {
                return ResourceManager.GetString("_ByDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation base on.
        /// </summary>
        internal static string _CalculationBaseOn {
            get {
                return ResourceManager.GetString("_CalculationBaseOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _CancelBtn {
            get {
                return ResourceManager.GetString("_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        internal static string _Charges {
            get {
                return ResourceManager.GetString("_Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Id.
        /// </summary>
        internal static string _ChargesId {
            get {
                return ResourceManager.GetString("_ChargesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Name.
        /// </summary>
        internal static string _ChargesName {
            get {
                return ResourceManager.GetString("_ChargesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Type.
        /// </summary>
        internal static string _ChargesType {
            get {
                return ResourceManager.GetString("_ChargesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Type Descr.
        /// </summary>
        internal static string _ChargesTypeDesc {
            get {
                return ResourceManager.GetString("_ChargesTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreateBy {
            get {
                return ResourceManager.GetString("_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreateDate {
            get {
                return ResourceManager.GetString("_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut of Date By.
        /// </summary>
        internal static string _CutOfDateBy {
            get {
                return ResourceManager.GetString("_CutOfDateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _Date {
            get {
                return ResourceManager.GetString("_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Amount.
        /// </summary>
        internal static string _DayAmount {
            get {
                return ResourceManager.GetString("_DayAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Percentage.
        /// </summary>
        internal static string _DayPercen {
            get {
                return ResourceManager.GetString("_DayPercen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string _Days {
            get {
                return ResourceManager.GetString("_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _Dept {
            get {
                return ResourceManager.GetString("_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Desc {
            get {
                return ResourceManager.GetString("_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (valid for Percentage Calculation Pinalty Type Only).
        /// </summary>
        internal static string _DescMinPinalty {
            get {
                return ResourceManager.GetString("_DescMinPinalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string _DueDate {
            get {
                return ResourceManager.GetString("_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date Tolarance.
        /// </summary>
        internal static string _DueDateTolarance {
            get {
                return ResourceManager.GetString("_DueDateTolarance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Days.
        /// </summary>
        internal static string _DueDays {
            get {
                return ResourceManager.GetString("_DueDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Pinalty.
        /// </summary>
        internal static string _EnablePinalty {
            get {
                return ResourceManager.GetString("_EnablePinalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Spesial Day.
        /// </summary>
        internal static string _ExcludeSpesialDay {
            get {
                return ResourceManager.GetString("_ExcludeSpesialDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Due Date.
        /// </summary>
        internal static string _FixedDueDate {
            get {
                return ResourceManager.GetString("_FixedDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Info.
        /// </summary>
        internal static string _GeneralInfo {
            get {
                return ResourceManager.GetString("_GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grace Period.
        /// </summary>
        internal static string _GracePeriod {
            get {
                return ResourceManager.GetString("_GracePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grace Priod.
        /// </summary>
        internal static string _GracePriod {
            get {
                return ResourceManager.GetString("_GracePriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        internal static string _Holiday {
            get {
                return ResourceManager.GetString("_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Due Mode.
        /// </summary>
        internal static string _InvDueMode {
            get {
                return ResourceManager.GetString("_InvDueMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Group.
        /// </summary>
        internal static string _InvGrp {
            get {
                return ResourceManager.GetString("_InvGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Group Mode.
        /// </summary>
        internal static string _InvGrpMode {
            get {
                return ResourceManager.GetString("_InvGrpMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Template.
        /// </summary>
        internal static string _InvTemplate {
            get {
                return ResourceManager.GetString("_InvTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than Equal Limit.
        /// </summary>
        internal static string _LessThanEqualLimit {
            get {
                return ResourceManager.GetString("_LessThanEqualLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Invoice Date.
        /// </summary>
        internal static string _LimitInvDate {
            get {
                return ResourceManager.GetString("_LimitInvDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Pinalty Amount.
        /// </summary>
        internal static string _MaxPinaltyAmount {
            get {
                return ResourceManager.GetString("_MaxPinaltyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Pinalty Amount.
        /// </summary>
        internal static string _MinPinaltyAmount {
            get {
                return ResourceManager.GetString("_MinPinaltyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Amount.
        /// </summary>
        internal static string _MonAmount {
            get {
                return ResourceManager.GetString("_MonAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Percentage.
        /// </summary>
        internal static string _MonPercen {
            get {
                return ResourceManager.GetString("_MonPercen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        internal static string _NextMont {
            get {
                return ResourceManager.GetString("_NextMont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _OkBtn {
            get {
                return ResourceManager.GetString("_OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Day of the Next Month.
        /// </summary>
        internal static string _OneDayNextMon {
            get {
                return ResourceManager.GetString("_OneDayNextMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Amount.
        /// </summary>
        internal static string _OneTimeAmount {
            get {
                return ResourceManager.GetString("_OneTimeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Percentage.
        /// </summary>
        internal static string _OneTimePercen {
            get {
                return ResourceManager.GetString("_OneTimePercen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinalty.
        /// </summary>
        internal static string _Pinalty {
            get {
                return ResourceManager.GetString("_Pinalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty Fee Start from.
        /// </summary>
        internal static string _PinaltyFeeStartFrom {
            get {
                return ResourceManager.GetString("_PinaltyFeeStartFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty Type.
        /// </summary>
        internal static string _PinaltyType {
            get {
                return ResourceManager.GetString("_PinaltyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        internal static string _Principal {
            get {
                return ResourceManager.GetString("_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal and Penalty.
        /// </summary>
        internal static string _PrincipalPinalty {
            get {
                return ResourceManager.GetString("_PrincipalPinalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _ProcessBtn {
            get {
                return ResourceManager.GetString("_ProcessBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Fixed Due Date.
        /// </summary>
        internal static string _RangeFixDueDate {
            get {
                return ResourceManager.GetString("_RangeFixDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounded.
        /// </summary>
        internal static string _Round {
            get {
                return ResourceManager.GetString("_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string _Saturday {
            get {
                return ResourceManager.GetString("_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        /// </summary>
        internal static string _Seq {
            get {
                return ResourceManager.GetString("_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string _Sunday {
            get {
                return ResourceManager.GetString("_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template and Bank Account.
        /// </summary>
        internal static string _TemplateAndBankAccount {
            get {
                return ResourceManager.GetString("_TemplateAndBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        internal static string _Tenant {
            get {
                return ResourceManager.GetString("_Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit/Utility Charges.
        /// </summary>
        internal static string _UnitOrUtilityCharges {
            get {
                return ResourceManager.GetString("_UnitOrUtilityCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdateBy {
            get {
                return ResourceManager.GetString("_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdateDate {
            get {
                return ResourceManager.GetString("_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Stamp.
        /// </summary>
        internal static string _UseStamp {
            get {
                return ResourceManager.GetString("_UseStamp", resourceCulture);
            }
        }
    }
}
