using System;
using System.Collections.Generic;
using System.Text;

namespace GLT00200COMMON
{
    public class ContextConstant
    {
        public const string GLT00200_IMPORT_JOURNAL_ERROR_STREAMING_CONTEXT = "GLT00200_IMPORT_JOURNAL_ERROR_STREAMING_CONTEXT";
        public const string GLT00200_IMPORT_JOURNAL_STREAMING_CONTEXT = "GLT00200_IMPORT_JOURNAL_STREAMING_CONTEXT";
        public const string GLT00200_HEADER_DATA_STREAMING_CONTEXT = "GLT00200_HEADER_DATA_STREAMING_CONTEXT";
        public const string GLT00200_DETAIL_DATA_STREAMING_CONTEXT = "GLT00200_DETAIL_DATA_STREAMING_CONTEXT";
        public const string GLT00200_PROCESS_ID_STREAMING_CONTEXT = "GLT00200_PROCESS_ID_STREAMING_CONTEXT";
        public const string GLT00200_ERROR_GUID_STREAMING_CONTEXT = "GLT00200_ERROR_GUID_STREAMING_CONTEXT";
        public const string GLT00200_HEADER_DATA_CONTEXT = "GLT00200_HEADER_DATA_CONTEXT";
        public const string GLT00200_PROCESS_ID_CONTEXT = "GLT00200_PROCESS_ID_CONTEXT";
        public const string GLT00200_LANGUAGE_ID_CONTEXT = "GLT00200_LANGUAGE_ID_CONTEXT";
        public const string GLT00200_SAVE_IMPORT_JOURNAL_CONTEXT = "GLT00200_SAVE_IMPORT_JOURNAL_CONTEXT";
        public const string UPLOAD_GLT00200_ERROR_GUID_STREAMING_CONTEXT = "UPLOAD_GLT00200_ERROR_GUID_STREAMING_CONTEXT";
        public const string UPLOAD_GLT00200_ERROR_COUNT_GUID_CONTEXT = "UPLOAD_GLT00200_ERROR_COUNT_GUID_CONTEXT";
    }
}
