//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMT02500FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMT02500FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMT02500FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMT02500FrontResources.PMT02500FrontResources_msgrsc", typeof(PMT02500FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Date.
        /// </summary>
        internal static string _AcceptDate {
            get {
                return ResourceManager.GetString("_AcceptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active / InActive.
        /// </summary>
        internal static string _ActiveorInActive {
            get {
                return ResourceManager.GetString("_ActiveorInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string _Actual {
            get {
                return ResourceManager.GetString("_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Area.
        /// </summary>
        internal static string _ActualArea {
            get {
                return ResourceManager.GetString("_ActualArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement.
        /// </summary>
        internal static string _Agreement {
            get {
                return ResourceManager.GetString("_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Date.
        /// </summary>
        internal static string _AgreementDate {
            get {
                return ResourceManager.GetString("_AgreementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement List.
        /// </summary>
        internal static string _AgreementList {
            get {
                return ResourceManager.GetString("_AgreementList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement No.
        /// </summary>
        internal static string _AgreementNo {
            get {
                return ResourceManager.GetString("_AgreementNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement No*.
        /// </summary>
        internal static string _AgreementNo_ {
            get {
                return ResourceManager.GetString("_AgreementNo*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Status.
        /// </summary>
        internal static string _AgreementStatus {
            get {
                return ResourceManager.GetString("_AgreementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Unit(s).
        /// </summary>
        internal static string _AgreementUnit_s_ {
            get {
                return ResourceManager.GetString("_AgreementUnit(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string _Amount {
            get {
                return ResourceManager.GetString("_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based On Opening Date.
        /// </summary>
        internal static string _BasedOnOpeningDate {
            get {
                return ResourceManager.GetString("_BasedOnOpeningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base on Opening Date.
        /// </summary>
        internal static string _BaseonOpeningDate {
            get {
                return ResourceManager.GetString("_BaseonOpeningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Method.
        /// </summary>
        internal static string _BillingMethod {
            get {
                return ResourceManager.GetString("_BillingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Mode.
        /// </summary>
        internal static string _BillingMode {
            get {
                return ResourceManager.GetString("_BillingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rule.
        /// </summary>
        internal static string _BillingRule {
            get {
                return ResourceManager.GetString("_BillingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Fee.
        /// </summary>
        internal static string _BookingFee {
            get {
                return ResourceManager.GetString("_BookingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse File.
        /// </summary>
        internal static string _BrowseFile {
            get {
                return ResourceManager.GetString("_BrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string _Building {
            get {
                return ResourceManager.GetString("_Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Id.
        /// </summary>
        internal static string _BuildingId {
            get {
                return ResourceManager.GetString("_BuildingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string _Capacity {
            get {
                return ResourceManager.GetString("_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CF.
        /// </summary>
        internal static string _CF {
            get {
                return ResourceManager.GetString("_CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        internal static string _ChangeStatus {
            get {
                return ResourceManager.GetString("_ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status From.
        /// </summary>
        internal static string _ChangeStatusFrom {
            get {
                return ResourceManager.GetString("_ChangeStatusFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string _Charge {
            get {
                return ResourceManager.GetString("_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Id.
        /// </summary>
        internal static string _ChargeId {
            get {
                return ResourceManager.GetString("_ChargeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Mode.
        /// </summary>
        internal static string _ChargeMode {
            get {
                return ResourceManager.GetString("_ChargeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Name.
        /// </summary>
        internal static string _ChargeName {
            get {
                return ResourceManager.GetString("_ChargeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        internal static string _Charges {
            get {
                return ResourceManager.GetString("_Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Id.
        /// </summary>
        internal static string _ChargesId {
            get {
                return ResourceManager.GetString("_ChargesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Info.
        /// </summary>
        internal static string _ChargesInfo {
            get {
                return ResourceManager.GetString("_ChargesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Type.
        /// </summary>
        internal static string _ChargeType {
            get {
                return ResourceManager.GetString("_ChargeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string _Close {
            get {
                return ResourceManager.GetString("_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string _Common {
            get {
                return ResourceManager.GetString("_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Area.
        /// </summary>
        internal static string _CommonArea {
            get {
                return ResourceManager.GetString("_CommonArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to  redraft this offer?.
        /// </summary>
        internal static string _ConfirmationRedraft {
            get {
                return ResourceManager.GetString("_ConfirmationRedraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to  submit this offer?.
        /// </summary>
        internal static string _ConfirmationSubmit {
            get {
                return ResourceManager.GetString("_ConfirmationSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        internal static string _Contractor {
            get {
                return ResourceManager.GetString("_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Id.
        /// </summary>
        internal static string _ContractorId {
            get {
                return ResourceManager.GetString("_ContractorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreatedDate {
            get {
                return ResourceManager.GetString("_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string _Currency {
            get {
                return ResourceManager.GetString("_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string _Day {
            get {
                return ResourceManager.GetString("_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _Department {
            get {
                return ResourceManager.GetString("_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department*.
        /// </summary>
        internal static string _Department_ {
            get {
                return ResourceManager.GetString("_Department*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string _Deposit {
            get {
                return ResourceManager.GetString("_Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Amount.
        /// </summary>
        internal static string _DepositAmount {
            get {
                return ResourceManager.GetString("_DepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Date.
        /// </summary>
        internal static string _DepositDate {
            get {
                return ResourceManager.GetString("_DepositDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit ID.
        /// </summary>
        internal static string _DepositID {
            get {
                return ResourceManager.GetString("_DepositID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Name.
        /// </summary>
        internal static string _DepositName {
            get {
                return ResourceManager.GetString("_DepositName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Description {
            get {
                return ResourceManager.GetString("_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string _Document {
            get {
                return ResourceManager.GetString("_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        internal static string _DocumentDate {
            get {
                return ResourceManager.GetString("_DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document File.
        /// </summary>
        internal static string _DocumentFile {
            get {
                return ResourceManager.GetString("_DocumentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No.
        /// </summary>
        internal static string _DocumentNo {
            get {
                return ResourceManager.GetString("_DocumentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Status.
        /// </summary>
        internal static string _DocumentStatus {
            get {
                return ResourceManager.GetString("_DocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string _EndDate {
            get {
                return ResourceManager.GetString("_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Date.
        /// </summary>
        internal static string _ExpiredDate {
            get {
                return ResourceManager.GetString("_ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Amount.
        /// </summary>
        internal static string _FeeAmount {
            get {
                return ResourceManager.GetString("_FeeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Calculation.
        /// </summary>
        internal static string _FeeCalculation {
            get {
                return ResourceManager.GetString("_FeeCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Method.
        /// </summary>
        internal static string _FeeMethod {
            get {
                return ResourceManager.GetString("_FeeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee/Area.
        /// </summary>
        internal static string _FeePerArea {
            get {
                return ResourceManager.GetString("_FeePerArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Contractor.
        /// </summary>
        internal static string _FlagContractor {
            get {
                return ResourceManager.GetString("_FlagContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Paid.
        /// </summary>
        internal static string _FlagPaid {
            get {
                return ResourceManager.GetString("_FlagPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string _Floor {
            get {
                return ResourceManager.GetString("_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Id.
        /// </summary>
        internal static string _FloorId {
            get {
                return ResourceManager.GetString("_FloorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up Date.
        /// </summary>
        internal static string _FollowUpDate {
            get {
                return ResourceManager.GetString("_FollowUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Total Area.
        /// </summary>
        internal static string _ForTotalArea {
            get {
                return ResourceManager.GetString("_ForTotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string _From {
            get {
                return ResourceManager.GetString("_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From LOI No.
        /// </summary>
        internal static string _FromLOINo {
            get {
                return ResourceManager.GetString("_FromLOINo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross.
        /// </summary>
        internal static string _Gross {
            get {
                return ResourceManager.GetString("_Gross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Area.
        /// </summary>
        internal static string _GrossArea {
            get {
                return ResourceManager.GetString("_GrossArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Over Date.
        /// </summary>
        internal static string _HandOverDate {
            get {
                return ResourceManager.GetString("_HandOverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HO Date.
        /// </summary>
        internal static string _HODate {
            get {
                return ResourceManager.GetString("_HODate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string _Invalid {
            get {
                return ResourceManager.GetString("_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Amount.
        /// </summary>
        internal static string _InvoiceAmount {
            get {
                return ResourceManager.GetString("_InvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoiced.
        /// </summary>
        internal static string _Invoiced {
            get {
                return ResourceManager.GetString("_Invoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Group.
        /// </summary>
        internal static string _InvoiceGroup {
            get {
                return ResourceManager.GetString("_InvoiceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Period.
        /// </summary>
        internal static string _InvoicePeriod {
            get {
                return ResourceManager.GetString("_InvoicePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Plan.
        /// </summary>
        internal static string _InvoicePlan {
            get {
                return ResourceManager.GetString("_InvoicePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoicing Period.
        /// </summary>
        internal static string _InvoicingPeriod {
            get {
                return ResourceManager.GetString("_InvoicingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Lord.
        /// </summary>
        internal static string _LandLord {
            get {
                return ResourceManager.GetString("_LandLord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease Mode.
        /// </summary>
        internal static string _LeaseMode {
            get {
                return ResourceManager.GetString("_LeaseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter No.
        /// </summary>
        internal static string _MeterNo {
            get {
                return ResourceManager.GetString("_MeterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Start.
        /// </summary>
        internal static string _MeterStart {
            get {
                return ResourceManager.GetString("_MeterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Rent.
        /// </summary>
        internal static string _MinimumRent {
            get {
                return ResourceManager.GetString("_MinimumRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string _Month {
            get {
                return ResourceManager.GetString("_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month(s).
        /// </summary>
        internal static string _Month_s_ {
            get {
                return ResourceManager.GetString("_Month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Revenue.
        /// </summary>
        internal static string _MonthlyRevenue {
            get {
                return ResourceManager.GetString("_MonthlyRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        internal static string _Net {
            get {
                return ResourceManager.GetString("_Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Area.
        /// </summary>
        internal static string _NetArea {
            get {
                return ResourceManager.GetString("_NetArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Agreement.
        /// </summary>
        internal static string _NewAgreement {
            get {
                return ResourceManager.GetString("_NewAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Doc No.
        /// </summary>
        internal static string _NewDocNo {
            get {
                return ResourceManager.GetString("_NewDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string _Note {
            get {
                return ResourceManager.GetString("_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _Notes {
            get {
                return ResourceManager.GetString("_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Error.
        /// </summary>
        internal static string _NotesError {
            get {
                return ResourceManager.GetString("_NotesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer No.
        /// </summary>
        internal static string _OfferNo {
            get {
                return ResourceManager.GetString("_OfferNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Status.
        /// </summary>
        internal static string _OfferStatus {
            get {
                return ResourceManager.GetString("_OfferStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string _Paid {
            get {
                return ResourceManager.GetString("_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Mode.
        /// </summary>
        internal static string _PeriodMode {
            get {
                return ResourceManager.GetString("_PeriodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan End Date.
        /// </summary>
        internal static string _PlanEndDate {
            get {
                return ResourceManager.GetString("_PlanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan HO Date.
        /// </summary>
        internal static string _PlanHODate {
            get {
                return ResourceManager.GetString("_PlanHODate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Start Date.
        /// </summary>
        internal static string _PlanStartDate {
            get {
                return ResourceManager.GetString("_PlanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _Print {
            get {
                return ResourceManager.GetString("_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _Process {
            get {
                return ResourceManager.GetString("_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTY.
        /// </summary>
        internal static string _PROPERTY {
            get {
                return ResourceManager.GetString("_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _PropertySmall {
            get {
                return ResourceManager.GetString("_PropertySmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal Date.
        /// </summary>
        internal static string _ProposalDate {
            get {
                return ResourceManager.GetString("_ProposalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prorate.
        /// </summary>
        internal static string _Prorate {
            get {
                return ResourceManager.GetString("_Prorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string _Reason {
            get {
                return ResourceManager.GetString("_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redraft.
        /// </summary>
        internal static string _Redraft {
            get {
                return ResourceManager.GetString("_Redraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref Date.
        /// </summary>
        internal static string _RefDate {
            get {
                return ResourceManager.GetString("_RefDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref No.
        /// </summary>
        internal static string _RefNo {
            get {
                return ResourceManager.GetString("_RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Agreement.
        /// </summary>
        internal static string _RenewalAgreement {
            get {
                return ResourceManager.GetString("_RenewalAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Rate.
        /// </summary>
        internal static string _RentRate {
            get {
                return ResourceManager.GetString("_RentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Minimum Rent.
        /// </summary>
        internal static string _RevenueMinimumRent {
            get {
                return ResourceManager.GetString("_RevenueMinimumRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Sharing.
        /// </summary>
        internal static string _RevenueSharing {
            get {
                return ResourceManager.GetString("_RevenueSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Sharing.
        /// </summary>
        internal static string _RevenueSharing1 {
            get {
                return ResourceManager.GetString("_RevenueSharing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Sharing HD.
        /// </summary>
        internal static string _RevenueSharingHD {
            get {
                return ResourceManager.GetString("_RevenueSharingHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Sharing ID.
        /// </summary>
        internal static string _RevenueSharingId {
            get {
                return ResourceManager.GetString("_RevenueSharingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Sharing Minimum Rent.
        /// </summary>
        internal static string _RevenueSharingMinimumRent {
            get {
                return ResourceManager.GetString("_RevenueSharingMinimumRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Sharing Name.
        /// </summary>
        internal static string _RevenueSharingName {
            get {
                return ResourceManager.GetString("_RevenueSharingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Sharing Scheme.
        /// </summary>
        internal static string _RevenueSharingScheme {
            get {
                return ResourceManager.GetString("_RevenueSharingScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman.
        /// </summary>
        internal static string _Salesman {
            get {
                return ResourceManager.GetString("_Salesman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string _Save {
            get {
                return ResourceManager.GetString("_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To Excel.
        /// </summary>
        internal static string _SaveToExcel {
            get {
                return ResourceManager.GetString("_SaveToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq No.
        /// </summary>
        internal static string _SeqNo {
            get {
                return ResourceManager.GetString("_SeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share(%).
        /// </summary>
        internal static string _Share {
            get {
                return ResourceManager.GetString("_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File.
        /// </summary>
        internal static string _SourceFile {
            get {
                return ResourceManager.GetString("_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sqm.
        /// </summary>
        internal static string _sqm {
            get {
                return ResourceManager.GetString("_sqm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string _StartDate {
            get {
                return ResourceManager.GetString("_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date*.
        /// </summary>
        internal static string _StartDate_ {
            get {
                return ResourceManager.GetString("_StartDate*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Invoice Period.
        /// </summary>
        internal static string _StartInvoicePeriod {
            get {
                return ResourceManager.GetString("_StartInvoicePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string _Submit {
            get {
                return ResourceManager.GetString("_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Redraft Successfully!.
        /// </summary>
        internal static string _SuccessMessageOfferRedraft {
            get {
                return ResourceManager.GetString("_SuccessMessageOfferRedraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Submitted Successfully!.
        /// </summary>
        internal static string _SuccessMessageOfferSubmit {
            get {
                return ResourceManager.GetString("_SuccessMessageOfferSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T &amp; C.
        /// </summary>
        internal static string _TandC {
            get {
                return ResourceManager.GetString("_TandC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        internal static string _TaxCode {
            get {
                return ResourceManager.GetString("_TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id.
        /// </summary>
        internal static string _TaxId {
            get {
                return ResourceManager.GetString("_TaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string _Template {
            get {
                return ResourceManager.GetString("_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        internal static string _Tenant {
            get {
                return ResourceManager.GetString("_Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant*.
        /// </summary>
        internal static string _Tenant_ {
            get {
                return ResourceManager.GetString("_Tenant*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenure.
        /// </summary>
        internal static string _Tenure {
            get {
                return ResourceManager.GetString("_Tenure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenure Days.
        /// </summary>
        internal static string _TenureDays {
            get {
                return ResourceManager.GetString("_TenureDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenure Month.
        /// </summary>
        internal static string _TenureMonth {
            get {
                return ResourceManager.GetString("_TenureMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenure Year.
        /// </summary>
        internal static string _TenureYear {
            get {
                return ResourceManager.GetString("_TenureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string _To {
            get {
                return ResourceManager.GetString("_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string _Total {
            get {
                return ResourceManager.GetString("_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Actual Area.
        /// </summary>
        internal static string _TotalActualArea {
            get {
                return ResourceManager.GetString("_TotalActualArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string _TotalAmount {
            get {
                return ResourceManager.GetString("_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Area.
        /// </summary>
        internal static string _TotalArea {
            get {
                return ResourceManager.GetString("_TotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Common Area.
        /// </summary>
        internal static string _TotalCommonArea {
            get {
                return ResourceManager.GetString("_TotalCommonArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Gross Area.
        /// </summary>
        internal static string _TotalGrossArea {
            get {
                return ResourceManager.GetString("_TotalGrossArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Net Area.
        /// </summary>
        internal static string _TotalNetArea {
            get {
                return ResourceManager.GetString("_TotalNetArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Net Size.
        /// </summary>
        internal static string _TotalNetSize {
            get {
                return ResourceManager.GetString("_TotalNetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rows.
        /// </summary>
        internal static string _TotalRows {
            get {
                return ResourceManager.GetString("_TotalRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Unit.
        /// </summary>
        internal static string _TotalUnit {
            get {
                return ResourceManager.GetString("_TotalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string _Transaction {
            get {
                return ResourceManager.GetString("_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trx Status.
        /// </summary>
        internal static string _TrxStatus {
            get {
                return ResourceManager.GetString("_TrxStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string _Unit {
            get {
                return ResourceManager.GetString("_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type.
        /// </summary>
        internal static string _Unit_Type {
            get {
                return ResourceManager.GetString("_Unit Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit &amp; Charges.
        /// </summary>
        internal static string _UnitandCharges {
            get {
                return ResourceManager.GetString("_UnitandCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit &amp; Utilities.
        /// </summary>
        internal static string _UnitAndUtilities {
            get {
                return ResourceManager.GetString("_UnitAndUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Description.
        /// </summary>
        internal static string _UnitDescription {
            get {
                return ResourceManager.GetString("_UnitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Description*.
        /// </summary>
        internal static string _UnitDescription_ {
            get {
                return ResourceManager.GetString("_UnitDescription*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Id.
        /// </summary>
        internal static string _UnitId {
            get {
                return ResourceManager.GetString("_UnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Info.
        /// </summary>
        internal static string _UnitInfo {
            get {
                return ResourceManager.GetString("_UnitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string _UnitName {
            get {
                return ResourceManager.GetString("_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type.
        /// </summary>
        internal static string _UnitType {
            get {
                return ResourceManager.GetString("_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type Category.
        /// </summary>
        internal static string _UnitTypeCategory {
            get {
                return ResourceManager.GetString("_UnitTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdatedBy {
            get {
                return ResourceManager.GetString("_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdatedDate {
            get {
                return ResourceManager.GetString("_UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string _Upload {
            get {
                return ResourceManager.GetString("_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string _Utilities {
            get {
                return ResourceManager.GetString("_Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        internal static string _Utility {
            get {
                return ResourceManager.GetString("_Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility Type.
        /// </summary>
        internal static string _UtilityType {
            get {
                return ResourceManager.GetString("_UtilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string _Valid {
            get {
                return ResourceManager.GetString("_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With FO.
        /// </summary>
        internal static string _WithFO {
            get {
                return ResourceManager.GetString("_WithFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string _Year {
            get {
                return ResourceManager.GetString("_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Successfully.
        /// </summary>
        internal static string M002 {
            get {
                return ResourceManager.GetString("M002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type must Microsoft Excel .xlsx.
        /// </summary>
        internal static string M003 {
            get {
                return ResourceManager.GetString("M003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is Empty.
        /// </summary>
        internal static string M004 {
            get {
                return ResourceManager.GetString("M004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure want process these records?.
        /// </summary>
        internal static string M005 {
            get {
                return ResourceManager.GetString("M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement No is required..
        /// </summary>
        internal static string ValidationAgreementNo {
            get {
                return ResourceManager.GetString("ValidationAgreementNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t saved your changes. Are you sure want to cancel? .
        /// </summary>
        internal static string ValidationBeforeCancel {
            get {
                return ResourceManager.GetString("ValidationBeforeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building is required..
        /// </summary>
        internal static string ValidationBuilding {
            get {
                return ResourceManager.GetString("ValidationBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Id is required..
        /// </summary>
        internal static string ValidationCharge {
            get {
                return ResourceManager.GetString("ValidationCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Mode is required..
        /// </summary>
        internal static string ValidationChargeMode {
            get {
                return ResourceManager.GetString("ValidationChargeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor is required..
        /// </summary>
        internal static string ValidationContractor {
            get {
                return ResourceManager.GetString("ValidationContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is required..
        /// </summary>
        internal static string ValidationCurrency {
            get {
                return ResourceManager.GetString("ValidationCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Found For &quot;Meter No&quot; From Selected Utility Type.
        /// </summary>
        internal static string ValidationDataMeterNo {
            get {
                return ResourceManager.GetString("ValidationDataMeterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date cannot be later than the end date..
        /// </summary>
        internal static string ValidationDate {
            get {
                return ResourceManager.GetString("ValidationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department is required..
        /// </summary>
        internal static string ValidationDepartment {
            get {
                return ResourceManager.GetString("ValidationDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Amount must be greater than 0..
        /// </summary>
        internal static string ValidationDepositAmount {
            get {
                return ResourceManager.GetString("ValidationDepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit ID is required..
        /// </summary>
        internal static string ValidationDepositID {
            get {
                return ResourceManager.GetString("ValidationDepositID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fee Amount must be greater than 0..
        /// </summary>
        internal static string ValidationFeeAmount {
            get {
                return ResourceManager.GetString("ValidationFeeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Calculation is required..
        /// </summary>
        internal static string ValidationFeeCalculation {
            get {
                return ResourceManager.GetString("ValidationFeeCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease Mode is required..
        /// </summary>
        internal static string ValidationLeaseMode {
            get {
                return ResourceManager.GetString("ValidationLeaseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter No is required..
        /// </summary>
        internal static string ValidationMeterNo {
            get {
                return ResourceManager.GetString("ValidationMeterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently processing in Fee Calculation. Please complete this process before saving.
        /// </summary>
        internal static string ValidationModeCalUnit {
            get {
                return ResourceManager.GetString("ValidationModeCalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman is required..
        /// </summary>
        internal static string ValidationSalesman {
            get {
                return ResourceManager.GetString("ValidationSalesman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant is required..
        /// </summary>
        internal static string ValidationTenant {
            get {
                return ResourceManager.GetString("ValidationTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Description is required..
        /// </summary>
        internal static string ValidationUnitDescription {
            get {
                return ResourceManager.GetString("ValidationUnitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Id is required..
        /// </summary>
        internal static string ValidationUnitId {
            get {
                return ResourceManager.GetString("ValidationUnitId", resourceCulture);
            }
        }
    }
}
