using System;
using System.Collections.Generic;
using System.Text;

namespace APT00200COMMON.DTOs
{
    public class ContextConstant
    {
        public const string APT00200_GET_PURCHASE_RETURN_LIST_STREAMING_CONTEXT = "APT00200_GET_PURCHASE_RETURN_LIST_STREAMING_CONTEXT";
        public const string APT00210_GET_PROPERTY_ID_STREAMING_CONTEXT = "APT00210_GET_PROPERTY_ID_STREAMING_CONTEXT";
        public const string APT00211_REC_ID_STREAMING_CONTEXT = "APT00211_REC_ID_STREAMING_CONTEXT";

        public const string APT00231_GET_ADDITIONAL_LIST_STREAMING_CONTEXT = "APT00231_GET_ADDITIONAL_LIST_STREAMING_CONTEXT";
    }
}
