using System;

namespace PMT01300COMMON
{
    public class PMT01300ResultSPPrintDTO
    {
        public int INO { get; set; }
        public string CCOMPANY_ID { get; set; }
        public string CPROPERTY_ID { get; set; }
        public string CPROPERTY_NAME { get; set; }
        public string CDEPT_CODE { get; set; }
        public string CDEPT_NAME { get; set; }
        public string CTRANS_CODE { get; set; }
        public string CREF_NO { get; set; }
        public string CREF_DATE { get; set; }
        public string CREF_PRD { get; set; }
        public string CTENANT_ID { get; set; }
        public string CTENANT_NAME { get; set; }
        public string CCUSTOMER_TYPE { get; set; }
        public string CCUSTOMER_TYPE_NAME { get; set; }
        public string CADDRESS { get; set; }
        public string CPHONE1 { get; set; }
        public string CPHONE2 { get; set; }
        public string CEMAIL { get; set; }
        public string CDOC_NO { get; set; }
        public string CDOC_DATE { get; set; }
        public string CPAY_TERM_CODE { get; set; }
        public string CPAY_TERM_NAME { get; set; }
        public string CDUE_DATE { get; set; }
        public string CTRANS_DESC { get; set; }
        public string CCURRENCY_CODE { get; set; }
        public string CCURRENCY_NAME { get; set; }
        public decimal NLBASE_RATE { get; set; }
        public decimal NLCURRENCY_RATE { get; set; }
        public decimal NBBASE_RATE { get; set; }
        public decimal NBCURRENCY_RATE { get; set; }
        public decimal NTAX_BASE_RATE { get; set; }
        public decimal NTAX_CURRENCY_RATE { get; set; }
        public decimal NAMOUNT { get; set; }
        public decimal NLAMOUNT { get; set; }
        public decimal NBAMOUNT { get; set; }
        public decimal NDISCOUNT { get; set; }
        public decimal NLDISCOUNT { get; set; }
        public decimal NBDISCOUNT { get; set; }
        public decimal NLSUMMARY_DISCOUNT { get; set; }
        public decimal NSUMMARY_DISCOUNT { get; set; }
        public decimal NADD_ON { get; set; }
        public decimal NBSUMMARY_DISCOUNT { get; set; }
        public decimal NLADD_ON { get; set; }
        public decimal NBADD_ON { get; set; }
        public decimal NTAXABLE_AMOUNT { get; set; }
        public decimal NLTAXABLE_AMOUNT { get; set; }
        public decimal NBTAXABLE_AMOUNT { get; set; }
        public decimal NTAX { get; set; }
        public decimal NLTAX { get; set; }
        public decimal NBTAX { get; set; }
        public decimal NOTHER_TAX { get; set; }
        public decimal NLOTHER_TAX { get; set; }
        public decimal NBOTHER_TAX { get; set; }
        public decimal NADDITION { get; set; }
        public decimal NLADDITION { get; set; }
        public decimal NBADDITION { get; set; }
        public decimal NDEDUCTION { get; set; }
        public decimal NLDEDUCTION { get; set; }
        public decimal NBDEDUCTION { get; set; }
        public decimal NTRANS_AMOUNT { get; set; }
        public decimal NLTRANS_AMOUNT { get; set; }
        public decimal NBTRANS_AMOUNT { get; set; }
        public string CSOURCE_MODULE { get; set; }
        public bool LTAXABLE { get; set; }
        public string CTAX_ID { get; set; }
        public string CTAX_NAME { get; set; }
        public decimal NTAX_PCT { get; set; }
        public string CTRANS_STATUS { get; set; }
        public string CTRANS_STATUS_NAME { get; set; }
        public decimal NTOTAL_AMOUNT { get; set; }
        public string CTOTAL_AMOUNT_IN_WORDS { get; set; }
        public bool LGLLINK { get; set; }
        public string CGL_REF_NO { get; set; }
        public string CLINK_REF_NO { get; set; }
        public string CINVGRP_CODE { get; set; }
        public string CINVGRP_NAME { get; set; }
        public string CUNIT_DESCRIPTION { get; set; }
        public decimal NTOTAL_TAX { get; set; }
        public decimal NTAX_EXEMPTION { get; set; }
        public string CPROD_DEPT_CODE { get; set; }
        public string CPROD_TYPE { get; set; }
        public string CPRODUCT_ID { get; set; }
        public string CDETAIL_DESC { get; set; }
        public string CPRODUCT_NAME { get; set; }
        public decimal NTRANS_QTY { get; set; }
        public decimal NAPPV_QTY { get; set; }
        public decimal NBILL_UNIT_QTY { get; set; }
        public string CUNIT { get; set; }
        public decimal NUNIT_PRICE { get; set; }
        public decimal NLINE_AMOUNT { get; set; }
        public decimal NDISC_AMOUNT { get; set; }
        public decimal NDIST_DISCOUNT { get; set; }
        public decimal NTOTAL_DISCOUNT { get; set; }
        public decimal NDIST_ADD_ON { get; set; }
        public decimal NLINE_TAXABLE_AMOUNT { get; set; }
        public decimal NTAX_AMOUNT { get; set; }
        public decimal NOTHER_TAX_AMOUNT { get; set; }
        public string CJRN_ID { get; set; }
    }
}
