--GSM05000

-- ================= INIT PROCESS ==================

-- LIST DATA

Select A.*, CMODULE_NAME = Isnull((Select Top 1 RTRIM(CMODULE_NAME) 
From SAM_PROGRAM (Nolock) Where CMODULE_ID = A.CMODULE_ID), '***Not found***') 
From GSM_TRANSACTION_CODE A (Nolock) 
WHERE A.CCOMPANY_ID = 'RCD'
ORDER BY A.CTRANSACTION_CODE, A.CMODULE_ID ASC


-- SINGLE DATA
Select A.* From GSM_TRANSACTION_CODE A (Nolock) 
Where A.CCOMPANY_ID = 'RCD'
AND A.CTRANSACTION_CODE = '920010'

SELECT * FROM RFT_GET_GSB_CODE_INFO ('SIAPP', 'rcd', '_GS_REFNO_DELIMITER', '', 'en')
