    using System;
using System.Collections.Generic;
using System.Text;

namespace GSM02500COMMON.DTOs
{
    public class ContextConstant
    {
        public const string GSM02500_PROPERTY_ID_STREAMING_CONTEXT = "GSM02500_PROPERTY_ID_STREAMING_CONTEXT";
        public const string GSM02500_BUILDING_ID_STREAMING_CONTEXT = "GSM02500_BUILDING_ID_STREAMING_CONTEXT";
        public const string GSM02500_FLOOR_ID_STREAMING_CONTEXT = "GSM02500_FLOOR_ID_STREAMING_CONTEXT";
        //public const string GSM02500_UNIT_TYPE_ID_CONTEXT = "GSM02500_UNIT_TYPE_ID_CONTEXT";
        //public const string GSM02500_PROPERTY_ID_CONTEXT = "GSM02500_PROPERTY_ID_CONTEXT";
        //public const string GSM02500_UNIT_ID_CONTEXT = "GSM02500_UNIT_ID_CONTEXT";
        //public const string GSM02500_BUILDING_ID_CONTEXT = "GSM02500_BUILDING_ID_CONTEXT";
        //public const string GSM02500_FLOOR_ID_CONTEXT = "GSM02500_FLOOR_ID_CONTEXT";

        //public const string GSM02501_LACTIVE_CONTEXT = "GSM02501_LACTIVE_CONTEXT";
        //public const string GSM02501_PROPERTY_ID_CONTEXT = "GSM02501_PROPERTY_ID_CONTEXT";

        public const string GSM02502_PROPERTY_ID_STREAMING_CONTEXT = "GSM02502_PROPERTY_ID_STREAMING_CONTEXT";
        //public const string GSM02502_PROPERTY_ID_CONTEXT = "GSM02502_PROPERTY_ID_CONTEXT";
        //public const string GSM02502_UNIT_TYPE_CATEGORY_ID_CONTEXT = "GSM02502_UNIT_TYPE_CATEGORY_ID_CONTEXT";
        //public const string GSM02502_LACTIVE_CONTEXT = "GSM02502_LACTIVE_CONTEXT";

        public const string GSM02502_CHARGE_PROPERTY_ID_STREAMING_CONTEXT = "GSM02502_CHARGE_PROPERTY_ID_STREAMING_CONTEXT";
        //public const string GSM02502_CHARGE_PROPERTY_ID_CONTEXT = "GSM02502_CHARGE_PROPERTY_ID_CONTEXT";
        //public const string GSM02502_CHARGE_UNIT_TYPE_CATEGORY_ID_CONTEXT = "GSM02502_CHARGE_UNIT_TYPE_CATEGORY_ID_CONTEXT";
        public const string GSM02502_CHARGE_UNIT_TYPE_CATEGORY_ID_STREAMING_CONTEXT = "GSM02502_CHARGE_UNIT_TYPE_CATEGORY_ID_STREAMING_CONTEXT";
        public const string GSM02502_CHARGE_COMBOBOX_CLASS_ID_STREAMING_CONTEXT = "GSM02502_CHARGE_COMBOBOX_CLASS_ID_STREAMING_CONTEXT";

        public const string GSM02502_UTILITY_PROPERTY_ID_STREAMING_CONTEXT = "GSM02502_UTILITY_PROPERTY_ID_STREAMING_CONTEXT";
        //public const string GSM02502_UTILITY_PROPERTY_ID_CONTEXT = "GSM02502_UTILITY_PROPERTY_ID_CONTEXT";
        //public const string GSM02502_UTILITY_UNIT_TYPE_CATEGORY_ID_CONTEXT = "GSM02502_UTILITY_UNIT_TYPE_CATEGORY_ID_CONTEXT";
        public const string GSM02502_UTILITY_UNIT_TYPE_CATEGORY_ID_STREAMING_CONTEXT = "GSM02502_UTILITY_UNIT_TYPE_CATEGORY_ID_STREAMING_CONTEXT";

        public const string GSM02503_PROPERTY_ID_STREAMING_CONTEXT = "GSM02503_PROPERTY_ID_STREAMING_CONTEXT";
        public const string GSM02503_UNIT_TYPE_ID_STREAMING_CONTEXT = "GSM02503_UNIT_TYPE_ID_STREAMING_CONTEXT";
        public const string GSM02503_UNIT_TYPE_CATEGORY_ID_STREAMING_CONTEXT = "GSM02503_UNIT_TYPE_CATEGORY_ID_STREAMING_CONTEXT";
        //public const string GSM02503_UNIT_TYPE_CATEGORY_ID_CONTEXT = "GSM02503_UNIT_TYPE_CATEGORY_ID_CONTEXT";
        //public const string GSM02503_LACTIVE_CONTEXT = "GSM02503_LACTIVE_CONTEXT";
        //public const string GSM02503_PROPERTY_ID_CONTEXT = "GSM02503_PROPERTY_ID_CONTEXT";
        //public const string GSM02503_UNIT_TYPE_ID_CONTEXT = "GSM02503_UNIT_TYPE_ID_CONTEXT";

        public const string GSM02504_PROPERTY_ID_STREAMING_CONTEXT = "GSM02504_PROPERTY_ID_STREAMING_CONTEXT";
        //public const string GSM02504_PROPERTY_ID_CONTEXT = "GSM02504_PROPERTY_ID_CONTEXT";

        public const string GSM02510_PROPERTY_ID_STREAMING_CONTEXT = "GSM02510_PROPERTY_ID_STREAMING_CONTEXT";
        //public const string GSM02510_PROPERTY_ID_CONTEXT = "GSM02510_PROPERTY_ID_CONTEXT";
        //public const string GSM02510_BUILDING_ID_CONTEXT = "GSM02510_BUILDING_ID_CONTEXT";
        //public const string GSM02510_LACTIVE_CONTEXT = "GSM02510_LACTIVE_CONTEXT";

        public const string GSM02520_UNIT_TYPE_CATEGORY_ID_STREAMING_CONTEXT = "GSM02520_UNIT_TYPE_CATEGORY_ID_STREAMING_CONTEXT";
        public const string GSM02520_PROPERTY_ID_STREAMING_CONTEXT = "GSM02520_PROPERTY_ID_STREAMING_CONTEXT";
        public const string GSM02520_BUILDING_ID_STREAMING_CONTEXT = "GSM02520_BUILDING_ID_STREAMING_CONTEXT";
        public const string GSM02520_FLOOR_ID_STREAMING_CONTEXT = "GSM02520_FLOOR_ID_STREAMING_CONTEXT";
        //public const string GSM02520_PROPERTY_ID_CONTEXT = "GSM02520_PROPERTY_ID_CONTEXT";
        //public const string GSM02520_BUILDING_ID_CONTEXT = "GSM02520_BUILDING_ID_CONTEXT";
        //public const string GSM02520_FLOOR_ID_CONTEXT = "GSM02520_FLOOR_ID_CONTEXT";
        //public const string GSM02520_LACTIVE_CONTEXT = "GSM02520_LACTIVE_CONTEXT";


        public const string GSM02530_UNIT_TYPE_CATEGORY_ID_STREAMING_CONTEXT = "GSM02530_UNIT_TYPE_CATEGORY_ID_STREAMING_CONTEXT";
        public const string GSM02530_UNIT_ID_STREAMING_CONTEXT = "GSM02530_UNIT_ID_STREAMING_CONTEXT";
        public const string GSM02530_UTILITIES_TYPE_ID_STREAMING_CONTEXT = "GSM02530_UTILITIES_TYPE_ID_STREAMING_CONTEXT";
        public const string GSM02530_SEQUENCE_ID_STREAMING_CONTEXT = "GSM02530_SEQUENCE_ID_STREAMING_CONTEXT";
        public const string GSM02530_PROPERTY_ID_STREAMING_CONTEXT = "GSM02530_PROPERTY_ID_STREAMING_CONTEXT";
        public const string GSM02530_BUILDING_ID_STREAMING_CONTEXT = "GSM02530_BUILDING_ID_STREAMING_CONTEXT";
        public const string GSM02530_FLOOR_ID_STREAMING_CONTEXT = "GSM02530_FLOOR_ID_STREAMING_CONTEXT";
        //public const string GSM02530_UNIT_ID_CONTEXT = "GSM02530_UNIT_ID_CONTEXT";
        //public const string GSM02530_PROPERTY_ID_CONTEXT = "GSM02530_PROPERTY_ID_CONTEXT";
        //public const string GSM02530_BUILDING_ID_CONTEXT = "GSM02530_BUILDING_ID_CONTEXT";
        //public const string GSM02530_FLOOR_ID_CONTEXT = "GSM02530_FLOOR_ID_CONTEXT";
        //public const string GSM02530_LACTIVE_CONTEXT = "GSM02530_LACTIVE_CONTEXT";
        //public const string GSM02530_UTILITIES_TYPE_CONTEXT = "GSM02530_UTILITIES_TYPE_CONTEXT";
        //public const string GSM02530_SEQUENCE_CONTEXT = "GSM02530_SEQUENCE_CONTEXT";

        public const string GSM02540_PROPERTY_ID_STREAMING_CONTEXT = "GSM02540_PROPERTY_ID_STREAMING_CONTEXT";
        public const string GSM02540_BUILDING_ID_STREAMING_CONTEXT = "GSM02540_BUILDING_ID_STREAMING_CONTEXT";
        //public const string GSM02540_PROPERTY_ID_CONTEXT = "GSM02540_PROPERTY_ID_CONTEXT";
        //public const string GSM02540_CUNIT_PROMOTION_TYPE_ID_CONTEXT = "GSM02540_CUNIT_PROMOTION_TYPE_ID_CONTEXT";
        //public const string GSM02540_LACTIVE_CONTEXT = "GSM02540_LACTIVE_CONTEXT";
        //public const string GSM02540_CUNIT_PROMOTION_ID_CONTEXT = "GSM02540_CUNIT_PROMOTION_ID_CONTEXT";

        public const string GSM02550_PROPERTY_ID_STREAMING_CONTEXT = "GSM02550_PROPERTY_ID_STREAMING_CONTEXT";
        public const string GSM02550_PROPERTY_ID_CONTEXT = "GSM02550_PROPERTY_ID_CONTEXT";

        public const string GSM02560_PROPERTY_ID_STREAMING_CONTEXT = "GSM02560_PROPERTY_ID_STREAMING_CONTEXT";

        public const string UPLOAD_FLOOR_STREAMING_CONTEXT = "UPLOAD_FLOOR_STREAMING_CONTEXT";
        public const string UPLOAD_FLOOR_CHECK_IS_FLOOR_USED_CONTEXT = "UPLOAD_FLOOR_CHECK_IS_FLOOR_USED_CONTEXT";
        public const string UPLOAD_FLOOR_ERROR_GUID_STREAMING_CONTEXT = "UPLOAD_FLOOR_ERROR_GUID_STREAMING_CONTEXT";
        public const string UPLOAD_FLOOR_PROPERTY_ID_CONTEXT = "UPLOAD_FLOOR_PROPERTY_ID_CONTEXT";
        public const string UPLOAD_FLOOR_IS_OVERWRITE_CONTEXT = "UPLOAD_FLOOR_IS_OVERWRITE_CONTEXT";
        public const string UPLOAD_FLOOR_BUILDING_ID_CONTEXT = "UPLOAD_FLOOR_BUILDING_ID_CONTEXT";

        public const string UPLOAD_UNIT_STREAMING_CONTEXT = "UPLOAD_UNIT_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_ERROR_GUID_STREAMING_CONTEXT = "UPLOAD_UNIT_ERROR_GUID_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_PROPERTY_ID_CONTEXT = "UPLOAD_UNIT_PROPERTY_ID_CONTEXT";
        public const string UPLOAD_UNIT_BUILDING_ID_CONTEXT = "UPLOAD_UNIT_BUILDING_ID_CONTEXT";
        public const string UPLOAD_UNIT_FLOOR_ID_CONTEXT = "UPLOAD_UNIT_FLOOR_ID_CONTEXT";
        public const string UPLOAD_UNIT_IS_OVERWRITE_CONTEXT = "UPLOAD_UNIT_IS_OVERWRITE_CONTEXT";

        public const string UPLOAD_UNIT_UTILITY_STREAMING_CONTEXT = "UPLOAD_UNIT_UTILITY_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_UTILITY_ERROR_GUID_STREAMING_CONTEXT = "UPLOAD_UNIT_UTILITY_ERROR_GUID_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_UTILITY_PROPERTY_ID_CONTEXT = "UPLOAD_UNIT_UTILITY_PROPERTY_ID_CONTEXT";
        public const string UPLOAD_UNIT_UTILITY_BUILDING_ID_CONTEXT = "UPLOAD_UNIT_UTILITY_BUILDING_ID_CONTEXT";
        public const string UPLOAD_UNIT_UTILITY_FLOOR_ID_CONTEXT = "UPLOAD_UNIT_UTILITY_FLOOR_ID_CONTEXT";
        public const string UPLOAD_UNIT_UTILITY_UNIT_ID_CONTEXT = "UPLOAD_UNIT_UTILITY_UNIT_ID_CONTEXT";
        public const string UPLOAD_UNIT_UTILITY_IS_OVERWRITE_CONTEXT = "UPLOAD_UNIT_UTILITY_IS_OVERWRITE_CONTEXT";

        public const string UPLOAD_UNIT_TYPE_CATEGORY_STREAMING_CONTEXT = "UPLOAD_UNIT_TYPE_CATEGORY_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_TYPE_CATEGORY_ERROR_GUID_STREAMING_CONTEXT = "UPLOAD_UNIT_TYPE_CATEGORY_ERROR_GUID_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_TYPE_CATEGORY_CHECK_IS_USED_CONTEXT = "UPLOAD_UNIT_TYPE_CATEGORY_CHECK_IS_USED_CONTEXT";
        public const string UPLOAD_UNIT_TYPE_CATEGORY_PROPERTY_ID_CONTEXT = "UPLOAD_UNIT_TYPE_CATEGORY_PROPERTY_ID_CONTEXT";
        public const string UPLOAD_UNIT_TYPE_CATEGORY_IS_OVERWRITE_CONTEXT = "UPLOAD_UNIT_TYPE_CATEGORY_IS_OVERWRITE_CONTEXT";

        public const string UPLOAD_UNIT_TYPE_STREAMING_CONTEXT = "UPLOAD_UNIT_TYPE_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_TYPE_ERROR_GUID_STREAMING_CONTEXT = "UPLOAD_UNIT_TYPE_ERROR_GUID_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_TYPE_CHECK_IS_USED_CONTEXT = "UPLOAD_UNIT_TYPE_CHECK_IS_USED_CONTEXT";
        public const string UPLOAD_UNIT_TYPE_PROPERTY_ID_CONTEXT = "UPLOAD_UNIT_TYPE_PROPERTY_ID_CONTEXT";
        public const string UPLOAD_UNIT_TYPE_IS_OVERWRITE_CONTEXT = "UPLOAD_UNIT_TYPE_IS_OVERWRITE_CONTEXT";

        public const string UPLOAD_UNIT_PROMOTION_TYPE_STREAMING_CONTEXT = "UPLOAD_UNIT_PROMOTION_TYPE_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_PROMOTION_TYPE_ERROR_GUID_STREAMING_CONTEXT = "UPLOAD_UNIT_PROMOTION_TYPE_ERROR_GUID_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_PROMOTION_TYPE_PROPERTY_ID_CONTEXT = "UPLOAD_UNIT_PROMOTION_TYPE_PROPERTY_ID_CONTEXT";
        public const string UPLOAD_UNIT_PROMOTION_TYPE_IS_OVERWRITE_CONTEXT = "UPLOAD_UNIT_PROMOTION_TYPE_IS_OVERWRITE_CONTEXT";

        public const string UPLOAD_UNIT_PROMOTION_STREAMING_CONTEXT = "UPLOAD_UNIT_PROMOTION_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_PROMOTION_ERROR_GUID_STREAMING_CONTEXT = "UPLOAD_UNIT_PROMOTION_ERROR_GUID_STREAMING_CONTEXT";
        public const string UPLOAD_UNIT_PROMOTION_PROPERTY_ID_CONTEXT = "UPLOAD_UNIT_PROMOTION_PROPERTY_ID_CONTEXT";
        public const string UPLOAD_UNIT_PROMOTION_IS_OVERWRITE_CONTEXT = "UPLOAD_UNIT_PROMOTION_IS_OVERWRITE_CONTEXT";
    }
}
