
/****** OBJECT:  TABLE DBO.LMT_DISCOUNT_HD    SCRIPT DATE: 12/9/2019 5:48:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF (EXISTS (SELECT * 
					FROM INFORMATION_SCHEMA.TABLES 
					WHERE  TABLE_NAME = 'LMT_DISCOUNT_HD'))
DROP TABLE LMT_DISCOUNT_HD


CREATE TABLE DBO.LMT_DISCOUNT_HD(
			CCOMPANY_ID				VARCHAR(8)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CCOMPANY_ID			DEFAULT (''),
			CPROPERTY_ID			VARCHAR(20)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CPROPERTY_ID			DEFAULT (''),
			CREF_NO					VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CREF_NO				DEFAULT (''),
			CREF_DATE				CHAR(8)			NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CREF_DATE			DEFAULT (''),
			CCHARGES_TYPE			VARCHAR(2)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CCHARGES_TYPE		DEFAULT (''),
			CCHARGES_ID				VARCHAR(20)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CCHARGES_ID			DEFAULT (''),
			CDISCOUNT_CODE			VARCHAR(8)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CDISCOUNT_CODE		DEFAULT (''),
			CINV_PERIOD_YEAR		VARCHAR(4)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CINV_PERIOD_YEAR		DEFAULT (''),
			CINV_PERIOD_MONTH		VARCHAR(2)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CINV_PERIOD_MONTH	DEFAULT (''),
			LALL_BUILDING			BIT				NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_LALL_BUILDING		DEFAULT (1),
			CBUILDING_ID			VARCHAR(20)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CBUILDING_ID			DEFAULT (''),
			CAGREEMENT_TYPE			VARCHAR(2)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CAGREEMENT_TYPE		DEFAULT (''),
			CDISCOUNT_STATUS		VARCHAR(2)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CDISCOUNT_STATUS		DEFAULT (''), /*01 - Used / 02 - Overwrite / 03 - Undo*/
			CPROCESS_BY				VARCHAR(8)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CPROCESS_BY			DEFAULT (''),
			CUPDATE_BY				VARCHAR(8)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CUPDATE_BY			DEFAULT ('SYSTEM'),
			DUPDATE_DATE			DATETIME		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_DUPDATE_DATE			DEFAULT (GETDATE()),
			CCREATE_BY				VARCHAR(8)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_CCREATE_BY			DEFAULT ('SYSTEM'),
			DCREATE_DATE			DATETIME		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_HD_DCREATE_DATE			DEFAULT (GETDATE()),

 CONSTRAINT LMT_DISCOUNT_HD01_PK PRIMARY KEY CLUSTERED 
( CCOMPANY_ID	ASC
, CPROPERTY_ID	ASC
, CREF_NO		ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

