
/****** OBJECT:  TABLE DBO.LMT_DISCOUNT_DT    SCRIPT DATE: 12/9/2019 5:48:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF (EXISTS (SELECT * 
					FROM INFORMATION_SCHEMA.TABLES 
					WHERE  TABLE_NAME = 'LMT_DISCOUNT_DT'))
DROP TABLE LMT_DISCOUNT_DT


CREATE TABLE DBO.LMT_DISCOUNT_DT(
			CCOMPANY_ID					VARCHAR(8)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CCOMPANY_ID					DEFAULT (''),
			CPROPERTY_ID				VARCHAR(20)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CPROPERTY_ID					DEFAULT (''),
			CREF_NO						VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CREF_NO						DEFAULT (''),
			CSEQ_NO						VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CSEQ_NO						DEFAULT (''),
			CFLOOR_ID					VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CFLOOR_ID					DEFAULT (''),
			CUNIT_ID					VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CUNIT_ID						DEFAULT (''),
			CTENANT_ID					VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CTENANT_ID					DEFAULT (''),
			NCHARGES_AMOUNT				VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_NCHARGES_AMOUNT				DEFAULT (0),
			NCHARGE_DISCOUNT			VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_NCHARGE_DISCOUNT				DEFAULT (0),
			NNET_CHARGE					VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_NNET_CHARGE					DEFAULT (0),
			CAGREEMENT_NO				VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CAGREEMENT_NO				DEFAULT (''),
			CSTART_DATE					VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CSTART_DATE					DEFAULT (''),
			CEND_DATE					VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CEND_DATE					DEFAULT (''),
			CEXISTING_DISCOUNT_CODE		VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CEXISTING_DISCOUNT_CODE		DEFAULT (''),
			NEXISTING_CHARGE_DISCOUNT	VARCHAR(30)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_NEXISTING_CHARGE_DISCOUNT	DEFAULT (0),

			CUPDATE_BY					VARCHAR(8)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CUPDATE_BY					DEFAULT ('SYSTEM'),
			DUPDATE_DATE				DATETIME		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_DUPDATE_DATE					DEFAULT (GETDATE()),
			CCREATE_BY					VARCHAR(8)		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_CCREATE_BY					DEFAULT ('SYSTEM'),
			DCREATE_DATE				DATETIME		NOT NULL CONSTRAINT DF_LMT_DISCOUNT_DT_DCREATE_DATE					DEFAULT (GETDATE()),

 CONSTRAINT LMT_DISCOUNT_DT01_PK PRIMARY KEY CLUSTERED 
( CCOMPANY_ID	ASC
, CPROPERTY_ID	ASC
, CREF_NO		ASC
, CSEQ_NO		ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

