//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMR00600BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMR00600BackResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMR00600BackResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMR00600BackResources.PMR00600BackResources_msgrsc", typeof(PMR00600BackResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOI / Agreement No..
        /// </summary>
        internal static string AGREEMENT_LABEL {
            get {
                return ResourceManager.GetString("AGREEMENT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string AMOUNT_LABEL {
            get {
                return ResourceManager.GetString("AMOUNT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string APRIL_LABEL {
            get {
                return ResourceManager.GetString("APRIL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string AUGUST_LABEL {
            get {
                return ResourceManager.GetString("AUGUST_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string BUILDING_LABEL {
            get {
                return ResourceManager.GetString("BUILDING_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string CHARGE_LABEL {
            get {
                return ResourceManager.GetString("CHARGE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string COLUMN_AMOUNT_LABEL {
            get {
                return ResourceManager.GetString("COLUMN_AMOUNT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string COLUMN_NOTE_LABEL {
            get {
                return ResourceManager.GetString("COLUMN_NOTE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Date.
        /// </summary>
        internal static string COLUMN_OVERTIME_DATE_LABEL {
            get {
                return ResourceManager.GetString("COLUMN_OVERTIME_DATE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string COLUMN_STATUS_LABEL {
            get {
                return ResourceManager.GetString("COLUMN_STATUS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenure.
        /// </summary>
        internal static string COLUMN_TENURE_LABEL {
            get {
                return ResourceManager.GetString("COLUMN_TENURE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time In.
        /// </summary>
        internal static string COLUMN_TIMEIN_LABEL {
            get {
                return ResourceManager.GetString("COLUMN_TIMEIN_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        internal static string COLUMN_TIMEOUT_LABEL {
            get {
                return ResourceManager.GetString("COLUMN_TIMEOUT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string COLUMN_UNIT_LABEL {
            get {
                return ResourceManager.GetString("COLUMN_UNIT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string COLUMN_UNIT_PRICE_LABEL {
            get {
                return ResourceManager.GetString("COLUMN_UNIT_PRICE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string DECEMBER_LABEL {
            get {
                return ResourceManager.GetString("DECEMBER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string DEPARTMENT_LABEL {
            get {
                return ResourceManager.GetString("DEPARTMENT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string FEBRUARY_LABEL {
            get {
                return ResourceManager.GetString("FEBRUARY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string GRANDTOTAL_LABEL {
            get {
                return ResourceManager.GetString("GRANDTOTAL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By.
        /// </summary>
        internal static string GROUP_BY_LABEL {
            get {
                return ResourceManager.GetString("GROUP_BY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string INVOICE_LABEL {
            get {
                return ResourceManager.GetString("INVOICE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        internal static string INVOICE_NO_LABEL {
            get {
                return ResourceManager.GetString("INVOICE_NO_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Status.
        /// </summary>
        internal static string INVOICE_STATUS_LABEL {
            get {
                return ResourceManager.GetString("INVOICE_STATUS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string JANUARY_LABEL {
            get {
                return ResourceManager.GetString("JANUARY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string JULY_LABEL {
            get {
                return ResourceManager.GetString("JULY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string JUNE_LABEL {
            get {
                return ResourceManager.GetString("JUNE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string LABEL_CHARGE {
            get {
                return ResourceManager.GetString("LABEL_CHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        internal static string LABEL_TENANT {
            get {
                return ResourceManager.GetString("LABEL_TENANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string MARCH_LABEL {
            get {
                return ResourceManager.GetString("MARCH_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string MAY_LABEL {
            get {
                return ResourceManager.GetString("MAY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string NOVEMBER_LABEL {
            get {
                return ResourceManager.GetString("NOVEMBER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string OCTOBER_LABEL {
            get {
                return ResourceManager.GetString("OCTOBER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string PERIOD_LABEL {
            get {
                return ResourceManager.GetString("PERIOD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string PROPERTY_LABEL {
            get {
                return ResourceManager.GetString("PROPERTY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string REPORT_TYPE_LABEL {
            get {
                return ResourceManager.GetString("REPORT_TYPE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string SEPTEMBER_LABEL {
            get {
                return ResourceManager.GetString("SEPTEMBER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string SERVICE_LABEL {
            get {
                return ResourceManager.GetString("SERVICE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string STATUS_LABEL {
            get {
                return ResourceManager.GetString("STATUS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total based on.
        /// </summary>
        internal static string SUBTOTAL_LABEL {
            get {
                return ResourceManager.GetString("SUBTOTAL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string TAX_LABEL {
            get {
                return ResourceManager.GetString("TAX_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        internal static string TENANT_LABEL {
            get {
                return ResourceManager.GetString("TENANT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TOTAL_LABEL {
            get {
                return ResourceManager.GetString("TOTAL_LABEL", resourceCulture);
            }
        }
    }
}
