//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAM00100FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FAM00100FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FAM00100FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FAM00100FrontResources.FAM00100FrontResources_msgrsc", typeof(FAM00100FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Cancel Soft Close.
        /// </summary>
        internal static string _AllowCancelSoftClose {
            get {
                return ResourceManager.GetString("_AllowCancelSoftClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Depreciation Transaction.
        /// </summary>
        internal static string _AutoDepreciationTrans {
            get {
                return ResourceManager.GetString("_AutoDepreciationTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Header for each asset.
        /// </summary>
        internal static string _AutoDeptA {
            get {
                return ResourceManager.GetString("_AutoDeptA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Header for each process.
        /// </summary>
        internal static string _AutoDeptP {
            get {
                return ResourceManager.GetString("_AutoDeptP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank-in Mode.
        /// </summary>
        internal static string _BankInMode {
            get {
                return ResourceManager.GetString("_BankInMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _BtnCancel {
            get {
                return ResourceManager.GetString("_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string _BtnCreate {
            get {
                return ResourceManager.GetString("_BtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string _By {
            get {
                return ResourceManager.GetString("_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Department.
        /// </summary>
        internal static string _ByDept {
            get {
                return ResourceManager.GetString("_ByDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque.
        /// </summary>
        internal static string _Cheque {
            get {
                return ResourceManager.GetString("_Cheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing in Progress.
        /// </summary>
        internal static string _ClosingInProgress {
            get {
                return ResourceManager.GetString("_ClosingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contra Account*.
        /// </summary>
        internal static string _ContraAccount {
            get {
                return ResourceManager.GetString("_ContraAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Period.
        /// </summary>
        internal static string _CurrentPeriod {
            get {
                return ResourceManager.GetString("_CurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate Type*.
        /// </summary>
        internal static string _CurrRateType {
            get {
                return ResourceManager.GetString("_CurrRateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate Type.
        /// </summary>
        internal static string _CurrRateTypeNotMand {
            get {
                return ResourceManager.GetString("_CurrRateTypeNotMand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Asset Department*.
        /// </summary>
        internal static string _DefaultAssetDept {
            get {
                return ResourceManager.GetString("_DefaultAssetDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Asset Department.
        /// </summary>
        internal static string _DefaultAssetDeptNotMand {
            get {
                return ResourceManager.GetString("_DefaultAssetDeptNotMand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Trans. Department*.
        /// </summary>
        internal static string _DefaultTransDept {
            get {
                return ResourceManager.GetString("_DefaultTransDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Trans. Department.
        /// </summary>
        internal static string _DefaultTransDeptNotMand {
            get {
                return ResourceManager.GetString("_DefaultTransDeptNotMand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail by Asset.
        /// </summary>
        internal static string _DetailByAsset {
            get {
                return ResourceManager.GetString("_DetailByAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Numbering by Cash/Bank Code.
        /// </summary>
        internal static string _DocNumByCashOrBank {
            get {
                return ResourceManager.GetString("_DocNumByCashOrBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Input Cheque Due Date.
        /// </summary>
        internal static string _EnableInputChequeDueDate {
            get {
                return ResourceManager.GetString("_EnableInputChequeDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FA System Parameter.
        /// </summary>
        internal static string _FASystemParameter {
            get {
                return ResourceManager.GetString("_FASystemParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex Gain Account*.
        /// </summary>
        internal static string _ForexGainAccount {
            get {
                return ResourceManager.GetString("_ForexGainAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex Loss Account*.
        /// </summary>
        internal static string _ForexLossAccount {
            get {
                return ResourceManager.GetString("_ForexLossAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Link Date.
        /// </summary>
        internal static string _GLLinkDate {
            get {
                return ResourceManager.GetString("_GLLinkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC Link Date.
        /// </summary>
        internal static string _ICLinkDate {
            get {
                return ResourceManager.GetString("_ICLinkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Incremental Asset Code by Journal Group.
        /// </summary>
        internal static string _IncrementalAssetCode {
            get {
                return ResourceManager.GetString("_IncrementalAssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Setup.
        /// </summary>
        internal static string _JournalSetup {
            get {
                return ResourceManager.GetString("_JournalSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Type.
        /// </summary>
        internal static string _JournalType {
            get {
                return ResourceManager.GetString("_JournalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FA System Parameter for this property has not been created!.
        /// </summary>
        internal static string _L01 {
            get {
                return ResourceManager.GetString("_L01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string _length {
            get {
                return ResourceManager.GetString("_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes?.
        /// </summary>
        internal static string _N01 {
            get {
                return ResourceManager.GetString("_N01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FA System Parameter Created Successfully!.
        /// </summary>
        internal static string _N02 {
            get {
                return ResourceManager.GetString("_N02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string _Period {
            get {
                return ResourceManager.GetString("_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PJ Link Date.
        /// </summary>
        internal static string _PJLinkDate {
            get {
                return ResourceManager.GetString("_PJLinkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through Batch Clearing Cheque.
        /// </summary>
        internal static string _RadioBBankInMode {
            get {
                return ResourceManager.GetString("_RadioBBankInMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Cheque Directly.
        /// </summary>
        internal static string _RadioDBankInMode {
            get {
                return ResourceManager.GetString("_RadioDBankInMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Close Period.
        /// </summary>
        internal static string _SoftClosePeriod {
            get {
                return ResourceManager.GetString("_SoftClosePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Closing in Progress.
        /// </summary>
        internal static string _SoftClosingProgress {
            get {
                return ResourceManager.GetString("_SoftClosingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary by Journal Group.
        /// </summary>
        internal static string _SummaryByJrnal {
            get {
                return ResourceManager.GetString("_SummaryByJrnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdatedBy {
            get {
                return ResourceManager.GetString("_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate Type is required!.
        /// </summary>
        internal static string V01 {
            get {
                return ResourceManager.GetString("V01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC Link Date is required!.
        /// </summary>
        internal static string V02 {
            get {
                return ResourceManager.GetString("V02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PJ Link Date is required!.
        /// </summary>
        internal static string V03 {
            get {
                return ResourceManager.GetString("V03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Close Period may not be later than IC Link Date Period!.
        /// </summary>
        internal static string V04 {
            get {
                return ResourceManager.GetString("V04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Close Period may not be later than PJ Link Date Period!.
        /// </summary>
        internal static string V05 {
            get {
                return ResourceManager.GetString("V05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Close Period may not be later than GL Link Date Period!.
        /// </summary>
        internal static string V06 {
            get {
                return ResourceManager.GetString("V06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Period may not be later than Soft Close Period!.
        /// </summary>
        internal static string V07 {
            get {
                return ResourceManager.GetString("V07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Link Date is required!.
        /// </summary>
        internal static string V08 {
            get {
                return ResourceManager.GetString("V08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans Dept Code is required!.
        /// </summary>
        internal static string V09 {
            get {
                return ResourceManager.GetString("V09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Dept Code is required!.
        /// </summary>
        internal static string V10 {
            get {
                return ResourceManager.GetString("V10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Trans. Department required!.
        /// </summary>
        internal static string V11 {
            get {
                return ResourceManager.GetString("V11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Asset Department required!.
        /// </summary>
        internal static string V12 {
            get {
                return ResourceManager.GetString("V12", resourceCulture);
            }
        }
    }
}
