<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <UserSecretsId>8783793f-5d17-4374-ab4f-a16967ef5909</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="FAM00100FrontResources_msgrsc.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FAM00100FrontResources_msgrsc.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="FAM00100FrontResources_msgrsc.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>FAM00100FrontResources_msgrsc.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
