//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMR03300FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMR03300FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMR03300FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMR03300FrontResources.PMR03300FrontResources_msgrsc", typeof(PMR03300FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _btn_cancel {
            get {
                return ResourceManager.GetString("_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string _btn_save {
            get {
                return ResourceManager.GetString("_btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string _label_saveas {
            get {
                return ResourceManager.GetString("_label_saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR Customer Analysis.
        /// </summary>
        internal static string _pageTitle {
            get {
                return ResourceManager.GetString("_pageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string _title_saveas {
            get {
                return ResourceManager.GetString("_title_saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string BTN_PRINT {
            get {
                return ResourceManager.GetString("BTN_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string BTN_SAVE_AS {
            get {
                return ResourceManager.GetString("BTN_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        internal static string CBASE_CURRENCY {
            get {
                return ResourceManager.GetString("CBASE_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Category.
        /// </summary>
        internal static string CCUSTOMER_CATEGORY {
            get {
                return ResourceManager.GetString("CCUSTOMER_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Id.
        /// </summary>
        internal static string CCUSTOMER_ID {
            get {
                return ResourceManager.GetString("CCUSTOMER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string CCUSTOMER_NAME {
            get {
                return ResourceManager.GetString("CCUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From*.
        /// </summary>
        internal static string CFROM {
            get {
                return ResourceManager.GetString("CFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress No/transaction &amp; Zero Balance.
        /// </summary>
        internal static string CHECK_BOX_SUPRESS {
            get {
                return ResourceManager.GetString("CHECK_BOX_SUPRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group.
        /// </summary>
        internal static string CJURNAL_GROUP {
            get {
                return ResourceManager.GetString("CJURNAL_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency.
        /// </summary>
        internal static string CLOCAL_CURRENCY {
            get {
                return ResourceManager.GetString("CLOCAL_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string CPROPERTY_ID {
            get {
                return ResourceManager.GetString("CPROPERTY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To*.
        /// </summary>
        internal static string CTO {
            get {
                return ResourceManager.GetString("CTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string CYEAR_FROM {
            get {
                return ResourceManager.GetString("CYEAR_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string CYEAR_TO {
            get {
                return ResourceManager.GetString("CYEAR_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Type.
        /// </summary>
        internal static string GROUP_BOX_CURRENCY_TYPE {
            get {
                return ResourceManager.GetString("GROUP_BOX_CURRENCY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        internal static string GROUP_BOX_FILTER_BY {
            get {
                return ResourceManager.GetString("GROUP_BOX_FILTER_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string GROUP_BOX_PERIOD {
            get {
                return ResourceManager.GetString("GROUP_BOX_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Customer Category .
        /// </summary>
        internal static string Validation_From_Customer_Category {
            get {
                return ResourceManager.GetString("Validation_From_Customer_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select From Customer ID.
        /// </summary>
        internal static string Validation_From_Customer_Id {
            get {
                return ResourceManager.GetString("Validation_From_Customer_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select From Customer Name.
        /// </summary>
        internal static string Validation_From_Customer_Name {
            get {
                return ResourceManager.GetString("Validation_From_Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select From Journal Group.
        /// </summary>
        internal static string Validation_From_Journal_Group {
            get {
                return ResourceManager.GetString("Validation_From_Journal_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select To Customer ID.
        /// </summary>
        internal static string Validation_To_Customer_Id {
            get {
                return ResourceManager.GetString("Validation_To_Customer_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select To Customer Name.
        /// </summary>
        internal static string Validation_To_Customer_Name {
            get {
                return ResourceManager.GetString("Validation_To_Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select To Journal Group.
        /// </summary>
        internal static string Validation_To_Journal_Group {
            get {
                return ResourceManager.GetString("Validation_To_Journal_Group", resourceCulture);
            }
        }
    }
}
