<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="R_APIBackEnd">
      <HintPath>..\..\..\..\..\SYSTEM\SOURCE\LIBRARY\Back\R_APIBackEnd.dll</HintPath>
    </Reference>
    <Reference Include="R_APICommon">
      <HintPath>..\..\..\..\..\SYSTEM\SOURCE\LIBRARY\Back\R_APICommon.dll</HintPath>
    </Reference>
    <Reference Include="R_APICommonDTO">
      <HintPath>..\..\..\..\..\SYSTEM\SOURCE\LIBRARY\Back\R_APICommonDTO.dll</HintPath>
    </Reference>
    <Reference Include="R_CommonFrontBackAPI">
      <HintPath>..\..\..\..\..\SYSTEM\SOURCE\LIBRARY\Back\R_CommonFrontBackAPI.dll</HintPath>
    </Reference>
    <Reference Include="R_OpenTelemetry">
      <HintPath>..\..\..\..\..\SYSTEM\SOURCE\LIBRARY\Back\R_OpenTelemetry.dll</HintPath>
    </Reference>
    <Reference Include="R_Storage">
      <HintPath>..\..\..\..\..\..\..\..\..\..\..\RealCode\RSF\BIMASAKTI_11\1.00\PROGRAM\SYSTEM\SOURCE\LIBRARY\Back\R_Storage.dll</HintPath>
    </Reference>
    <Reference Include="R_StorageCommon">
      <HintPath>..\..\..\..\..\..\..\..\..\..\..\RealCode\RSF\BIMASAKTI_11\1.00\PROGRAM\SYSTEM\SOURCE\LIBRARY\Back\R_StorageCommon.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\..\..\..\..\..\RealCode\RSF\BIMASAKTI_11\1.00\PROGRAM\BS Program\SOURCE\BACK\FA\FA_SPR\RSP_FAT00300_SAVE_TRANSResources\RSP_FAT00300_SAVE_TRANSResources.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\..\..\..\..\..\RealCode\RSF\BIMASAKTI_11\1.00\PROGRAM\BS Program\SOURCE\BACK\FA\FA_SPR\RSP_FAT00300_SUBMIT_TRANSResources\RSP_FAT00300_SUBMIT_TRANSResources.csproj" />
    <ProjectReference Include="..\..\..\COMMON\FA\FAT00300Common\FAT00300Common.csproj" />
    <ProjectReference Include="..\FAT00300BackResources\FAT00300BackResources.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

</Project>







