using System;
using System.Collections.Generic;
using System.Text;

namespace CBT02200COMMON.DTO
{
    public class ContextConstant
    {
        public const string CBT02200_GRID_HEADER_STREAMING_CONTEXT = "CBT02200_GRID_HEADER_STREAMING_CONTEXT";
        public const string CBT02200_GRID_DETAIL_REC_ID_STREAMING_CONTEXT = "CBT02200_GRID_DETAIL_REC_ID_STREAMING_CONTEXT";
        public const string CBT02210_CHEQUE_LIST_DETAIL_REC_ID_STREAMING_CONTEXT = "CBT02210_CHEQUE_LIST_DETAIL_REC_ID_STREAMING_CONTEXT";
    }
}
