using System;
using System.Collections.Generic;
using System.Text;

namespace GLT00500COMMON
{
    public class ContextConstant
    {
        public const string GLT00500_IMPORT_ADJUSTMENT_JOURNAL_ERROR_STREAMING_CONTEXT = "GLT00500_IMPORT_ADJUSTMENT_JOURNAL_ERROR_STREAMING_CONTEXT";
        public const string GLT00500_IMPORT_ADJUSTMENT_JOURNAL_STREAMING_CONTEXT = "GLT00500_IMPORT_ADJUSTMENT_JOURNAL_STREAMING_CONTEXT";
        public const string UPLOAD_GLT00500_ERROR_GUID_STREAMING_CONTEXT = "UPLOAD_GLT00500_ERROR_GUID_STREAMING_CONTEXT";
        public const string GLT00500_HEADER_DATA_STREAMING_CONTEXT = "GLT00500_HEADER_DATA_STREAMING_CONTEXT";
        public const string GLT00500_DETAIL_DATA_STREAMING_CONTEXT = "GLT00500_DETAIL_DATA_STREAMING_CONTEXT";
        public const string GLT00500_PROCESS_ID_STREAMING_CONTEXT = "GLT00500_PROCESS_ID_STREAMING_CONTEXT";
        public const string GLT00500_ERROR_GUID_STREAMING_CONTEXT = "GLT00500_ERROR_GUID_STREAMING_CONTEXT";
        public const string GLT00500_HEADER_DATA_CONTEXT = "GLT00500_HEADER_DATA_CONTEXT";
        public const string GLT00500_PROCESS_ID_CONTEXT = "GLT00500_PROCESS_ID_CONTEXT";
        public const string GLT00500_LANGUAGE_ID_CONTEXT = "GLT00500_LANGUAGE_ID_CONTEXT";
        public const string GLT00500_SAVE_IMPORT_ADJUSTMENT_JOURNAL_CONTEXT = "GLT00500_SAVE_IMPORT_ADJUSTMENT_JOURNAL_CONTEXT";
        public const string UPLOAD_GLT00500_ERROR_COUNT_GUID_CONTEXT = "UPLOAD_GLT00500_ERROR_COUNT_GUID_CONTEXT";
    }
}
