//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_HD_MAINTAIN_PUBLIC_LOCATIONResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_HD_MAINTAIN_PUBLIC_LOCATIONResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_HD_MAINTAIN_PUBLIC_LOCATIONResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_HD_MAINTAIN_PUBLIC_LOCATIONResources.RSP_HD_MAINTAIN_PUBLIC_LOCATIONResources" +
                            "_msgrsc", typeof(RSP_HD_MAINTAIN_PUBLIC_LOCATIONResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error process, please contact your administrator!.
        /// </summary>
        internal static string _0401 {
            get {
                return ResourceManager.GetString("0401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Public Location Id!.
        /// </summary>
        internal static string _0402 {
            get {
                return ResourceManager.GetString("0402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete, Public Location already in used!.
        /// </summary>
        internal static string _0403 {
            get {
                return ResourceManager.GetString("0403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Location Id cannot be empty!.
        /// </summary>
        internal static string _0404 {
            get {
                return ResourceManager.GetString("0404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Location Name cannot be empty!.
        /// </summary>
        internal static string _0405 {
            get {
                return ResourceManager.GetString("0405", resourceCulture);
            }
        }
    }
}
