EXEC [RSP_PMA00400_GET_HEADER_LIST]

EXEC RSP_PM_GET_HANDOVER_EMPLOYEE_LIST
@CCOMPANY_ID = 'bsi',
@CPROPERTY_ID = 'ashmd',
@CDEPT_CODE ='00',
@CTRANS_CODE ='802013',
@CREF_NO ='LOI-SU-00-20250200001',
@LASSIGNED = 1


RSP_PMA00400_GET_HEADER_LIST

EXEC RSP_PM_GET_HANDOVER_CHECKLIST_LIST
@CCOMPANY_ID  = '',
@CPROPERTY_ID = '',
@CDEPT_CODE	  = '',
@CTRANS_CODE  = '',
@CREF_NO	  = '',
@CUNIT_ID	  = '',
@CFLOOR_ID	  = '',
@CBUILDING_ID = ''


EXEC RSP_PM_GET_HANDOVER_UTILITY_LIST 
@CCOMPANY_ID   = 'BSI',
@CPROPERTY_ID  = 'ASHMD',
@CDEPT_CODE	   = '00',
@CTRANS_CODE   = '802061',
@CREF_NO	   = 'LOI-U-2024100093',
@CLANG_ID	   = 'En',
@CUNIT_ID	   = 'U-F2-07',
@CBUILDING_ID  = 'TW-1',
@CFLOOR_ID	   = 'FLR02'
 --01 02 NMETER START = -
 --03 04 NBLOCK START = -
SELECT dbo.RFN_GET_COMPANY_LOGO('RCD') as CLOGO
select * from SAM_COMPANIES where CCOMPANY_ID ='bsi'

select * from STORAGE_DATA_TABLE where CSTORAGE_ID= '20b430600224409bbc035dcdf016c38f' --20b430600224409bbc035dcdf016c38f
select * from STORAGE_DATA_TABLE where CSTORAGE_ID= '20b430600224409bbc035dcdf016c38f'
select * from SAB_PLATFORM
exec RSP_PM_GET_HANDover


EXEC [RSP_PMA00400_GET_IMAGES] 
@CCOMPANY_ID		='BSI',		
@CPROPERTY_ID		='ASHMD',
@CDEPT_CODE			='00',
@CTRANS_CODE		='802061',
@CREF_NO			='LOI-U-2024100045',
@CUNIT_ID			='U-F1-01',
@CFLOOR_ID			='FLR01',
@CBUILDING_ID		='TW-1',
@CIMAGE_TYPE		='01',	-- '01'='', - CHECKLIST, '02' - UTILITY
@CLANG_ID			='EN'


- bikin report
--TRANSACTION
- upload to storage return storage id
- menjadi param [RSP_PMA00400_SAVE_PDF]
-
EXEC [RSP_PMA00400_SAVE_PDF]
@CCOMPANY_ID
@CPROPERTY_ID
@CDEPT_CODE
@CTRANS_CODE
@CREF_NO
@CUNIT_ID
@CFLOOR_ID
@CBUILDING_ID
@CSTORAGE_ID
@CPROGRAM_ID
-- commit

RESOURCE [RSP_PMA00400_SAVE_PDF]
8001 -- Error process, please contact your administrator!
8002 -- Cannot find agreement unit data!
8003 -- Storage ID is empty! 


 EXEC [RSP_SA_GET_DOMAIN_TYPE_URL] 'GENERAL_API' ,'HANDOVER_SUMMARY'
domain/apiurl/guid
172.....:8080/api/pm/getfile/23d68g8hugy89h9


/* Dilakukan setelah semua report selesai dibuat 
EXEC [RSP_PMA00400_SEND_EMAIL]
@CPROGRAM_ID		
@CGET_FILE_API_URL -- http://172.16.0.79:5101/PM/api/PMA00400/GetFile
@CLANG_ID			http://172.16.0.79:5705/api/PMA00400/GetFileHandover
*/
setelah proses semua data dalam satu tenant, jalankan sp dibawah
begin transaction
exec RSP_PMA00400_SEND_EMAIL
@CPROGRAM_ID ='PMA00400',
@CGET_FILE_API_URL = 'http://172.16.0.79:5705/api/PMA00400/GetFileHandover',
@CDB_TENANT_ID  = 'Tenant_df',--- R_BackGlobalVar.CTENANT_ID
@CLANG_ID ='en'

rollback

RESOURCE [RSP_PM_HANDOVER_NOTIFICATION] -- dipanggil oleh [RSP_PMA00400_SEND_EMAIL]
8001 -- Error process, please contact your administrator!
8002 -- Company ID is empty!
8003 -- Company ID is not found!
8004 -- Property ID is empty!
8005 -- Property ID is not found!
8006 -- Dept Code is empty!
8007 -- Dept Code is not found!
8008 -- Trans Code is empty!
8009 -- Trans Code is not found!
8010 -- Ref No is empty!
8011 -- Ref No is not found!
8012 -- No receiver found!
8013 -- No email template for CARE Notification found, please set email template with Template ID "DONE_HANDOVER" in program Email Template (SAM02100)!

SETELAH PROSES PEMBUATAN REPORT TELAH SELESAI MAKA, 
-SP AKAN MELAKUKAN HIT PADA GENERAL API DENGAN PARAMETER TENANT DAN GUID.
-SP AKAN MENGEMBALIKAN GUID BARU, YANG KEMUDIAN LANGSUNG DIPROSES UNTUK MENYIMPAN KE LOKAL USER  BERUPA
	PDF-NYA

EXEC [RSP_PMA00400_GET_HANDOVER_PDF_URL]
@CGUID = 'abc'

rollback

select * from STORAGE_DATA_TABLE
order by DCREATE_DATE desc

select * from PMT_AGREEMENT_UNIT_IMAGES
where CIMAGE_TYPE = '05'

RSP_PMA00400_GET_IMAGES

SP
begin transaction
exec RSP_PMA00400_GET_HANDOVER_STORAGE_ID
@CGUID = 'FADB939E-039B-4172-9928-A3221873886D'


CIMAGE_STORAGE_ID
b84166f737f14ff49cbfa0bfb5439893

select * from SAM_COMPANIES where CCOMPANY_ID ='BSI'


RSP_PMA00400_GET_IMAGES

EXEC RSP_PM_GET_HANDOVER_UTILITY_LIST 
@CCOMPANY_ID   = 'BSI',
@CPROPERTY_ID  = 'ASHMD',
@CDEPT_CODE	   = '00',
@CTRANS_CODE   = '802061',
@CREF_NO	   = 'LOI-U-2024100093',
@CLANG_ID	   = 'En',
@CUNIT_ID	   = 'U-F2-07',
@CBUILDING_ID  = 'TW-1',
@CFLOOR_ID	   = 'FLR02'
 --01 02 NMETER START = -
 --03 04 NBLOCK START = -
 CCHARGES_TYPE


 USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_PM_GET_HANDOVER_SCHEDULE_LIST]
		@CCOMPANY_ID = 'bsi',
		@CPROPERTY_ID = 'ashmd',
		@CTYPE = 'L',
		@CHANDOVER_STATUS = '04',
		@CBUILDING_ID = 'TW-1',
		@CFROM_DATE = '20241001',
		@CTO_DATE = '20250227'

SELECT	'Return Value' = @return_value

GO


 select * from PMT_AGREEMENT_UNIT_IMAGES where CIMAGE_TYPE = '05'
 use RealMainDb
 
 select * from RealMainDb
 EXEC [RSP_SA_GET_DOMAIN_TYPE_URL] 'GENERAL_API' ,'HANDOVER_SUMMARY'


select * from SAB_MULTI_TENANT_DB
select * from SAM_DOMAIN_DT
select * from SAM_DOMAIN_HD
CDOMAIN_ID	CDOMAIN_NAME	CDOMAIN_URL	CDOMAIN_TYPE_ID	CDOMAIN_TYPE_NAME	CDOMAIN_TYPE_URL	CDOMAIN_TYPE_HTTP_METHOD
GENERAL_API	Domain for General API	http://172.16.0.79:5705/	HANDOVER_SUMMARY	API Path to get handover summary file	api/PMA00400/GetFileHandover	GET

use BIMASAKTI_11

delete from SAT_LOCKING where CUSER_ID = 'aoc'

select top 10* from PMT_AGREEMENT where   CTRANS_CODE ='802061'

EXEC [RSP_PMA00400_GET_HEADER_LIST]


EXEC [RSP_PMA00400_GET_IMAGES] 
@CCOMPANY_ID		='BSI',		
@CPROPERTY_ID		='ASHMD',
@CDEPT_CODE			='00',
@CTRANS_CODE		='802061',
@CREF_NO			='LOI-U-2024100045',
@CUNIT_ID			='U-F2-06',
@CFLOOR_ID			='FLR02',
@CBUILDING_ID		='TW-1',
@CIMAGE_TYPE		='02',--'01',	-- '01'='', - CHECKLIST, '02' - UTILITY
@CLANG_ID			='EN'

CIMAGE_STORAGE_ID
a6cca74afbd54cfea575fb73da0f106e


EXEC [RSP_PMA00400_GET_IMAGES] 
@CCOMPANY_ID		='BSI',		
@CPROPERTY_ID		='ASHMD',
@CDEPT_CODE			='00',
@CTRANS_CODE		='802061',
@CREF_NO			='LOI-U-2024100045',
@CUNIT_ID			='U-F2-06',
@CFLOOR_ID			='FLR02',
@CBUILDING_ID		='TW-1',
@CIMAGE_TYPE		='02',--'01',	-- '01'='', - CHECKLIST, '02' - 
@CLANG_ID			='EN'

UTILITY CDESCRIPTION	CCHARGES_TYPE_DESCRIPTION
Electricity					Electricity

SELECT 
    ST.CFILE_NAME AS FileName,
    ST.CFILE_EXTENSION AS FileExtension,
    ST.CURL_DATA AS Url,
    ST.ODATA AS Data,
    ST.CSTORAGE_PROVIDER_ID AS StorageProvider,
    ISNULL(PL.CAPI_CLIENT_ID, '') AS AccountName,
    ISNULL(PL.CAPI_CLIENT_SECRET, '') AS SharedKey
FROM STORAGE_DATA_TABLE ST WITH (NOLOCK)
LEFT JOIN SAB_PLATFORM PL WITH (NOLOCK)
    ON PL.CPLATFORM_ID = 
       CASE 
           WHEN ST.CSTORAGE_PROVIDER_ID = 'CS_AZURE' THEN 'AZURE'
           WHEN ST.CSTORAGE_PROVIDER_ID = 'CS_GOOGLE' THEN 'GOOGLE'
           ELSE NULL
       END
WHERE ST.CSTORAGE_ID = '97b8938646bd4d31b6804e54fd29ee2f' 
AND ST.LDELETE_FLAG = 0;

EXEC [RSP_PMA00400_GET_HEADER_LIST]

--- Lakuin ini kalau udah sampe kirim email
UPDATE A 
SET LHAS_DISTRIBUTED = 0
FROM PMT_AGREEMENT A 
WHERE A.CREF_NO = 'LOI-U-2024100045'
--- Lakuin ini kalau udah RSP_PMA00400_SAVE_PDF
DELETE FROM PMT_AGREEMENT_UNIT_IMAGES WHERE CIMAGE_TYPE = '05' AND CREF_NO = 'LOI-U-2024100045'

CCARE_TICKET_NO
, , , CARE-202503-00000000012-TICKET, CARE-202503-00000000012-TICKET

select * from STORAGE_DATA_TABLE
order by DCREATE_DATE desc
