RSP_GS_GET_PAYMENT_TERM_LIST 'RCD', 'ASHMD', 'hmc'
RSP_GS_GET_PAYMENT_TERM_LIST 'RCD', 'JBMPC', 'hmc'
RSP_GS_GET_PAYMENT_TERM_LIST 'RCD', 'LMPNG', 'hmc'
select * from SAM_USER_LOCKING
USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_GS_MAINTAIN_PAYMENT_TERM]
		@CCOMPANY_ID = N'RCD',
		@CPROPERTY_ID = N'ASHMD',
		@CPAY_TERM_CODE = N'T11',
		@CPAY_TERM_NAME = N'Term 11 Day',
		@IPAY_TERM_DAYS = 11,
		@CACTION = N'EDIT',
		@CUSER_ID = N'hmc'

SELECT	'Return Value' = @return_value

GO
GSM_PAYMENT_TERM
•	GSM_JRNGRP
•	GSM_JRNGRP_GOA
•	GSM_JRNGRP_GOA_DEPT

select * from SAM_USER_LOCKING