RSP_GS_GET_TRANS_CODE_LIST 'rcd','hmc';

--LIST TRANS CODE--

RSP_GS_GET_TRANS_CODE_INFO 'rcd' , '000020'


RSP_GS_GET_TRANS_CODE_LIST 'rcd', 'hmc'

SELECT * FROM RFT_GET_GSB_CODE_INFO ('SIAPP', 'rcd', '_GS_REFNO_DELIMITER', '', 'en')

RSP_GS_GET_TRANS_CODE_INFO 'rcd', '000000'

RSP_GS_GET_TRANS_CODE_APPROVER_LIST  'rcd', '000010', 'hmc','acc'

RSP_GS_GET_TRANS_CODE_DEPT_LIST 'rcd', '000010', 'hmc'

RSP_GS_GET_DEPT_LOOKUP_LIST 'rcd', 'hmc'

RSP_GS_GET_TRANS_CODE_APPROVER_LIST