use BIMASAKTI_11

--Password: CD-r5fdbsvr1#
delete from U  whe
where 
CKEY_VALUE='rcd|802041'
rollback
select * from SAM_USER_LOCKING


SELECT VAR_SELECTED = 0, A.*, C.CDESCRIPTION AS CAPPROVAL_STATUS_DESC, B.CTRANSACTION_NAME, B.CTABLE_NAME, B.CPROGRAM_ID 
FROM GST_APPROVAL_I A (NOLOCK) 
INNER JOIN GSM_TRANSACTION_CODE B (NOLOCK) ON B.CCOMPANY_ID = A.CCOMPANY_ID AND B.CTRANSACTION_CODE = A.CTRANSACTION_CODE 
INNER JOIN RFT_GET_GSB_CODE_INFO('SIAPP', 'RCD', '_GS_APPROVAL_STATUS', '', 'HPC') C ON C.CCODE = A.CAPPROVAL_STATUS
WHERE A.CUSER_ID = 'HPC' AND A.CAPPROVAL_STATUS = '01'  AND A.CTRANSACTION_STATUS IN ('01','02')
ORDER BY B.CTRANSACTION_NAME, A.CREFERENCE_DATE ASC

SELECT *FROM GST_APPROVAL_I 


select * from GSM_TRANSACTION_CODE
select * from GST_APPROVAL_I
delete from  GST_APPROVAL_I where CREFERENCE_NO = 'REF.202306.0003'
--•	Combobox. “Reason of Rejection”
SELECT * FROM RFT_GET_GSB_CODE_INFO('SIAPP', 'rcd', '_GS_REJECTTRANS_REASON',' ','EN')
SELECT * FROM RFT_GET_GSB_CODE_INFO('SIAPP', 'RCD', '_GS_REJECTTRANS_REASON', '' , 'EN') 

Select CCOMPANY_ID From GST_APPROVAL_I (Updlock) 
Where CCOMPANY_ID = 'rcd' And CTRANSACTION_CODE = '000000' And CDEPT_CODE = 'ACC' And CREFERENCE_NO = 'REF.202306.0001' And CTRANSACTION_STATUS In (01,02); 
Update GST_APPROVAL_I Set CAPPROVAL_STATUS= '01' FROM GST_APPROVAL_I A (NOLOCK)

select * from GST_APPROVAL_I (updlock) 
select * FROM GST_APPROVAL_I 
select 
CCODE	CDESCRIPTION
01                  	Invalid Data Entry

WITH Inbox.CurrentSelectedRecord:
Set Var_Company_Id = 'RCD',
Set Var_Transaction_Code = .CTRANSACTION_CODE
Set Var_Department_Code = .CDEPT_CODE
Set Var_Reference_No = .CREFERENCE_NO
Run program .CPROGRAM_ID With Parameters: Var_Company_Id And Var_Transaction_Code And Var_Department_Code And Var_Reference_No + Access View Only
End WITH

SELECT VAR_SELECTED = 1, A.*, C.CDESCRIPTION AS CTRANSACTION_STATUS_DESC, B.CTRANSACTION_NAME, B.CPROGRAM_ID FROM GST_APPROVAL_O A (NOLOCK) 
INNER JOIN GSM_TRANSACTION_CODE B (NOLOCK) ON B.CCOMPANY_ID = A.CCOMPANY_ID AND B.CTRANSACTION_CODE = A.CTRANSACTION_CODE 
INNER JOIN DBO.RFT_GET_GSB_CODE_INFO('SIAPP', 'RCD', '_STATUS_FLAG_01', '','EN') C ON C.CCODE = A.CTRANSACTION_STATUS
WHERE A.CUSER_ID = 'HPC' AND A.CTRANSACTION_STATUS IN ('01','02')
ORDER BY B.CTRANSACTION_NAME, A.CREFERENCE_DATE ASC



SELECT B.CUSER_NAME FROM SAM_USER_COMPANY A (NOLOCK) 
INNER JOIN SAM_USER B (NOLOCK) ON B.CUSER_ID = A.CUSER_ID 
WHERE A.CCOMPANY_ID = 'Rcd' AND A.CUSER_ID = 'IB'

select * from SAM_USER_COMPANY
select * from SAM_USER




SELECT VAR_SELECTED = 1, A.*, C.CDESCRIPTION AS CTRANSACTION_STATUS_DESC, B.CTRANSACTION_NAME, B.CPROGRAM_ID FROM GST_APPROVAL_O A (NOLOCK) 
INNER JOIN GSM_TRANSACTION_CODE B (NOLOCK) ON B.CCOMPANY_ID = A.CCOMPANY_ID AND B.CTRANSACTION_CODE = A.CTRANSACTION_CODE 
INNER JOIN DBO.RFT_GET_GSB_CODE_INFO('SIAPP', 'rcd', '_STATUS_FLAG_01', '', 'en') C ON C.CCODE = A.CTRANSACTION_STATUS
WHERE A.CUSER_ID = 'HPC' AND A.CTRANSACTION_STATUS IN ('01','02')
ORDER BY B.CTRANSACTION_NAME, A.CREFERENCE_DATE ASC

-------------------------INBOX-----------------------------

SELECT VAR_SELECTED = 0, A.*, C.CDESCRIPTION AS CAPPROVAL_STATUS_DESC, B.CTRANSACTION_NAME, B.CTABLE_NAME, B.CPROGRAM_ID 
FROM GST_APPROVAL_I A (NOLOCK) 
INNER JOIN GSM_TRANSACTION_CODE B (NOLOCK) ON B.CCOMPANY_ID = A.CCOMPANY_ID AND B.CTRANSACTION_CODE = A.CTRANSACTION_CODE 
INNER JOIN RFT_GET_GSB_CODE_INFO('SIAPP', 'RCD', '_GS_APPROVAL_STATUS', '', 'HMC') C ON C.CCODE = A.CAPPROVAL_STATUS
WHERE A.CUSER_ID = 'HMC' AND A.CAPPROVAL_STATUS = '01'  AND A.CTRANSACTION_STATUS IN ('01','02')
ORDER BY B.CTRANSACTION_NAME, A.CREFERENCE_DATE ASC

select * from GLT_TRANS_HD

SELECT VAR_SELECTED = 0, A.*, C.CDESCRIPTION AS CAPPROVAL_STATUS_DESC, B.CTRANSACTION_NAME,
                              B.CTABLE_NAME, B.CPROGRAM_ID FROM GST_APPROVAL_I A (NOLOCK) 
                              INNER JOIN GSM_TRANSACTION_CODE B (NOLOCK) 
                              ON B.CCOMPANY_ID = A.CCOMPANY_ID AND B.CTRANSACTION_CODE = A.CTRANSACTION_CODE 
                              INNER JOIN RFT_GET_GSB_CODE_INFO('SIAPP', 'Rcd',
                              '_GS_APPROVAL_STATUS', '', 'en') C 
                              ON C.CCODE = A.CAPPROVAL_STATUS 
                              WHERE A.CUSER_ID = 'hpc' AND A.CAPPROVAL_STATUS = '01'  AND A.CTRANSACTION_STATUS IN ('01','02') 
                              ORDER BY B.CTRANSACTION_NAME, A.CREFERENCE_DATE ASC
select * from GST_APPROVAL_I
select * from GSM_TRANSACTION_CODE
select * from RFT_GET_GSB_CODE_INFO('SIAPP', 'Rcd',
                              '_GS_APPROVAL_STATUS', '', 'en')

Select CCOMPANY_ID From GST_APPROVAL_I (Updlock) 
Where CCOMPANY_ID = 'rcd' And CTRANSACTION_CODE = '000010' And CDEPT_CODE = 'ACC' And CREFERENCE_NO = 'REF.202306.0001' And CTRANSACTION_STATUS In (01,02); 
Update GST_APPROVAL_I Set CAPPROVAL_STATUS= '01' FROM GST_APPROVAL_I A (NOLOCK)

--value 2
Select CCOMPANY_ID From GST_APPROVAL_I (Updlock) 
Where CCOMPANY_ID = 'rcd' And CTRANSACTION_CODE = '000010' And CDEPT_CODE = 'ACC' And CREFERENCE_NO = 'REF.202306.0003' And CTRANSACTION_STATUS In (00,02); 
Update GST_APPROVAL_I Set CAPPROVAL_STATUS= '01' FROM GST_APPROVAL_I A (NOLOCK)

select * from GST_APPROVAL_I 
insert into GST_APPROVAL_I 
(CCOMPANY_ID, CTRANSACTION_CODE, CDEPT_CODE,CREFERENCE_NO ,CUSER_ID, CAPPROVAL_USER_ID, CPERIOD, ISEQUENCE, CREFERENCE_DATE,  CAPPROVAL_STATUS, CTRANSACTION_STATUS)
Values 
('rcd', '000010', 'ACC', 'REF.202306.0004', 'HPC', 'HPC', '202306', 1, '20230620', '01', '01')

Select CCOMPANY_ID From GST_APPROVAL_I  (Updlock) Where CCOMPANY_ID = 'rcd' And CTRANSACTION_CODE = 'Normal Journal' And CDEPT_CODE = 'ACC'And CREFERENCE_NO = 'REF.202306.0001' And CTRANSACTION_STATUS In (01,02) 
UPDATE GST_APPROVAL_I SET CAPPROVAL_STATUS= '02' 
FROM GST_APPROVAL_I A (NOLOCK) WHERE A.CCOMPANY_ID= 'rcd' AND A.CTRANSACTION_CODE = '000000' AND A.CDEPT_CODE= 'ACC' AND A.CREFERENCE_NO= 'REF.202306.0001' AND A.CUSER_ID = 'hmc' AND A.CAPPROVAL_STATUS= '01'

rollback;

SELECT * FROM RFT_GET_GSB_CODE_INFO('SIAPP', 'RCD', '_GS_REJECTTRANS_REASON', '' , 'EN') 

UPDATE GST_APPROVAL_I 
SET CAPPROVAL_STATUS	= '01'
FROM GST_APPROVAL_I A (NOLOCK) 
WHERE A.CCOMPANY_ID	= 'RCD'
AND A.CTRANSACTION_CODE 	= '000000'
AND A.CDEPT_CODE		= 'ACC'
AND A.CREFERENCE_NO	= 'REF.202306.0001'
AND A.CUSER_ID		= 'HPC'
AND A.CAPPROVAL_STATUS	= '02'

select *
FROM GST_APPROVAL_I A (NOLOCK) 
WHERE A.CCOMPANY_ID	= 'RCD'
AND A.CTRANSACTION_CODE 	= '000000'
AND A.CDEPT_CODE		= 'ACC'
AND A.CREFERENCE_NO	= 'REF.202306.0001'
AND A.CUSER_ID		= 'HPC'
AND A.CAPPROVAL_STATUS	= '02'


-------------------------OUTBOX-----------------------------

   SELECT VAR_SELECTED = 1, A.*, C.CDESCRIPTION AS CTRANSACTION_STATUS_DESC, B.CTRANSACTION_NAME,
                   B.CPROGRAM_ID FROM GST_APPROVAL_O A(NOLOCK) 
                   INNER JOIN GSM_TRANSACTION_CODE B(NOLOCK) ON B.CCOMPANY_ID = A.CCOMPANY_ID 
                   AND B.CTRANSACTION_CODE = A.CTRANSACTION_CODE 
                    INNER JOIN DBO.RFT_GET_GSB_CODE_INFO('SIAPP', 'rcd', 
                    '_STATUS_FLAG_01', '', 'en') C 
                    ON C.CCODE = A.CTRANSACTION_STATUS
                   WHERE A.CUSER_ID = 'hpc' AND A.CTRANSACTION_STATUS IN('01','02') 
                   ORDER BY B.CTRANSACTION_NAME, A.CREFERENCE_DATE ASC

				    -----------------------OUTBOX list of Approve by – Outbox

 SELECT C.*, D.CUSER_NAME, D.CPOSITION, E.CDESCRIPTION AS CAPPROVAL_STATUS_DESC FROM GST_APPROVAL_I C (NOLOCK) 
INNER JOIN SAM_USER D (NOLOCK) ON D.CUSER_ID = C.CUSER_ID 
INNER JOIN RFT_GET_GSB_CODE_INFO ('SIAPP', 'RCD', '_GS_APPROVAL_STATUS', '', 'EN') E ON C.CAPPROVAL_STATUS = E.CCODE
WHERE C.CCOMPANY_ID     = 'RCD'
AND C.CTRANSACTION_CODE = '000000'
AND C.CDEPT_CODE        = 'ACC'
AND C.CREFERENCE_NO     = 'REF.202306.0001'
ORDER BY C.CUSER_ID, C.ISEQUENCE ASC

SELECT * FROM RFT_GET_GSB_CODE_INFO(‘SIAPP’, [Login User].[CCOMPANY_ID], ‘_GS_REJECTTRANS_REASON’, ‘’, [Login User].[CLANGUAGE_ID])
				   -------------------------DRAFT-----------------------------

SELECT VAR_SELECTED = 1, A.*, B.CTRANSACTION_NAME, B.CPROGRAM_ID FROM GST_APPROVAL_O A(NOLOCK) 
INNER JOIN GSM_TRANSACTION_CODE B(NOLOCK) ON B.CCOMPANY_ID = A.CCOMPANY_ID
AND B.CTRANSACTION_CODE = A.CTRANSACTION_CODE 
WHERE A.CUSER_ID = 'HPC' AND A.CTRANSACTION_STATUS = '00'

UPDATE GST_APPROVAL_I 
SET CAPPROVAL_STATUS	= '02'
FROM GST_APPROVAL_I A (NOLOCK) 
WHERE A.CCOMPANY_ID	= 'RCD'
AND A.CTRANSACTION_CODE 	= '000000'
AND A.CDEPT_CODE		= 'ACC'
AND A.CREFERENCE_NO	= 'REF.202306.0001'
AND A.CUSER_ID		= 'HPC'
AND A.CAPPROVAL_STATUS	= '01'
-----------------LOCKING
 Select CCOMPANY_ID From GST_APPROVAL_I  (Updlock)
Where CCOMPANY_ID = '{poParameter.CCOMPANYID}' And CTRANSACTION_CODE = '{item.CTRANSACTION_NAME}' 
 And CDEPT_CODE = '{item.CDEPT_CODE}'And CREFERENCE_NO = '{item.CREFERENCE_NO}' And CTRANSACTION_STATUS In (01,02)

 select CCOMPANY_ID from GST_APPROVAL_I
 
 exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd','jbmpc', '02', 'hmc'

 SELECT VAR_SELECTED = 0, A.*--, C.CDESCRIPTION AS CAPPROVAL_STATUS_DESC, B.CTRANSACTION_NAME, B.CTABLE_NAME, B.CPROGRAM_ID 
FROM GST_APPROVAL_I A (NOLOCK) 
INNER JOIN GSM_TRANSACTION_CODE B (NOLOCK) ON B.CCOMPANY_ID = A.CCOMPANY_ID AND B.CTRANSACTION_CODE = A.CTRANSACTION_CODE 
INNER JOIN RFT_GET_GSB_CODE_INFO('SIAPP', 'RCD', '_GS_APPROVAL_STATUS', '', 'EN') C ON C.CCODE = A.CAPPROVAL_STATUS
WHERE A.CUSER_ID = 'HPC' AND A.CAPPROVAL_STATUS = '01'  AND A.CTRANSACTION_STATUS IN ('01','02')
ORDER BY B.CTRANSACTION_NAME, A.CREFERENCE_DATE ASC

--LIst Inbox update 

Select CCOMPANY_ID From GST_APPROVAL_I (Updlock) 
Where CCOMPANY_ID = 'rcd' And CTRANSACTION_CODE = '000010' And CDEPT_CODE = 'ACC' And CREFERENCE_NO = 'REF.202306.0001' And CTRANSACTION_STATUS In (01,02); 
Update GST_APPROVAL_I Set CAPPROVAL_STATUS= '01' FROM GST_APPROVAL_I A (NOLOCK)

--value 2
Select CCOMPANY_ID From GST_APPROVAL_I (Updlock) 
Where CCOMPANY_ID = 'rcd' And CTRANSACTION_CODE = '000010' And CDEPT_CODE = 'ACC' And CREFERENCE_NO = 'REF.202306.0003' And CTRANSACTION_STATUS In (00,02); 
Update GST_APPROVAL_I Set CAPPROVAL_STATUS= '01' FROM GST_APPROVAL_I A (NOLOCK)

--To look detail error on temporary table
EXECUTE RSP_ConvertXMLToTable 'RCD', 'HPC', 'd83abc9b31784a63a5bec3f66ad38836'

select * from GST_APPROVAL_I
select * from SAM_USER_LOCKING
/*
GST_APPROVAL_I
SELECT CCOMPANY_ID From GST_APPROVAL_I (Updlock) 
Where CCOMPANY_ID = 'rcd' And CTRANSACTION_NAME = 'Normal Journal' And CDEPT_CODE = 'ACC'And CREFERENCE_NO = 'REF.202306.0001' And CTRANSACTION_STATUS In (01,02) 
Select CCOMPANY_ID From .CTABLE_NAME (Updlock) 
Where CCOMPANY_ID = .CCOMPANY_ID And CTRANSACTION_NAME = .CTRANSACTION_CODE And CDEPT_CODE = .CDEPT_CODE And CREFERENCE_NO = .CREFERENCE_NO And CTRANSACTION_STATUS In (01,02)
*/

select * from GLT_TRANS_HD

Select CCOMPANY_ID From GLT_TRANS_HD (Updlock) 
Where CCOMPANY_ID = .CCOMPANY_ID And CTRANSACTION_NAME = .CTRANSACTION_CODE And CDEPT_CODE = .CDEPT_CODE And CREFERENCE_NO = .CREFERENCE_NO And CTRANSACTION_STATUS In (01,02)

--PROCESS APPROVE
SELECT CCOMPANY_ID From GLT_TRANS_HD (Updlock) 
Where CCOMPANY_ID = 'rcd' And CTRANSACTION_NAME = 'Normal Journal' And CDEPT_CODE = 'HRD'And CREFERENCE_NO = 'REF.202308.0001' And CTRANSACTION_STATUS In ('01','02') 

UPDATE GST_APPROVAL_I SET CAPPROVAL_STATUS= '02' FROM GST_APPROVAL_I A (NOLOCK) WHERE A.CCOMPANY_ID= 'rcd' 
AND A.CTRANSACTION_CODE = '000000' AND A.CDEPT_CODE= 'ACC' AND A.CREFERENCE_NO= 'REF.202306.0001' AND A.CUSER_ID = 'hpc' AND A.CAPPROVAL_STATUS= '01'

EXECUTE RSP_ConvertXMLToTable 'rcd', 'hmc', '6d38f981aad64346bb6ec7253339247b'


83f50b9b08fc414498222acbabec3d7a

writeuploadstatus sudah finish


select * from GST_UPLOAD_PROCESS_STATUS
where CUSER_ID = 'hmc'

exec RSP_ConvertTableToXML

SELECT * FROM SAM_USER_COMPANY A (NOLOCK)
                              INNER JOIN SAM_USER B (NOLOCK) ON B.CUSER_ID = A.CUSER_ID
                              WHERE A.CCOMPANY_ID = 'rcd' AND A.CUSER_ID = 'hmc'

--APT00100, APT00200
---CR01 --INBOX, OUTBOX DAN DRAFT
USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_GS_GET_APPR_TRX_LIST]
		@CCOMPANY_ID = 'RCD',
		@CUSER_LOGIN_ID = 'hmc',
		@CTRANS_TYPE = 'I' --I, O, D

SELECT	'Return Value' = @return_value
GO

--APPROVER LIST
USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_GS_GET_APPROVER_LIST]
		@CCOMPANY_ID = NULL,
		@CTRANS_CODE = NULL,
		@CDEPT_CODE = NULL,
		@CREF_NO = NULL,
		@CUSER_LOGIN_ID = NULL

SELECT	'Return Value' = @return_value
GO

EXEC RSP_GS_GET_APPROVER_LIST 'RCD','000000', 'ACC','REF.202306.0001','hpc'

USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_GS_MAINTAIN_APPROVAL]
		@CCOMPANY_ID = NULL,
		@CTRANS_CODE = NULL,
		@CDEPT_CODE = NULL,
		@CREF_NO = NULL,
		@CUSER_ID = NULL,
		@CACTION = NULL

SELECT	'Return Value' = @return_value

GO


--PROCESS APPROVE
USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_GS_MAINTAIN_APPROVAL]
		@CCOMPANY_ID = N'RCD',
		@CTRANS_CODE = N'000000',
		@CDEPT_CODE = N'ACC',
		@CREF_NO = N'REF.202306.0001',
		@CUSER_ID = N'HPC',
		@CACTION = N'01'

SELECT	'Return Value' = @return_value

GO

---REJECTED PROCESS
DECLARE	@return_value int

EXEC	[RSP_GS_GET_APPR_TRX_LIST]
		@CCOMPANY_ID = 'bsi',
		@CUSER_LOGIN_ID = 'hmc',
		@CTRANS_TYPE = 'I' --I, O, D

SELECT	'Return Value' = @return_value
GO

USE [BIMASAKTI_11]
GO
DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_GS_MAINTAIN_APPROVAL]
		@CCOMPANY_ID = 'RCD',
		@CTRANS_CODE = '000010',
		@CDEPT_CODE = 'ACC',
		@CREF_NO = 'REF.202306.0004',
		@CREJECT_REASON = '',
		@CREJECT_NOTES = '',
		@CUSER_ID = 'hmc',
		@CACTION = '01'

SELECT	'Return Value' = @return_value

GO
DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_GS_GET_APPR_TRX_LIST]
		@CCOMPANY_ID = 'RCD',
		@CUSER_LOGIN_ID = 'hmc',
		@CTRANS_TYPE = 'I'--I, O, D

SELECT	'Return Value' = @return_value;





USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC [dbo].[RSP_GS_MAINTAIN_APPROVAL]
		@CCOMPANY_ID = 'RCD',
		@CTRANS_CODE = '000010',
		@CDEPT_CODE = 'ACC',
		@CREF_NO = 'REF.202306.0004',
		@CREJECT_REASON = '01',
		@CREJECT_NOTES = 'reject',
		@CUSER_ID = 'hpc',
		@CACTION = '09'

SELECT	'Return Value' = @return_value

--BACK TRANSACTION
		UPDATE GST_APPROVAL_I 
		SET CAPPROVAL_STATUS	= '01'
		FROM GST_APPROVAL_I A (NOLOCK) 
		WHERE A.CCOMPANY_ID		= 'RCD'
		AND A.CTRANS_CODE 		= '000000'
		AND A.CDEPT_CODE		= 'HRD'
		AND A.CREF_NO			= 'REF.202308.0001'
		AND A.CUSER_ID			= 'HMC'
		AND A.CAPPROVAL_STATUS	IN ('01','02')

		--BACK TRANSACTION
		UPDATE GST_APPROVAL_I 
		SET CAPPROVAL_STATUS	= '01'
		FROM GST_APPROVAL_I A (NOLOCK) 
		WHERE A.CCOMPANY_ID		= 'RCD'
		AND A.CTRANS_CODE 		= '000000'
		AND A.CDEPT_CODE		= 'HRD'
		AND A.CREF_NO			= 'REF.202308.0002'
		AND A.CUSER_ID			= 'HMC'
		AND A.CAPPROVAL_STATUS	='03'


--UPDATE GET USERNAME
EXEC RSP_GS_GET_USER_DETAIL 'RCD', 'GST00500', 'RE', ''

SELECT * FROM RFT_GET_GSB_CODE_INFO('SIAPP', 'rcd', '_GS_REJECTTRANS_REASON', '', '')

RSP_GL_GET_BUDGET_FOR_TB_LIST 'rcd','L', 'EN','2023'

RSP_GS_GET_PERIOD_YEAR_RANGE 'rcd', '',''

EXEC	@return_value = [dbo].[RSP_GS_MAINTAIN_APPROVAL]
		@CCOMPANY_ID = 'RCD',
		@CTRANS_CODE = '000010',
		@CDEPT_CODE = 'ACC',
		@CREF_NO = 'REF.202306.0004',
		@CREJECT_REASON = '',
		@CREJECT_NOTES = '',
		@CUSER_ID = 'hpc',
		@CACTION = '01'


GO
DECLARE	@return_value int

EXEC	[RSP_GS_GET_APPR_TRX_LIST]
		@CCOMPANY_ID = 'RCD',
		@CUSER_LOGIN_ID = 'hmc',
		@CTRANS_TYPE = 'I'--I, O, D
SELECT	'Return Value' = @return_value;


CREF_NO = 'HAND/ACC/202408/003/OVER'
CPROGRAM_ID = 'PMT02000|PopUpHandOver'

CREF_NO = 'LOC-U-2024080013'
CPROGRAM_ID = 'PMT01100|PMT01100_Offer'



begin transaction
select * from 	GST_APPROVAL_I
	where
	--CCOMPANY_ID = 'RCD'
	-- and 
	CREF_NO = 'LMACC-20240800004-PM'
	and CAPPROVAL_USER_ID = 'HMC'
	/*
	    loDb.R_AddCommandParameter(loCommand, "@CCOMPANY_ID", DbType.String, 20, poEntity.CCOMPANY_ID);
                loDb.R_AddCommandParameter(loCommand, "@CPROPERTY_ID", DbType.String, 20, poEntity.CPROPERTY_ID);
                loDb.R_AddCommandParameter(loCommand, "@CDEPT_CODE", DbType.String, 20, poEntity.CDEPT_CODE);
                loDb.R_AddCommandParameter(loCommand, "@CTRANS_CODE", DbType.String, 10, poEntity.CTRANS_CODE);
                loDb.R_AddCommandParameter(loCommand, "@CREF_NO", DbType.String, 30, poEntity.CREF_NO);
                loDb.R_AddCommandParameter(loCommand, "@CUSER_ID", DbType.String, 8, poEntity.CUSER_ID);
				*/

				delete from SAT_LOCKING where CUSER_ID='HPC'



RSP_GS_GET_APPR_TRX_LIST 
@CCOMPANY_ID= 'BSI', 
@CTRANS_TYPE='I', 
@CUSER_LOGIN_ID='RAM'

BEGIN TRANSACTION
IF (OBJECT_ID('tempdb..#__SP_ERR_Table') is null) BEGIN
	select SP_Name=cast('' as varchar(50)), Err_Code=cast('' as varchar(20)), Err_Detail=cast('' as nvarchar(max)) into #__SP_ERR_Table where 0=1
end else begin
	truncate table #__SP_ERR_TABLE
end

begin try
exec RSP_GS_MAINTAIN_APPROVAL
@CCOMPANY_ID = 'BSI',
@CTRANS_CODE = '802061',
@CDEPT_CODE ='00',
@CREF_NO = 'LOI-U-2024100070',
@CREJECT_REASON ='',
@CREJECT_NOTES ='',
@CUSER_ID ='RAM',
@CACTION ='01'

end try
begin catch
	select * from #__SP_ERR_TABLE --untuk tahu error code yg di raise
end catch
ROLLBACK

begin transaction 
exec RSP_GS_MAINTAIN_APPROVAL
@CCOMPANY_ID = 'BSI',
@CTRANS_CODE = '802032',
@CDEPT_CODE ='00',
@CREF_NO = 'AGRC-20250100001-AC',
@CREJECT_REASON ='',
@CREJECT_NOTES ='',
@CUSER_ID ='RAM',
@CACTION ='01'

rollback

EXEC	[RSP_GS_GET_APPR_TRX_LIST]
		@CCOMPANY_ID = 'bsi',
		@CUSER_LOGIN_ID = 'hmc',
		@CTRANS_TYPE = 'I'--I, O, D


select CPROGRAM_ID, * from GST_APPROVAL

select * from GST_APPROVAL_I
WHERE CTRANS_CODE  =  '505010'
and CAPPROVAL_USER_ID ='hmc'

begin transaction 
select * from GSM_TRANSACTION_CODE 
WHERE CTRANS_CODE  = '505010'

UPDATE GSM_TRANSACTION_CODE SET CPROGRAM_ID ='ICT00900|ICT00900Detail'			--LOO-E-02-2025040001
WHERE CTRANS_CODE  = '505010'

select CPROGRAM_ID, * from GSM_TRANSACTION_CODE 
WHERE CPROGRAM_ID  <>''
and CPROGRAM_ID = 'PMT01700'
rollback
commit
 