PMT00900

exec RSP_IC_GET_ADJUSTMENT_LIST 
@CCOMPANY_ID	='rcd',
@CPROPERTY_ID	='ashmd',
@CUSER_ID		='hmc'

CTRANS_STATUS	
CTRANS_STATUS_DESCR
CREF_NO	
CREF_DATE	
CDEPT_NAME	
CPRODUCT_NAME	
CADJUST_METHOD	
NADJUST_AMOUNT	
CALLOC_NAME	
CCREATE_BY	
DCREATE_DATE	
CUPDATE_BY	
DUPDATE_DATE

CDEPT_CODE	
CCOMPANY_ID	
CPROPERTY_ID	
CPRODUCT_ID	
CADJUST_METHOD_DESCR	
CALLOC_ID	

EXEC RSP_IC_GET_ADJUSTMENT_DETAIL 
@CCOMPANY_ID	='',
@CPROPERTY_ID	='',
@CREF_NO		='',
@CUSER_ID		=''

CTRANS_STATUS	
CTRANS_STATUS_DESCR	
CCOMPANY_ID	
CPROPERTY_ID	
CDEPT_CODE	
CDEPT_NAME	
CREF_NO	CREF_DATE	
CPRODUCT_ID	
CPRODUCT_NAME	
CADJUST_METHOD	
CADJUST_METHOD_DESCR	
NADJUST_AMOUNT	
CALLOC_ID	
CALLOC_NAME	
DCREATE_DATE	
CUPDATE_BY	
DUPDATE_DATE

RSP_IC_GET_ADJUSTMENT_DETAIL 
@CCOMPANY_ID
@CPROPERTY_ID
@CREF_NO
@CUSER_ID

RSP_IC_CHANGE_STATUS_ADJUSTMENT



RSP_IC_GET_ADJUSTMENT_LIST
RSP_IC_MAINTAIN_ADJUSTMENT
RSP_IC_GET_ADJUSTMENT_DETAIL

begin transaction

RSP_HD_SCHEDULER_ACTION

rollback



BEGIN TRANSACTION
IF (OBJECT_ID('tempdb..#__SP_ERR_Table') is null) BEGIN
	select SP_Name=cast('' as varchar(50)), Err_Code=cast('' as varchar(20)), Err_Detail=cast('' as nvarchar(max)) into #__SP_ERR_Table where 0=1
end else begin
	truncate table #__SP_ERR_TABLE
end

begin try

exec RSP_IC_MAINTAIN_ADJUSTMENT
@CCOMPANY_ID		='BSI',
@CPROPERTY_ID		='ASHMD',
@CDEPT_CODE			='03',
@CTRANS_CODE		='505010',
@CREF_NO			='ADJ-0000000002',
@CREF_DATE			='20250415',
@CADJUST_METHOD		='V',
@CPRODUCT_ID		='ID02',
@NADJUST_AMOUNT		='11111',
@CNOTES				='Descripti0n off number 1',
@CALLOC_ID			='ID06',
@CACTION			='EDIT',
@CUSER_ID			='hmc'
end try
begin catch
	select * from #__SP_ERR_TABLE --untuk tahu error code yg di raise
end catch

ROLLBACK


rollback

begin transaction
use bimasakti_11
exec RSP_IC_MAINTAIN_ADJUSTMENT
@CCOMPANY_ID		='BSI',
@CPROPERTY_ID		='ASHMD',
@CDEPT_CODE			='03',
@CTRANS_CODE		='505010',
@CREF_NO			='ADJ-0000000003',
@CREF_DATE			='20250415',
@CADJUST_METHOD		='V',
@CPRODUCT_ID		='ID02',
@NADJUST_AMOUNT		='11111',
@CNOTES				='Descripti0n off number 1 with edit',
@CALLOC_ID			='ID06',
@CACTION			='EDIT',
@CUSER_ID			='hmc'
CCURRENCY_CODE
NLBASE_RATE
NLCURRENCY_RATE
NBBASE_RATE
NBCURRENCY_RATE
NTRANS_AMOUNT
exec RSP_GS_GET_TRANS_CODE_INFO 'bsi', '505010'

exec RSP_IC_GET_ADJUSTMENT_LIST 
@CCOMPANY_ID	='bsi',
@CPROPERTY_ID	='ashmd',
@CUSER_ID		='hmc'
exec RSP_IC_GET_ADJUSTMENT_DETAIL
@CCOMPANY_ID	='bsi',
@CPROPERTY_ID	='ashmd',
@CREF_NO		='ADJ-0000000002',
@CUSER_ID		='hmc'

use BIMASAKTI_11
exec RSP_IC_CHANGE_STATUS_ADJUSTMENT
@CCOMPANY_ID		='',
@CPROPERTY_ID		='',
@CDEPT_CODE			='',
@CTO_ALLOC_ID		='',
@CTRANS_CODE		='',
@CREF_NO			='',
@CSTATUS			='',
@CUSER_ID			=''

exec RSP_IC_GET_ADJUSTMENT_LIST 
@CCOMPANY_ID	='bsi',
@CPROPERTY_ID	='ashmd',
@CUSER_ID		='hmc'

exec RSP_IC_GET_ADJUSTMENT_LIST
exec RSP_IC_MAINTAIN_ADJUSTMENT

exec RSP_IC_CHANGE_STATUS_ADJUSTMENT

rollback



CTRANS_CODE
CTRANS_CODE_DESCR
CCREATE_BY
CNOTES

RSP_GS_GET_PROPERTY_LIST
@CCOMPANY_ID	='bsi',
@CUSER_ID		='hmc'

RSP_GS_GET_CURRENCY_LIST
@CCOMPANY_ID	='bsi',
@CUSER_ID		='hmc'
CCURRENCY_CODE	CCURRENCY_SYMBOL	CCURRENCY_NAME
AUD		Australian Dollar


RSP_GS_GET_COMPANY_INFO 'bsi'

--TABLE NAME
ICT_TRANS_HD

begin transaction 

exec RSP_IC_CHANGE_STATUS_ADJUSTMENT
@CCOMPANY_ID		='bsi',
@CPROPERTY_ID		='ashmd',
@CDEPT_CODE			='03',
@CTO_ALLOC_ID		='ID06',
@CTRANS_CODE		='505010',
@CREF_NO			='ADJ-0000000005',
@CSTATUS			='10',
@CUSER_ID			='hmc'

exec RSP_IC_GET_ADJUSTMENT_DETAIL
@CCOMPANY_ID	='bsi',
@CPROPERTY_ID	='ashmd',
@CREF_NO		='ADJ-0000000005',
@CUSER_ID		='hmc'

rollback

ICT_TRANS_HD

RSP_IC_MAINTAIN_ADJUSTMENT