RSP_LM_GET_INVOICE_GROUP_LIST 'RCD', 'ASHMD', 'HMC'
RSP_LM_GET_INVOICE_GROUP 'rcd', 'ashmd', 'INVHMC', 'hmc'


--EXEC RSP_LM_GET_INVOICE_GROUP @CCOMPANY_ID, @CPROPERTY_ID, @CINVGRP_CODE, @CUSER_LOGIN_ID

RSP_LM_GET_INVOICE_GROUP 'RCD', 'ASHMD', 'INVFMC01', 'hmc'


--ADD EDIT
RSP_LM_GET_INVGRP_DEPT_LIST 'rcd', 'ashmd', 'INVFMC01', 'hmc'

RSP_LM_GET_INVGRP_DEPT_DETAIL 'rcd', 'ashmd', 'INVFMC01', 'fin','hmc'

select * from LMM_INVGRP

RSP_GS_GET_OTHER_CHARGES_LIST 'rcd', 'ashmd','A', 'hmc'

RSP_GS_GET_DEPT_LOOKUP_LIST'rcd', 'hmc'
RSP_GS_GET_CASH_BANK_LIST'rcd','','B', 'hmc' -- CCB_CODE = 01
RSP_GS_GET_CASH_BANK_LIST'rcd','B','', 'hmc' -- CCB_CODE = 01
RSP_GS_GET_CASH_BANK_NUMBER_LIST 'rcd','01','hmc'

SELECT CSTATUS, * FROM STORAGE_DATA_TABLE


RSP_LM_GET_INVGRP_DEPT_LIST 'rcd', 'ashmd', 'INVFMC01', 'hmc'

--PENALTY
RSP_LM_GET_INVOICE_GROUP 'rcd', 'ashmd', 'INVFMC01','hmc'

--CHARGES
RSP_LM_GET_INVGRP_CHARGES_LIST 'rcd','ashmd', 'INVFMC01','hmc'
RSP_LM_GET_CHARGES_LIST 'rcd', 'jbmpc', 'hmc'

RSP_GS_GET_STORAGE_TYPE 'rcd', 'hmc'

--LOOOKUP 
RSP_GS_GET_CASH_BANK_NUMBER_LIST 'rcd', 'B', 'hmc'


select * from LMM_INVGRP

--CEK DATA
SELECT CSTORAGE_ID FROM LMM_INVGRP (NOLOCK) 
                    WHERE CCOMPANY_ID ='rcd'
                    AND CPROPERTY_ID = 'ashmd'
                    AND CINVGRP_CODE = 'HMC'

SELECT * FROM STORAGE_DATA_TABLE