--Password: CD-r5fdbsvr1#
delete from SAT_LOCKING where CUSER_ID='aoc'

delete from SAT_LOCKING where CUSER_ID='hmc'

EXEC RSP_LM_GET_UNIT_TYPE_LIST @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUNIT_TYPE_CATEGORY_ID , @CUSER_LOGIN_ID

EXEC RSP_GS_GET_UNIT_TYPE_BILLING_RULE_LIST @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUNIT_TYPE_ID, @LACTIVE_ONLY, @CUSER_LOGIN_ID

EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'ASHMD','','hmc'
EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'JBMPC','','hmc'
EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'LMPNG','','hmc'


EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_LIST 'RCD', 'JBMPC','1BRoom', 0, 'hmc'

--RSP_GS_GET_UNIT_TYPE_BILLING_RULE_DT 
EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUNIT_TYPE_ID, @CBIILING_RULE_CODE, @CUSER_LOGIN_ID

EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT 'RCD', 'JBMPC','1BRoom', 'Rules001', 'hmc'



exec RSP_GS_GET_PROPERTY_LIST 'rcd', 'admin'

SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'Login Company Id', '_PERIOD_MODE', '', 'EN')
SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'RCD', '_PERIOD_MODE', '', 'EN')


EXEC RSP_GS_GET_SALES_TAX_LIST 'RCD', 'hmc' 




EXEC RSP_LM_GET_CHARGES_TYPE_LIST 'hmc', 'ASHMD', '','admin'
exec RSP_GS_GET_PROPERTY_LIST 'rcd', 'admin'
LINSTALLMENT
0
CDP_CHARGE_ID	CDP_CHARGE_NAME CINSTALLMENT_CHARGE_ID

CINSTALLMENT_CHARGE_ID	CINSTALLMENT_CHARGE_NAME
EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT 'RCD', 'JBMPC','1BRoom', 'RULes03', 'hmc'

EXEC RSP_LM_ACTIVE_INACTIVE_UNIT_TYPE_BILLING_RULE 
Login Company Id
, "Selected Property Id"
, "Unit Type Id"
, "Billing Rule" Code
, Flag Active [True] / [False]
, Login User Id

EXEC RSP_LM_ACTIVE_INACTIVE_UNIT_TYPE_BILLING_RULE 'rcd','JBMPC','1BRoom', 'RULES03', 1, 'hmc'
EXEC RSP_LM_GET_CHARGES_TYPE_LIST 'RCD', 'JBMPC', '07', 'hmc'

EXEC RSP_LM_GET_UNIT_TYPE_LIST @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUSER_LOGIN_ID

EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'ASHMD','','hmc'
EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'JBMPC','','hmc'
EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'LMPNG','','hmc'

exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'jbmpc', '07','hmc'
exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'jbmpc', '','hmc'
--RSP_LM_GET_CHARGES_TYPE_LIST

SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'rcd', '_PERIOD_MODE', '', 'en')

exec RSP_LM_GET_UNIT_TYPE_BILLING_RULE_LIST 'rcd','ashmd', '1BRoom', '0','hmc'

exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'jbmpc', '', 'hmc'
exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'Ashmd', '', 'hmc'
exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'Lmpng', '', 'hmc'

exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'jbmpc', '07', 'hmc'
exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'Ashmd', '07', 'hmc'
exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'Lmpng', '07', 'hmc'

exec RSP_LM_GET_UNIT_TYPE_BILLING_RULE_LIST 'rcd','JBMPC', '1BRoom', '1','hmc'

exec RSP_LM_GET_UNIT_TYPE_BILLING_RULE_LIST 'rcd','JBMPC', '1BRoom', '0','hmc'
EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT 'RCD', 'JBMPC','1BRoom', 'Rules0020', 'hmc'
EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT 'RCD', 'ASHMD','1BRoom', '0', 'hmc'

USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_LM_MAINTAIN_UNIT_TYPE_BILLING_RULE]
		@CCOMPANY_ID = N'RCD',
		@CPROPERTY_ID = N'ASHMD',
		@CUNIT_TYPE_ID = N'1BRoom',
		@CBILLING_RULE_CODE = N'NewOneModify',
		@CBILLING_RULE_NAME = N'HarcoMas',
		@LBOOKING_FEE = 1,
		@CBOOKING_FEE_CHARGES_ID = N'G002',
		@LWITH_DP = 1,
		@IDP_PERCENTAGE = 22,
		@IDP_INTERVAL = 22,
		@CDP_PERIOD_MODE = N'03',
		@CDP_CHARGE_ID = N'DP',
		@LINSTALLMENT = 1,
		@IINSTALLMENT_PERCENTAGE = 1,
		@IINSTALLMENT_INTERVAL = 12,
		@CINSTALLMENT_PERIOD_MODE = N'03',
		@CINSTALLMENT_CHARGE_ID = N'GLK01',
		@LBANK_CREDIT = 0,
		@IBANK_CREDIT_PERCENTAGE = 0,
		@IBANK_CREDIT_INTERVAL = 0,
		@LACTIVE = 1,
		@CACTION = N'EDIT',
		@CUSER_ID = N'HMC'

SELECT	'Return Value' = @return_value
GO

CINSTALLMENT_PERIOD_MODE_DESCR
Monthly
Yearly


SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'RCD', '_PERIOD_MODE', '', 'EN')


--CR 02
[RSP_GS_GET_UNIT_TYPE_CTG_LIST]
		@CCOMPANY_ID = N'rcd',
		@CPROPERTY_ID = N'ashmd',
		@CUSER_ID = N'hmc'



[RSP_LM_GET_STRATA_BILLING_RULE_LIST]
		@CCOMPANY_ID = N'rcd',
		@CUNIT_TYPE_CTG_ID = N'STUDIO',
		@LACTIVE_ONLY = 0,
		@CUSER_ID = N'hmc'

RSP_PM_GET_STRATA_BILLING_RULE_LIST 'rcd','ashmd', '1Room',0,'hmc'

RSP_LM_GET_STRATA_BILLING_RULE_DT 'rcd','ashmd', 'STUDIO','Code 1','hmc'

USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_LM_MAINTAIN_STRATA_BILLING_RULE]
		@CCOMPANY_ID = N'rcd',
		@CPROPERTY_ID = N'jbmpc',
		@CUNIT_TYPE_CTG_ID = N'1 Bed test',
		@CBILLING_RULE_CODE = N'Rule Code 01',
		@CBILLING_RULE_NAME = N'Rule Name',
		@LBOOKING_FEE = 0,
		@NMIN_BOOKING_FEE = 0,
		@LBOOKING_FEE_OVERWRITE = 0,
		@CBOOKING_FEE_CHARGES_ID = '',
		@LWITH_DP = 1,
		@IDP_PERCENTAGE = 0,
		@IDP_INTERVAL = 0,
		@CDP_PERIOD_MODE = N'01',
		@CDP_CHARGE_ID = N'DP',
		@LINSTALLMENT = 0,
		@IINSTALLMENT_PERCENTAGE = 0,
		@IINSTALLMENT_INTERVAL = 0,
		@CINSTALLMENT_PERIOD_MODE = '',
		@CINSTALLMENT_CHARGE_ID = '',
		@LBANK_CREDIT = 0,
		@IBANK_CREDIT_PERCENTAGE = 12,
		@IBANK_CREDIT_INTERVAL = 12,
		@LACTIVE = 1,
		@CACTION = N'ADD',
		@CUSER_ID = N'hmc'

SELECT	'Return Value' = @return_value

GO

RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'ashmd', '07', 'hmc'
SELECT * FROM STORAGE_DATA_TABLE
delete from SAT_LOCKING where CUSER_ID='hmc'
RSP_LM_GET_INVOICE_GROUP 'rcd', 'ashmd', 'invfmc01', 'hmc'


---CR03
RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'jbmpc', '02,06,07', 'hmc'



select * From SAM_USER_LOCKING

--rcd|ASHMD|1ROOM|001
LMM_UNIT_TYPE_BILLING_RULE
 select *from LMM_BILLING_RULe
LMM_BILLING_RULE

select * from PMM_BILLING_RULE

RSP_PM_ACTIVE_INACTIVE_UNIT_TYPE_BILLING_RULE

RSP_LM_ACTIVE_INACTIVE_UNIT_TYPE_BILLING_RULE



   exec  RSP_PM_GET_STRATA_BILLING_RULE_LIST
    @CCOMPANY_ID= 'RCD', 
	@CPROPERTY_ID= 'ASHMD',
	@CUNIT_TYPE_CTG_ID= '1ROOM', 
	@CUSER_ID= 'HMC', 
	@LACTIVE_ONLY= false

 begin transaction
 exec RSP_PM_MAINTAIN_STRATA_BILLING_RULE
	   @CCOMPANY_ID= 'RCD', 
	   @CPROPERTY_ID= 'ASHMD', 
	   @CBILLING_RULE_CODE= '005Billing',
	   @CBILLING_RULE_NAME= '005Billing', 
	   @CBOOKING_FEE_CHARGES_ID= 'test0003', 
	   @CDP_CHARGE_ID= 'DPYT01', 
	   @CDP_PERIOD_MODE= '02', 
	   @CINSTALLMENT_CHARGE_ID= '', 
	   @CINSTALLMENT_PERIOD_MODE= '',
	   @CUNIT_TYPE_CTG_ID= '1ROOM', 
	   @IBANK_CREDIT_INTERVAL= 0, 
	   @IBANK_CREDIT_PERCENTAGE= 0,
	   @IDP_INTERVAL= 12, 
	   @IDP_PERCENTAGE= 100, 
	   @IINSTALLMENT_INTERVAL= 0, 
	   @IINSTALLMENT_PERCENTAGE= 0, 
	   @LACTIVE= true, 
	   @LBANK_CREDIT= false, 
	   @LBOOKING_FEE= true, 
	   @LBOOKING_FEE_OVERWRITE= true, 
	   @LINSTALLMENT= false, 
	   @LWITH_DP= true, 
	   @NMIN_BOOKING_FEE= 1000,
	   @CACTION= 'ADD', 
	   @CUSER_ID= 'HMC'


	   select * from PMM_BILLING_RULE

	      exec  RSP_PM_GET_STRATA_BILLING_RULE_LIST
    @CCOMPANY_ID= 'RCD', 
	@CPROPERTY_ID= 'ASHMD',
	@CUNIT_TYPE_CTG_ID= '1ROOM', 
	@CUSER_ID= 'HMC', 
	@LACTIVE_ONLY= false

	   EXEC RSP_PM_GET_BILLING_RULE_LIST 'BSI', 'ASHMD', '02', 'BR', false, 'HMC'
	   rollback

	   EXEC [dbo].[RSP_PM_LOOKUP_CANCEL_CUST_RECEIPT]
	 'BSI'--@CCOMPANY_ID		
	,'ASHMD'--@CPROPERTY_ID		
	,'RAM'--@CUSER_ID			
	,'202412'--@CPERIOD			
	,'TNT48'		
	,''	
	,'EN'--@CLANGUAGE_ID

	begin transaction

	exec RSP_PM_GET_STRATA_BILLING_RULE_LIST
	@CCOMPANY_ID= 'RCD', 
	@CPROPERTY_ID= 'ASHMD', 
	@CUNIT_TYPE_CTG_ID= '1ROOM', 
	@CUSER_ID= 'HMC', 
	@LACTIVE_ONLY= false

	exec RSP_PM_MAINTAIN_STRATA_BILLING_RULE
	@CBILLING_RULE_CODE= 'bIlling01', 
	@CBILLING_RULE_NAME= 'Billing01', 
	@CBOOKING_FEE_CHARGES_ID= 'wht02', 
	@CCOMPANY_ID= 'RCD', 
	@CDP_CHARGE_ID= '02', 
	@CDP_PERIOD_MODE= '02', 
	@CINSTALLMENT_CHARGE_ID= '02', 
	@CINSTALLMENT_PERIOD_MODE= '03', 
	@CPROPERTY_ID= 'ASHMD', 
	@CUNIT_TYPE_CTG_ID= '1ROOM', 
	@CUSER_ID= 'HMC',
	@IBANK_CREDIT_INTERVAL= 0, 
	@IBANK_CREDIT_PERCENTAGE= 0, 
	@IDP_INTERVAL= 0, @IDP_PERCENTAGE= 10, 
	@IINSTALLMENT_INTERVAL= 12, 
	@IINSTALLMENT_PERCENTAGE= 90, 
	@LACTIVE= true, 
	@LBANK_CREDIT= false, 
	@LBOOKING_FEE= true, 
	@LBOOKING_FEE_OVERWRITE= true, 
	@LINSTALLMENT= true, 
	@LWITH_DP= true, 
	@NMIN_BOOKING_FEE= 0,
	@CACTION= 'DELETE'



	rollback


	delete from SAT_LOCKING where CUSER_ID='hmc'
	select * from SAT_LOCKING