SELECT * FROM GSB_CODE_DT WHERE CCLASS_ID IN ('_BS_UNIT_CHARGES_TYPE', '_BS_UTILITY_CHARGES_TYPE')

RSP_PM_PMA00300
@CCOMPANY_ID = 'BSI',
@CPROPERTY_ID ='ASHMD', --STATIC
@CPERIOD ='202501', --YYMM
@CUSER_ID ='System'

RSP_PM_SAVE_BILLING_STATEMENT
@CCOMPANY_ID
@CPROPERTY_ID
@CTENANT_ID
@CLOI_AGRMT_REC_ID
@CREF_PRD
@CREF_DATE
@CDUE_DATE
@CSTORAGE_ID
@CUSER_ID

RSP_PM_GET_TENANT_VA_LIST
@CCOMPANY_ID = 'RCD',
@CPROPERTY_ID ='ASHMD',
@CTENANT_ID ='TNT09',
@CLANGUAGE_ID =''
/*
CBANK_CODE
CBANK_NAME
CVA_CODE
*/

SELECT dbo.RFN_GET_COMPANY_LOGO('rcd') as CLOGO

select CCOMPANY_ID,CPROPERTY_ID,CREC_ID,CSTORAGE_ID,CFILE_NAME,CCREATE_BY from TXT_INVOICE_TAX_FILE (nolock) where CSTATUS = '00'

select * from SAM_COMPANIES where CCOMPANY_ID ='{poParameter.CCOMPANY_ID}'


select * from PMT_BILLING_STATEMENT 

select * from SAM_COMPANIES where CCOMPANY_ID ='rcd' .

RS

select * from PMT_TRANS_HD

begin transaction

delete from PMT_BILLING_STATEMENT where CTENANT_ID='TNT72'


select * from STORAGE_DATA_TABLE order by DUPDATE_DATE desc
rollback


begin transaction
exec RSP_PM_SAVE_BILLING_STATEMENT
@CCOMPANY_ID = 'rcd',
@CPROPERTY_ID = 'ashmd',
@CTENANT_ID = 'LK002',
@CLOI_AGRMT_REC_ID = 'BD77B8D1-9456-4327-9C17-B6AD1001A5A6',
@CREF_PRD = '202501',
@CREF_DATE ='20250122',
@CDUE_DATE ='20250122',
@CSTORAGE_ID = '60209ec339e64862a9134d9db4ba9dd1',
@CUSER_ID ='HMC'

exec RSP_PM_GET_AGREEMENT_DETAIL
@CCOMPANY_ID = 'rcd',
@CPROPERTY_ID ='ashmd',
@CDEPT_CODE ='FIN',
@CTRANS_CODE = '802011',
@CREF_NO = 'LOOFIN-20250100004-',
@CUSER_ID =  'hmc'
rollback

begin transaction

select * from PMT_BILLING_STATEMENT where CTENANT_ID='TNT72' and CREF_PRD='202502'

delete from PMT_BILLING_STATEMENT where CTENANT_ID='TNT72'  and CREF_PRD='202502'
rollback


select * from STORAGE_DATA_TABLE order by DUPDATE_DATE desc 

exec RSP_PM_PMA00300
@CCOMPANY_ID = 'bsi',
@CPROPERTY_ID ='ASHMD', --STATIC
@CPERIOD ='202501', --YYMM
@CUSER_ID ='System'
--VA
RSP_PM_GET_TENANT_VA_LIST
@CCOMPANY_ID = 'bsi',
@CPROPERTY_ID ='ASHMD',
@CTENANT_ID ='TNT79',
@CLANGUAGE_ID ='en'

--DETAIL
EXEC RSP_PM_PMA00300 'BSI', 'ASHMD', '202501', 'D','UN' --UNIT
EXEC RSP_PM_PMA00300 'BSI', 'ASHMD', '202501', 'D','UT' --Utility

NMETER_START	
NMETER_END	

NBLOCK1_USAGE = NMETER_USAGE  
NBLOCK1_START = NMETER_START
NBLOCK1_END  = NMETER_END
NBLOCK1_CHARGE = NMETER_CHARGE
				= Biaya operasional NMAINTENANCE_FEE
NKVA ganti jadi NCAPACITY
CTRANS_DESC

use BIMASAKTI_11
begin transaction

exec RSP_PM_PMA00300
@CCOMPANY_ID  ='bsi',
@CPROPERTY_ID = 'ashmd',
@CPERIOD = '202504',
@CUSER_ID = 'hmc'
rollback

@CREPORT_TYPE
@CSERVICE_TYPE