//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMM00100FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMM00100FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMM00100FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMM00100FrontResources.PMM00100FrontResources_msgrsc", typeof(PMM00100FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string _btn_add {
            get {
                return ResourceManager.GetString("_btn_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _btn_cancel {
            get {
                return ResourceManager.GetString("_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string _btn_edit {
            get {
                return ResourceManager.GetString("_btn_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string _btn_save {
            get {
                return ResourceManager.GetString("_btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Building.
        /// </summary>
        internal static string _chk_allbuilding {
            get {
                return ResourceManager.GetString("_chk_allbuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiller.
        /// </summary>
        internal static string _chk_chiller {
            get {
                return ResourceManager.GetString("_chk_chiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute PDF.
        /// </summary>
        internal static string _chk_distributepdf {
            get {
                return ResourceManager.GetString("_chk_distributepdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        internal static string _chk_electricity {
            get {
                return ResourceManager.GetString("_chk_electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Off Date.
        /// </summary>
        internal static string _chk_electricity_cut_off_date {
            get {
                return ResourceManager.GetString("_chk_electricity_cut_off_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of the Month.
        /// </summary>
        internal static string _chk_end_of_month {
            get {
                return ResourceManager.GetString("_chk_end_of_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        internal static string _chk_gas {
            get {
                return ResourceManager.GetString("_chk_gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Off Date.
        /// </summary>
        internal static string _chk_gas_cut_off_date {
            get {
                return ResourceManager.GetString("_chk_gas_cut_off_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Invoice Process.
        /// </summary>
        internal static string _chk_generate_invoice_process {
            get {
                return ResourceManager.GetString("_chk_generate_invoice_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Link.
        /// </summary>
        internal static string _chk_gl_link {
            get {
                return ResourceManager.GetString("_chk_gl_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include images in PDF.
        /// </summary>
        internal static string _chk_includeimagesinpdf {
            get {
                return ResourceManager.GetString("_chk_includeimagesinpdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Penalty.
        /// </summary>
        internal static string _chk_includepenalty {
            get {
                return ResourceManager.GetString("_chk_includepenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Priority Apps.
        /// </summary>
        internal static string _chk_usepriorityapp {
            get {
                return ResourceManager.GetString("_chk_usepriorityapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string _chk_water {
            get {
                return ResourceManager.GetString("_chk_water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Off Date.
        /// </summary>
        internal static string _chk_water_cut_off_date {
            get {
                return ResourceManager.GetString("_chk_water_cut_off_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string _column_building {
            get {
                return ResourceManager.GetString("_column_building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _column_property {
            get {
                return ResourceManager.GetString("_column_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Statement.
        /// </summary>
        internal static string _grp_billingstatement {
            get {
                return ResourceManager.GetString("_grp_billingstatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handover.
        /// </summary>
        internal static string _grp_handover {
            get {
                return ResourceManager.GetString("_grp_handover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Payment.
        /// </summary>
        internal static string _grp_onlinepayment {
            get {
                return ResourceManager.GetString("_grp_onlinepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Type Parameter.
        /// </summary>
        internal static string _grp_rate_type_parameter {
            get {
                return ResourceManager.GetString("_grp_rate_type_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Parameter.
        /// </summary>
        internal static string _grp_receipt_parameter {
            get {
                return ResourceManager.GetString("_grp_receipt_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        internal static string _grp_utility {
            get {
                return ResourceManager.GetString("_grp_utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attempt(s) within.
        /// </summary>
        internal static string _lbl_attempt {
            get {
                return ResourceManager.GetString("_lbl_attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges and Tax Info.
        /// </summary>
        internal static string _lbl_chargesandtaxinfo {
            get {
                return ResourceManager.GetString("_lbl_chargesandtaxinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges ID*.
        /// </summary>
        internal static string _lbl_chargesid {
            get {
                return ResourceManager.GetString("_lbl_chargesid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _lbl_createdby {
            get {
                return ResourceManager.GetString("_lbl_createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency*.
        /// </summary>
        internal static string _lbl_currency {
            get {
                return ResourceManager.GetString("_lbl_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate Type.
        /// </summary>
        internal static string _lbl_currency_rate_type {
            get {
                return ResourceManager.GetString("_lbl_currency_rate_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Period.
        /// </summary>
        internal static string _lbl_current_period {
            get {
                return ResourceManager.GetString("_lbl_current_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        internal static string _lbl_days {
            get {
                return ResourceManager.GetString("_lbl_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Handover.
        /// </summary>
        internal static string _lbl_donehandover {
            get {
                return ResourceManager.GetString("_lbl_donehandover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Start Period.
        /// </summary>
        internal static string _lbl_electricity_start_period {
            get {
                return ResourceManager.GetString("_lbl_electricity_start_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of the Month.
        /// </summary>
        internal static string _lbl_endofthemonth {
            get {
                return ResourceManager.GetString("_lbl_endofthemonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Start Period.
        /// </summary>
        internal static string _lbl_gas_start_period {
            get {
                return ResourceManager.GetString("_lbl_gas_start_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Mode.
        /// </summary>
        internal static string _lbl_invoice_mode {
            get {
                return ResourceManager.GetString("_lbl_invoice_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Receipt.
        /// </summary>
        internal static string _lbl_less_receipt {
            get {
                return ResourceManager.GetString("_lbl_less_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance Amount.
        /// </summary>
        internal static string _lbl_less_tolerance_amount {
            get {
                return ResourceManager.GetString("_lbl_less_tolerance_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Reschedule*.
        /// </summary>
        internal static string _lbl_maxres {
            get {
                return ResourceManager.GetString("_lbl_maxres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Receipt.
        /// </summary>
        internal static string _lbl_over_receipt {
            get {
                return ResourceManager.GetString("_lbl_over_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance Amount.
        /// </summary>
        internal static string _lbl_over_tolerance_amount {
            get {
                return ResourceManager.GetString("_lbl_over_tolerance_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _lbl_property {
            get {
                return ResourceManager.GetString("_lbl_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLA Call Type (Defect)*.
        /// </summary>
        internal static string _lbl_slacallype {
            get {
                return ResourceManager.GetString("_lbl_slacallype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Period.
        /// </summary>
        internal static string _lbl_soft_period {
            get {
                return ResourceManager.GetString("_lbl_soft_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Invoice Period.
        /// </summary>
        internal static string _lbl_start_invoice_period {
            get {
                return ResourceManager.GetString("_lbl_start_invoice_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date*.
        /// </summary>
        internal static string _lbl_startdate {
            get {
                return ResourceManager.GetString("_lbl_startdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Date*.
        /// </summary>
        internal static string _lbl_statementdate {
            get {
                return ResourceManager.GetString("_lbl_statementdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit By*.
        /// </summary>
        internal static string _lbl_submitby {
            get {
                return ResourceManager.GetString("_lbl_submitby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate Type.
        /// </summary>
        internal static string _lbl_tax_rate_type {
            get {
                return ResourceManager.GetString("_lbl_tax_rate_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID*.
        /// </summary>
        internal static string _lbl_taxid {
            get {
                return ResourceManager.GetString("_lbl_taxid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of Payment.
        /// </summary>
        internal static string _lbl_termofpayment {
            get {
                return ResourceManager.GetString("_lbl_termofpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _lbl_updatedby {
            get {
                return ResourceManager.GetString("_lbl_updatedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Start Period.
        /// </summary>
        internal static string _lbl_water_start_period {
            get {
                return ResourceManager.GetString("_lbl_water_start_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withholding Tax Mode.
        /// </summary>
        internal static string _lbl_withholding_tax_mode {
            get {
                return ResourceManager.GetString("_lbl_withholding_tax_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Invoice.
        /// </summary>
        internal static string _opt_on_invoice {
            get {
                return ResourceManager.GetString("_opt_on_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Receipt.
        /// </summary>
        internal static string _opt_on_receipt {
            get {
                return ResourceManager.GetString("_opt_on_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM System Parameter.
        /// </summary>
        internal static string _pageTitlePMM00100 {
            get {
                return ResourceManager.GetString("_pageTitlePMM00100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string _tab_billing {
            get {
                return ResourceManager.GetString("_tab_billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HO Utilities Building Mapping.
        /// </summary>
        internal static string _tab_houtillbuildingmapping {
            get {
                return ResourceManager.GetString("_tab_houtillbuildingmapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select property !.
        /// </summary>
        internal static string _val1 {
            get {
                return ResourceManager.GetString("_val1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Gas cut off date !.
        /// </summary>
        internal static string _val10 {
            get {
                return ResourceManager.GetString("_val10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Electricity Charges ID!.
        /// </summary>
        internal static string _val11 {
            get {
                return ResourceManager.GetString("_val11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Electricity Tax ID!.
        /// </summary>
        internal static string _val12 {
            get {
                return ResourceManager.GetString("_val12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Gas Charges ID!.
        /// </summary>
        internal static string _val13 {
            get {
                return ResourceManager.GetString("_val13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Gas Tax ID!.
        /// </summary>
        internal static string _val14 {
            get {
                return ResourceManager.GetString("_val14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Water Charges ID!.
        /// </summary>
        internal static string _val15 {
            get {
                return ResourceManager.GetString("_val15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Maximum Reschedule Days!.
        /// </summary>
        internal static string _val16 {
            get {
                return ResourceManager.GetString("_val16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Maximum Reschedule Attempts!.
        /// </summary>
        internal static string _val17 {
            get {
                return ResourceManager.GetString("_val17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose SLA Call Type (Defect)!.
        /// </summary>
        internal static string _val18 {
            get {
                return ResourceManager.GetString("_val18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Start Date!.
        /// </summary>
        internal static string _val19 {
            get {
                return ResourceManager.GetString("_val19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select soft period !.
        /// </summary>
        internal static string _val2 {
            get {
                return ResourceManager.GetString("_val2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose Submit By!.
        /// </summary>
        internal static string _val20 {
            get {
                return ResourceManager.GetString("_val20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Currency!.
        /// </summary>
        internal static string _val21 {
            get {
                return ResourceManager.GetString("_val21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Statement Date!.
        /// </summary>
        internal static string _val22 {
            get {
                return ResourceManager.GetString("_val22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Term of Payment!.
        /// </summary>
        internal static string _val23 {
            get {
                return ResourceManager.GetString("_val23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Chiller Charges ID!.
        /// </summary>
        internal static string _val24 {
            get {
                return ResourceManager.GetString("_val24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Chiller Tax ID!.
        /// </summary>
        internal static string _val25 {
            get {
                return ResourceManager.GetString("_val25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Water Tax ID!.
        /// </summary>
        internal static string _val26 {
            get {
                return ResourceManager.GetString("_val26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select current period !.
        /// </summary>
        internal static string _val3 {
            get {
                return ResourceManager.GetString("_val3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Start invoice period !.
        /// </summary>
        internal static string _val4 {
            get {
                return ResourceManager.GetString("_val4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Electricity start period !.
        /// </summary>
        internal static string _val5 {
            get {
                return ResourceManager.GetString("_val5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Water start period !.
        /// </summary>
        internal static string _val6 {
            get {
                return ResourceManager.GetString("_val6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Gas start period !.
        /// </summary>
        internal static string _val7 {
            get {
                return ResourceManager.GetString("_val7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Electricity cut off date !.
        /// </summary>
        internal static string _val8 {
            get {
                return ResourceManager.GetString("_val8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Water cut off date !.
        /// </summary>
        internal static string _val9 {
            get {
                return ResourceManager.GetString("_val9", resourceCulture);
            }
        }
    }
}
