//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_PM_UPDATE_OVERTIME_STATUSResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_PM_UPDATE_OVERTIME_STATUSResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_PM_UPDATE_OVERTIME_STATUSResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_PM_UPDATE_OVERTIME_STATUSResources.RSP_PM_UPDATE_OVERTIME_STATUSResources_msg" +
                            "rsc", typeof(RSP_PM_UPDATE_OVERTIME_STATUSResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process failed! unable to save Overtime Transaction {0}.
        /// </summary>
        internal static string ERROR_PROCESS {
            get {
                return ResourceManager.GetString("ERROR_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process failed! please input service!.
        /// </summary>
        internal static string INCOMPLETE_SVC {
            get {
                return ResourceManager.GetString("INCOMPLETE_SVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process failed! please input unit!.
        /// </summary>
        internal static string INCOMPLETE_UNIT {
            get {
                return ResourceManager.GetString("INCOMPLETE_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Department Code.
        /// </summary>
        internal static string INVALID_DEPT_CODE {
            get {
                return ResourceManager.GetString("INVALID_DEPT_CODE", resourceCulture);
            }
        }
    }
}
