//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMT01800FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMT01800FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMT01800FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMT01800FrontResources.PMT01800FrontResources_msgrsc", typeof(PMT01800FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string _BtnView {
            get {
                return ResourceManager.GetString("_BtnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found!.
        /// </summary>
        internal static string DATANOTFOUND {
            get {
                return ResourceManager.GetString("DATANOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string DCMNT {
            get {
                return ResourceManager.GetString("DCMNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string DEPT {
            get {
                return ResourceManager.GetString("DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string DPT {
            get {
                return ResourceManager.GetString("DPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string FLOR {
            get {
                return ResourceManager.GetString("FLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up Date.
        /// </summary>
        internal static string FLW_UP_DT {
            get {
                return ResourceManager.GetString("FLW_UP_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Offer Date.
        /// </summary>
        internal static string FRM_OFR_DT {
            get {
                return ResourceManager.GetString("FRM_OFR_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross.
        /// </summary>
        internal static string GRSS {
            get {
                return ResourceManager.GetString("GRSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC List.
        /// </summary>
        internal static string LOC_LIST {
            get {
                return ResourceManager.GetString("LOC_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC Date.
        /// </summary>
        internal static string LOCDATE {
            get {
                return ResourceManager.GetString("LOCDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC Number.
        /// </summary>
        internal static string LOCNO {
            get {
                return ResourceManager.GetString("LOCNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOO List.
        /// </summary>
        internal static string LOO_LIST {
            get {
                return ResourceManager.GetString("LOO_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        internal static string NETT {
            get {
                return ResourceManager.GetString("NETT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Date.
        /// </summary>
        internal static string OFR_DT {
            get {
                return ResourceManager.GetString("OFR_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Number.
        /// </summary>
        internal static string OFR_NO {
            get {
                return ResourceManager.GetString("OFR_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospect/Tenant.
        /// </summary>
        internal static string PRSPK_TNT {
            get {
                return ResourceManager.GetString("PRSPK/TNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string PRTY {
            get {
                return ResourceManager.GetString("PRTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Form Number.
        /// </summary>
        internal static string REVFRMNO {
            get {
                return ResourceManager.GetString("REVFRMNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RFSH {
            get {
                return ResourceManager.GetString("RFSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman.
        /// </summary>
        internal static string SLSMN {
            get {
                return ResourceManager.GetString("SLSMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string STST {
            get {
                return ResourceManager.GetString("STST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit ID.
        /// </summary>
        internal static string UNT_ID {
            get {
                return ResourceManager.GetString("UNT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type.
        /// </summary>
        internal static string UNT_TYP {
            get {
                return ResourceManager.GetString("UNT_TYP", resourceCulture);
            }
        }
    }
}
