//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMR00800BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMR00800BackResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMR00800BackResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMR00800BackResources.PMR00800BackResources_msgrsc", typeof(PMR00800BackResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement No.
        /// </summary>
        internal static string CCOLUMN_AGREEMENT_NO {
            get {
                return ResourceManager.GetString("CCOLUMN_AGREEMENT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area All.
        /// </summary>
        internal static string CCOLUMN_AREA_ALL {
            get {
                return ResourceManager.GetString("CCOLUMN_AREA_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Rented.
        /// </summary>
        internal static string CCOLUMN_AREA_RENTED {
            get {
                return ResourceManager.GetString("CCOLUMN_AREA_RENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string CCOLUMN_NO {
            get {
                return ResourceManager.GetString("CCOLUMN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCC Rate%.
        /// </summary>
        internal static string CCOLUMN_OCC_RATE {
            get {
                return ResourceManager.GetString("CCOLUMN_OCC_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied Area.
        /// </summary>
        internal static string CCOLUMN_OCCUPIED_AREA {
            get {
                return ResourceManager.GetString("CCOLUMN_OCCUPIED_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL-Available.
        /// </summary>
        internal static string CCOLUMN_PL_AVAILABLE {
            get {
                return ResourceManager.GetString("CCOLUMN_PL_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROMO LEVY.
        /// </summary>
        internal static string CCOLUMN_PL_HEADER {
            get {
                return ResourceManager.GetString("CCOLUMN_PL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL%.
        /// </summary>
        internal static string CCOLUMN_PL_PERCENT {
            get {
                return ResourceManager.GetString("CCOLUMN_PL_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL-Rented.
        /// </summary>
        internal static string CCOLUMN_PL_RENTED {
            get {
                return ResourceManager.GetString("CCOLUMN_PL_RENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string CCOLUMN_RENT_AVAILABLE {
            get {
                return ResourceManager.GetString("CCOLUMN_RENT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENT.
        /// </summary>
        internal static string CCOLUMN_RENT_HEADER {
            get {
                return ResourceManager.GetString("CCOLUMN_RENT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent%.
        /// </summary>
        internal static string CCOLUMN_RENT_PERCENT {
            get {
                return ResourceManager.GetString("CCOLUMN_RENT_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rented.
        /// </summary>
        internal static string CCOLUMN_RENT_RENTED {
            get {
                return ResourceManager.GetString("CCOLUMN_RENT_RENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC-Available.
        /// </summary>
        internal static string CCOLUMN_SC_AVAILABLE {
            get {
                return ResourceManager.GetString("CCOLUMN_SC_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE CHARGE.
        /// </summary>
        internal static string CCOLUMN_SC_HEADER {
            get {
                return ResourceManager.GetString("CCOLUMN_SC_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC%.
        /// </summary>
        internal static string CCOLUMN_SC_PERCENT {
            get {
                return ResourceManager.GetString("CCOLUMN_SC_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC-Rented.
        /// </summary>
        internal static string CCOLUMN_SC_RENTED {
            get {
                return ResourceManager.GetString("CCOLUMN_SC_RENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPACE.
        /// </summary>
        internal static string CCOLUMN_SPACE_HEADER {
            get {
                return ResourceManager.GetString("CCOLUMN_SPACE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Id.
        /// </summary>
        internal static string CCOLUMN_TENANT_ID {
            get {
                return ResourceManager.GetString("CCOLUMN_TENANT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        internal static string CCOLUMN_TENANT_NAME {
            get {
                return ResourceManager.GetString("CCOLUMN_TENANT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Id.
        /// </summary>
        internal static string CCOLUMN_UNIT_ID {
            get {
                return ResourceManager.GetString("CCOLUMN_UNIT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type.
        /// </summary>
        internal static string CCOLUMN_UNIT_TYPE {
            get {
                return ResourceManager.GetString("CCOLUMN_UNIT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string CLABEL_BUILDING {
            get {
                return ResourceManager.GetString("CLABEL_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string CLABEL_GRANDTOTAL {
            get {
                return ResourceManager.GetString("CLABEL_GRANDTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string CLABEL_PERIOD {
            get {
                return ResourceManager.GetString("CLABEL_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string CLABEL_PROPERTY {
            get {
                return ResourceManager.GetString("CLABEL_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        internal static string CLABEL_SUBTOTAL {
            get {
                return ResourceManager.GetString("CLABEL_SUBTOTAL", resourceCulture);
            }
        }
    }
}
