//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT00200FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APT00200FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APT00200FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APT00200FrontResources.APT00200FrontResources_msgrsc", typeof(APT00200FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string _Addition {
            get {
                return ResourceManager.GetString("_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add On.
        /// </summary>
        internal static string _AddOn {
            get {
                return ResourceManager.GetString("_AddOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocate.
        /// </summary>
        internal static string _Allocate {
            get {
                return ResourceManager.GetString("_Allocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation ID.
        /// </summary>
        internal static string _AllocationID {
            get {
                return ResourceManager.GetString("_AllocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Suppliers.
        /// </summary>
        internal static string _AllSuppliers {
            get {
                return ResourceManager.GetString("_AllSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string _Amount {
            get {
                return ResourceManager.GetString("_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount (Base).
        /// </summary>
        internal static string _Amount_Base_ {
            get {
                return ResourceManager.GetString("_Amount(Base)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount (Local).
        /// </summary>
        internal static string _Amount_Local_ {
            get {
                return ResourceManager.GetString("_Amount(Local)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount (Trx).
        /// </summary>
        internal static string _Amount_Trx_ {
            get {
                return ResourceManager.GetString("_Amount(Trx)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Qty.
        /// </summary>
        internal static string _ApprovedQty {
            get {
                return ResourceManager.GetString("_ApprovedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        internal static string _BaseCurrency {
            get {
                return ResourceManager.GetString("_BaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CF.
        /// </summary>
        internal static string _CF {
            get {
                return ResourceManager.GetString("_CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge ID.
        /// </summary>
        internal static string _ChargeID {
            get {
                return ResourceManager.GetString("_ChargeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Name.
        /// </summary>
        internal static string _ChargeName {
            get {
                return ResourceManager.GetString("_ChargeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string _Close {
            get {
                return ResourceManager.GetString("_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreatedDate {
            get {
                return ResourceManager.GetString("_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curr..
        /// </summary>
        internal static string _Curr {
            get {
                return ResourceManager.GetString("_Curr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string _Currency {
            get {
                return ResourceManager.GetString("_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate.
        /// </summary>
        internal static string _CurrencyRate {
            get {
                return ResourceManager.GetString("_CurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _Date {
            get {
                return ResourceManager.GetString("_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction.
        /// </summary>
        internal static string _Deduction {
            get {
                return ResourceManager.GetString("_Deduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _Department {
            get {
                return ResourceManager.GetString("_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept. Code.
        /// </summary>
        internal static string _DeptCode {
            get {
                return ResourceManager.GetString("_DeptCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept. Name.
        /// </summary>
        internal static string _DeptName {
            get {
                return ResourceManager.GetString("_DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Description {
            get {
                return ResourceManager.GetString("_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string _Detail {
            get {
                return ResourceManager.GetString("_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc. Date.
        /// </summary>
        internal static string _DocDate {
            get {
                return ResourceManager.GetString("_DocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        internal static string _DocumentDate {
            get {
                return ResourceManager.GetString("_DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string _DocumentNo {
            get {
                return ResourceManager.GetString("_DocumentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string _DueDate {
            get {
                return ResourceManager.GetString("_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure.
        /// </summary>
        internal static string _Expenditure {
            get {
                return ResourceManager.GetString("_Expenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Entry.
        /// </summary>
        internal static string _ItemEntry {
            get {
                return ResourceManager.GetString("_ItemEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        internal static string _ItemList {
            get {
                return ResourceManager.GetString("_ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string _Journal {
            get {
                return ResourceManager.GetString("_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Amount.
        /// </summary>
        internal static string _LineAmount {
            get {
                return ResourceManager.GetString("_LineAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Discount.
        /// </summary>
        internal static string _LineDiscount {
            get {
                return ResourceManager.GetString("_LineDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Amount.
        /// </summary>
        internal static string _LocalAmount {
            get {
                return ResourceManager.GetString("_LocalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency.
        /// </summary>
        internal static string _LocalCurrency {
            get {
                return ResourceManager.GetString("_LocalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        internal static string _NetAmount {
            get {
                return ResourceManager.GetString("_NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _Notes {
            get {
                return ResourceManager.GetString("_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Tax.
        /// </summary>
        internal static string _OtherTax {
            get {
                return ResourceManager.GetString("_OtherTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period from.
        /// </summary>
        internal static string _Periodfrom {
            get {
                return ResourceManager.GetString("_Periodfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _Print {
            get {
                return ResourceManager.GetString("_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prod. Type.
        /// </summary>
        internal static string _ProdType {
            get {
                return ResourceManager.GetString("_ProdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string _Product {
            get {
                return ResourceManager.GetString("_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Dept..
        /// </summary>
        internal static string _ProductDept {
            get {
                return ResourceManager.GetString("_ProductDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string _ProductType {
            get {
                return ResourceManager.GetString("_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Amount.
        /// </summary>
        internal static string _PurchaseAmount {
            get {
                return ResourceManager.GetString("_PurchaseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Return Entry.
        /// </summary>
        internal static string _PurchaseReturnEntry {
            get {
                return ResourceManager.GetString("_PurchaseReturnEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Return Header.
        /// </summary>
        internal static string _PurchaseReturnHeader {
            get {
                return ResourceManager.GetString("_PurchaseReturnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Return Item.
        /// </summary>
        internal static string _PurchaseReturnItem {
            get {
                return ResourceManager.GetString("_PurchaseReturnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Return List.
        /// </summary>
        internal static string _PurchaseReturnList {
            get {
                return ResourceManager.GetString("_PurchaseReturnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string _Qty {
            get {
                return ResourceManager.GetString("_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redraft.
        /// </summary>
        internal static string _Redraft {
            get {
                return ResourceManager.GetString("_Redraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Date.
        /// </summary>
        internal static string _RefDate {
            get {
                return ResourceManager.GetString("_RefDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        internal static string _ReferenceNo {
            get {
                return ResourceManager.GetString("_ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. No..
        /// </summary>
        internal static string _RefNo {
            get {
                return ResourceManager.GetString("_RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string _Refresh {
            get {
                return ResourceManager.GetString("_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Qty.
        /// </summary>
        internal static string _ReturnQty {
            get {
                return ResourceManager.GetString("_ReturnQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Suppliers.
        /// </summary>
        internal static string _SelectedSuppliers {
            get {
                return ResourceManager.GetString("_SelectedSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq No..
        /// </summary>
        internal static string _SeqNo {
            get {
                return ResourceManager.GetString("_SeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string _Submit {
            get {
                return ResourceManager.GetString("_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string _Summary {
            get {
                return ResourceManager.GetString("_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Discount.
        /// </summary>
        internal static string _SummaryDiscount {
            get {
                return ResourceManager.GetString("_SummaryDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string _Supplier {
            get {
                return ResourceManager.GetString("_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier&apos;s Product.
        /// </summary>
        internal static string _Supplier_sProduct {
            get {
                return ResourceManager.GetString("_Supplier\'sProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Product ID.
        /// </summary>
        internal static string _SupplierProductID {
            get {
                return ResourceManager.GetString("_SupplierProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Product Name.
        /// </summary>
        internal static string _SupplierProductName {
            get {
                return ResourceManager.GetString("_SupplierProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string _Tax {
            get {
                return ResourceManager.GetString("_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable.
        /// </summary>
        internal static string _Taxable {
            get {
                return ResourceManager.GetString("_Taxable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        internal static string _TaxRate {
            get {
                return ResourceManager.GetString("_TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string _Term {
            get {
                return ResourceManager.GetString("_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string _to {
            get {
                return ResourceManager.GetString("_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Discount.
        /// </summary>
        internal static string _TotalDiscount {
            get {
                return ResourceManager.GetString("_TotalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string _TotalPrice {
            get {
                return ResourceManager.GetString("_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Purchase Return Amount.
        /// </summary>
        internal static string _TotalPurchaseReturnAmount {
            get {
                return ResourceManager.GetString("_TotalPurchaseReturnAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trx Amount.
        /// </summary>
        internal static string _TrxAmount {
            get {
                return ResourceManager.GetString("_TrxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string _Type {
            get {
                return ResourceManager.GetString("_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string _Unit {
            get {
                return ResourceManager.GetString("_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string _UnitPrice {
            get {
                return ResourceManager.GetString("_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdatedBy {
            get {
                return ResourceManager.GetString("_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdatedDate {
            get {
                return ResourceManager.GetString("_UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process Purchase Return with Manual Numbering! Transaction numbering setting for Purchase Return should be auto increment, not manual numbering!.
        /// </summary>
        internal static string M001 {
            get {
                return ResourceManager.GetString("M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this Purchase Return?.
        /// </summary>
        internal static string M002 {
            get {
                return ResourceManager.GetString("M002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Return Deleted Successfully!.
        /// </summary>
        internal static string M003 {
            get {
                return ResourceManager.GetString("M003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to submit this Purchase Return?.
        /// </summary>
        internal static string M004 {
            get {
                return ResourceManager.GetString("M004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to redraft this Purchase Return?.
        /// </summary>
        internal static string M005 {
            get {
                return ResourceManager.GetString("M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t saved your changes. Are you sure want to cancel?.
        /// </summary>
        internal static string M006 {
            get {
                return ResourceManager.GetString("M006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this Purchase Return Item?.
        /// </summary>
        internal static string M007 {
            get {
                return ResourceManager.GetString("M007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Return Item Deleted Successfully!.
        /// </summary>
        internal static string M008 {
            get {
                return ResourceManager.GetString("M008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this {0}?.
        /// </summary>
        internal static string M009 {
            get {
                return ResourceManager.GetString("M009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Deleted Successfully!.
        /// </summary>
        internal static string M010 {
            get {
                return ResourceManager.GetString("M010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Department!.
        /// </summary>
        internal static string V001 {
            get {
                return ResourceManager.GetString("V001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Supplier!.
        /// </summary>
        internal static string V002 {
            get {
                return ResourceManager.GetString("V002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select property!.
        /// </summary>
        internal static string V003 {
            get {
                return ResourceManager.GetString("V003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select department!.
        /// </summary>
        internal static string V004 {
            get {
                return ResourceManager.GetString("V004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select supplier!.
        /// </summary>
        internal static string V005 {
            get {
                return ResourceManager.GetString("V005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name is required!.
        /// </summary>
        internal static string V006 {
            get {
                return ResourceManager.GetString("V006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No. is required!.
        /// </summary>
        internal static string V007 {
            get {
                return ResourceManager.GetString("V007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date is required!.
        /// </summary>
        internal static string V008 {
            get {
                return ResourceManager.GetString("V008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select supplier!.
        /// </summary>
        internal static string V009 {
            get {
                return ResourceManager.GetString("V009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select currency!.
        /// </summary>
        internal static string V011 {
            get {
                return ResourceManager.GetString("V011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency Base Rate must be greater than 0!.
        /// </summary>
        internal static string V012 {
            get {
                return ResourceManager.GetString("V012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency Rate must be greater than 0!.
        /// </summary>
        internal static string V013 {
            get {
                return ResourceManager.GetString("V013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Base Rate must be greater than 0!.
        /// </summary>
        internal static string V014 {
            get {
                return ResourceManager.GetString("V014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Rate must be greater than 0!.
        /// </summary>
        internal static string V015 {
            get {
                return ResourceManager.GetString("V015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Tax ID!.
        /// </summary>
        internal static string V016 {
            get {
                return ResourceManager.GetString("V016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Base Rate must be greater than 0!.
        /// </summary>
        internal static string V017 {
            get {
                return ResourceManager.GetString("V017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Currency Rate must be greater than 0!.
        /// </summary>
        internal static string V018 {
            get {
                return ResourceManager.GetString("V018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required!.
        /// </summary>
        internal static string V019 {
            get {
                return ResourceManager.GetString("V019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Product Department!.
        /// </summary>
        internal static string V020 {
            get {
                return ResourceManager.GetString("V020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Product Type!.
        /// </summary>
        internal static string V021 {
            get {
                return ResourceManager.GetString("V021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Product!.
        /// </summary>
        internal static string V022 {
            get {
                return ResourceManager.GetString("V022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Expenditure!.
        /// </summary>
        internal static string V023 {
            get {
                return ResourceManager.GetString("V023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Allocation ID!.
        /// </summary>
        internal static string V024 {
            get {
                return ResourceManager.GetString("V024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Qty must be &gt; 0!.
        /// </summary>
        internal static string V025 {
            get {
                return ResourceManager.GetString("V025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Purchase Unit!.
        /// </summary>
        internal static string V026 {
            get {
                return ResourceManager.GetString("V026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Unit is required!.
        /// </summary>
        internal static string V027 {
            get {
                return ResourceManager.GetString("V027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Factor must be &gt; 0!.
        /// </summary>
        internal static string V028 {
            get {
                return ResourceManager.GetString("V028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price must be &gt; 0.
        /// </summary>
        internal static string V029 {
            get {
                return ResourceManager.GetString("V029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Discount Percentage! Please input value between 0 and 100..
        /// </summary>
        internal static string V030 {
            get {
                return ResourceManager.GetString("V030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount cannot be &lt; 0!.
        /// </summary>
        internal static string V031 {
            get {
                return ResourceManager.GetString("V031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Discount Amount! Discount Amount cannot be &gt; Total Price.
        /// </summary>
        internal static string V032 {
            get {
                return ResourceManager.GetString("V032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Discount Percentage! Please input value between 0 and 100..
        /// </summary>
        internal static string V033 {
            get {
                return ResourceManager.GetString("V033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount cannot be &lt; 0!.
        /// </summary>
        internal static string V034 {
            get {
                return ResourceManager.GetString("V034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Discount Amount! Discount Amount cannot be &gt; Total Price after Total Discount.
        /// </summary>
        internal static string V035 {
            get {
                return ResourceManager.GetString("V035", resourceCulture);
            }
        }
    }
}
