//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLTR00100BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GLTR00100BackResources_msgrsc___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GLTR00100BackResources_msgrsc___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLTR00100BackResources.GLTR00100BackResources_msgrsc - Copy", typeof(GLTR00100BackResources_msgrsc___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string Account_Name {
            get {
                return ResourceManager.GetString("Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string Account_No {
            get {
                return ResourceManager.GetString("Account_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary in.
        /// </summary>
        internal static string Base_Currency {
            get {
                return ResourceManager.GetString("Base_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        internal static string Document_Date {
            get {
                return ResourceManager.GetString("Document_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string Document_No {
            get {
                return ResourceManager.GetString("Document_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excharge Rate.
        /// </summary>
        internal static string Excharge_Rate {
            get {
                return ResourceManager.GetString("Excharge_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency.
        /// </summary>
        internal static string Local_Currency {
            get {
                return ResourceManager.GetString("Local_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Date.
        /// </summary>
        internal static string Reference_Date {
            get {
                return ResourceManager.GetString("Reference_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No..
        /// </summary>
        internal static string Reference_No {
            get {
                return ResourceManager.GetString("Reference_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversing Date.
        /// </summary>
        internal static string Reversing_Date {
            get {
                return ResourceManager.GetString("Reversing_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credit.
        /// </summary>
        internal static string Total_Credit {
            get {
                return ResourceManager.GetString("Total_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Debit.
        /// </summary>
        internal static string Total_Debit {
            get {
                return ResourceManager.GetString("Total_Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        internal static string Transaction_Type {
            get {
                return ResourceManager.GetString("Transaction_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string Updated_By {
            get {
                return ResourceManager.GetString("Updated_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher.
        /// </summary>
        internal static string Voucher {
            get {
                return ResourceManager.GetString("Voucher", resourceCulture);
            }
        }
    }
}
