//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_GS_UPLOAD_OTHER_UNIT_TYPEResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_GS_UPLOAD_OTHER_UNIT_TYPEResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_GS_UPLOAD_OTHER_UNIT_TYPEResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_GS_UPLOAD_OTHER_UNIT_TYPEResources.RSP_GS_UPLOAD_OTHER_UNIT_TYPEResources_msg" +
                            "rsc", typeof(RSP_GS_UPLOAD_OTHER_UNIT_TYPEResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department cannot be empty.
        /// </summary>
        internal static string EMPTY_DEPT_CODE {
            get {
                return ResourceManager.GetString("EMPTY_DEPT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Active Flag = 0, Non Active Date can not be empty.
        /// </summary>
        internal static string EMPTY_NON_ACTIVE_DATE {
            get {
                return ResourceManager.GetString("EMPTY_NON_ACTIVE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Unit Type Id can not be empty.
        /// </summary>
        internal static string EMPTY_OTHER_UNIT_TYPE_CODE {
            get {
                return ResourceManager.GetString("EMPTY_OTHER_UNIT_TYPE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Unit Type Name can not be empty.
        /// </summary>
        internal static string EMPTY_OTHER_UNIT_TYPE_NAME {
            get {
                return ResourceManager.GetString("EMPTY_OTHER_UNIT_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Unit Type Id is bigger than 20 Character.
        /// </summary>
        internal static string EXCESS_OTHER_UNIT_TYPE_CODE {
            get {
                return ResourceManager.GetString("EXCESS_OTHER_UNIT_TYPE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Unit Type Name is bigger than 100 Character.
        /// </summary>
        internal static string EXCESS_OTHER_UNIT_TYPE_NAME {
            get {
                return ResourceManager.GetString("EXCESS_OTHER_UNIT_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Active Flag, Active Flag value is not 1 / 0.
        /// </summary>
        internal static string INVALID_ACTIVE_FLAG {
            get {
                return ResourceManager.GetString("INVALID_ACTIVE_FLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Department Code.
        /// </summary>
        internal static string INVALID_DEPT_CODE {
            get {
                return ResourceManager.GetString("INVALID_DEPT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Property Type.
        /// </summary>
        internal static string INVALID_PROPERTY_TYPE {
            get {
                return ResourceManager.GetString("INVALID_PROPERTY_TYPE", resourceCulture);
            }
        }
    }
}
