//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMT02000FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMT02000FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMT02000FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMT02000FrontResources.PMT02000FrontResources_msgrsc", typeof(PMT02000FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Start Date.
        /// </summary>
        internal static string _ {
            get {
                return ResourceManager.GetString("-", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input HO Ref No!.
        /// </summary>
        internal static string _2001 {
            get {
                return ResourceManager.GetString("2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input HO Ref Date!.
        /// </summary>
        internal static string _2002 {
            get {
                return ResourceManager.GetString("2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input HO Actual Date!.
        /// </summary>
        internal static string _2003 {
            get {
                return ResourceManager.GetString("2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Opening Plan Start Date!.
        /// </summary>
        internal static string _2004 {
            get {
                return ResourceManager.GetString("2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Opening Plan End Date!.
        /// </summary>
        internal static string _2005 {
            get {
                return ResourceManager.GetString("2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Plan Start Date must before Opening Plan End Date!.
        /// </summary>
        internal static string _2006 {
            get {
                return ResourceManager.GetString("2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Plan Start Date must before Opening Plan End Date!.
        /// </summary>
        internal static string _2007 {
            get {
                return ResourceManager.GetString("2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Actual Size!.
        /// </summary>
        internal static string _2008 {
            get {
                return ResourceManager.GetString("2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Start Year!.
        /// </summary>
        internal static string _2009 {
            get {
                return ResourceManager.GetString("2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Start Month!.
        /// </summary>
        internal static string _2010 {
            get {
                return ResourceManager.GetString("2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Meter Start!.
        /// </summary>
        internal static string _2011 {
            get {
                return ResourceManager.GetString("2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Size*.
        /// </summary>
        internal static string _ActualSize {
            get {
                return ResourceManager.GetString("_ActualSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string _Building {
            get {
                return ResourceManager.GetString("_Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CF.
        /// </summary>
        internal static string _CF {
            get {
                return ResourceManager.GetString("_CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string _Charge {
            get {
                return ResourceManager.GetString("_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreatedDate {
            get {
                return ResourceManager.GetString("_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string _Delete {
            get {
                return ResourceManager.GetString("_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _Dept {
            get {
                return ResourceManager.GetString("_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string _Edit {
            get {
                return ResourceManager.GetString("_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string _Floor {
            get {
                return ResourceManager.GetString("_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Size.
        /// </summary>
        internal static string _GrossSize {
            get {
                return ResourceManager.GetString("_GrossSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Over.
        /// </summary>
        internal static string _HandOver {
            get {
                return ResourceManager.GetString("_HandOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HO Actual Date*.
        /// </summary>
        internal static string _HOActualDate {
            get {
                return ResourceManager.GetString("_HOActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HO Plan Date.
        /// </summary>
        internal static string _HOPlanDate {
            get {
                return ResourceManager.GetString("_HOPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HO Ref Date.
        /// </summary>
        internal static string _HORefDate {
            get {
                return ResourceManager.GetString("_HORefDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HO Ref No.
        /// </summary>
        internal static string _HORefNo {
            get {
                return ResourceManager.GetString("_HORefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string _labelMonth1 {
            get {
                return ResourceManager.GetString("_labelMonth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string _labelMonth10 {
            get {
                return ResourceManager.GetString("_labelMonth10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string _labelMonth11 {
            get {
                return ResourceManager.GetString("_labelMonth11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string _labelMonth12 {
            get {
                return ResourceManager.GetString("_labelMonth12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string _labelMonth2 {
            get {
                return ResourceManager.GetString("_labelMonth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string _labelMonth3 {
            get {
                return ResourceManager.GetString("_labelMonth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string _labelMonth4 {
            get {
                return ResourceManager.GetString("_labelMonth4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string _labelMonth5 {
            get {
                return ResourceManager.GetString("_labelMonth5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string _labelMonth6 {
            get {
                return ResourceManager.GetString("_labelMonth6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string _labelMonth7 {
            get {
                return ResourceManager.GetString("_labelMonth7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string _labelMonth8 {
            get {
                return ResourceManager.GetString("_labelMonth8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string _labelMonth9 {
            get {
                return ResourceManager.GetString("_labelMonth9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOI List.
        /// </summary>
        internal static string _LOIList {
            get {
                return ResourceManager.GetString("_LOIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOI Ref No.
        /// </summary>
        internal static string _LOIRef {
            get {
                return ResourceManager.GetString("_LOIRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Start.
        /// </summary>
        internal static string _MeterStart {
            get {
                return ResourceManager.GetString("_MeterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Size.
        /// </summary>
        internal static string _NetSize {
            get {
                return ResourceManager.GetString("_NetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan End Date*.
        /// </summary>
        internal static string _PlanEndDate {
            get {
                return ResourceManager.GetString("_PlanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Start Date*.
        /// </summary>
        internal static string _PlanStartDate {
            get {
                return ResourceManager.GetString("_PlanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTY.
        /// </summary>
        internal static string _Prop {
            get {
                return ResourceManager.GetString("_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redraft.
        /// </summary>
        internal static string _Redraft {
            get {
                return ResourceManager.GetString("_Redraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Month.
        /// </summary>
        internal static string _StartMonth {
            get {
                return ResourceManager.GetString("_StartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Year.
        /// </summary>
        internal static string _StartYear {
            get {
                return ResourceManager.GetString("_StartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string _Submit {
            get {
                return ResourceManager.GetString("_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        internal static string _Tenant {
            get {
                return ResourceManager.GetString("_Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Id.
        /// </summary>
        internal static string _Unit {
            get {
                return ResourceManager.GetString("_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdBy {
            get {
                return ResourceManager.GetString("_UpdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdDate {
            get {
                return ResourceManager.GetString("_UpdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility Type.
        /// </summary>
        internal static string _UtilityType {
            get {
                return ResourceManager.GetString("_UtilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t saved your changes. Are you sure want to cancel?.
        /// </summary>
        internal static string Cancel_Confirmation {
            get {
                return ResourceManager.GetString("Cancel_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this Hand Over?.
        /// </summary>
        internal static string Delete_Confirmation {
            get {
                return ResourceManager.GetString("Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to redraft this Handover?.
        /// </summary>
        internal static string Redraft_Confirmation {
            get {
                return ResourceManager.GetString("Redraft_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to submit this Handover?.
        /// </summary>
        internal static string Submit_Confirmation {
            get {
                return ResourceManager.GetString("Submit_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handover Deleted Successfully!.
        /// </summary>
        internal static string Success_Delete {
            get {
                return ResourceManager.GetString("Success_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handover Redraft Successfully!.
        /// </summary>
        internal static string Success_Redraft {
            get {
                return ResourceManager.GetString("Success_Redraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handover Submitted Successfully!.
        /// </summary>
        internal static string Success_Submit {
            get {
                return ResourceManager.GetString("Success_Submit", resourceCulture);
            }
        }
    }
}
