RSP_GL_GET_SYSTEM_PARAM '',''
EXEC RSP_GS_GET_OTHER_CHARGES_LIST 'BSI','ASHMD','A','ghc'
EXEC RSP_GL_GET_LAST_RATE_REVALUATION 'RCD','ACC','GHC'
EXEC RSP_GL_RATE_REVALUATION_PROCESS
'bsi',--@CCOMPANY_ID
'00',--@CDEPT_CODE
'20241201',--@CDATE
'AR',--@CPROCESS_FOR
'testquery1',--@CKEY_GUID
'VFM'--@CUSER_ID


SELECT TOP 1 CREF_DATE FROM GST_TRANS_HD