EXEC RSP_GS_GET_COMPANY_INFO 'rcd'
EXEC RSP_GL_GET_SYSTEM_PARAM 'rcd','en'
EXEC RSP_GS_GET_GSB_CODE_LIST 'BIMASAKTI','rcd','_GL_JOURNAL_STATUS','en',''
delete from sat_locking where CUSER_ID= 'ghc' 

exec RSP_GL_SEARCH_RECURRING_LIST '','','','','','','',''
EXEC RSP_GS_GET_DEPT_DETAIL '','',''

--LIST
exec RSP_GL_SEARCH_RECURRING_LIST
		 'rcd'--@CCOMPANY_ID		
		,'ghc'--@CUSER_ID			
		,'000030'--@CTRANS_CODE		
		,'ACC'--@CDEPT_CODE		
		,'202403'--@CPERIOD			
		,''--@CSTATUS			
		,''--@CSEARCH_TEXT		
		,'EN'--@CLANGUAGE_ID

--EXEC RSP_GL_GET_RECURRING_DETAIL_LIST  '01','ID'
EXEC RSP_GL_GET_RECURRING_JRN 'rcd','ghc','1852AF09-3D01-4655-8B98-8A1F0C3468A5','EN'


/**
  VAR_GSM_COMPANY
*/
EXEC RSP_GS_GET_COMPANY_INFO 'rcd'

/**
  VAR_GL_SYSTEM_PARAM
*/
EXEC RSP_GL_GET_SYSTEM_PARAM 'rcd', 'en'

/**
VAR_TODAY
*/
begin
declare @VAR_TODAY datetime
exec @VAR_TODAY=dbo.RFN_GET_DB_TODAY 'rcd'
select @VAR_TODAY
end

--VAR_CCURRENT_PERIOD_START_DATE
EXEC RSP_GS_GET_PERIOD_DT_INFO '','','' 

--VAR_CSOFT_PERIOD_START_DATE
SELECT CSTART_DATE 
FROM GSM_PERIOD_DT (NOLOCK)
WHERE CCOMPANY_ID='rcd' 
AND CCYEAR='2023'
AND CPERIOD_NO= '01'

/**
  VAR_IUNDO_COMMIT_JRN
*/
EXEC RSP_GL_GET_SYSTEM_ENABLE_OPTION_INFO  'rcd','GL014001'

/**
  VAR_GSM_TRANSACTION_CODE
*/
EXEC RSP_GS_GET_TRANS_CODE_INFO '',''
SELECT LINCREMENT_FLAG
      ,LAPPROVAL_FLAG 
FROM GSM_TRANSACTION_CODE (NOLOCK)
WHERE CCOMPANY_ID = 'rcd'
AND CTRANSACTION_CODE='000030'


/**
  VAR_GSM_PERIOD
*/
EXEC RSP_GS_GET_PERIOD_YEAR_RANGE 'RND','',''
SELECT IMIN_YEAR=CAST(MIN(CYEAR) AS INT)
      ,IMAX_YEAR=CAST(MAX(CYEAR) AS INT) 
FROM GSM_PERIOD (NOLOCK)
WHERE CCOMPANY_ID = 'rcd'

/*
VAR_STATUS
*/
SELECT CCODE='',CNAME='All' UNION SELECT CCODE,CDESCRIPTION AS CNAME FROM RFT_GET_GSB_CODE_INFO('BIMASAKTI', 'rsf','_GL_JOURNAL_STATUS', '', 'ID') ORDER BY CCODE

/*
List Currency
*/
EXEC RSP_GS_GET_CURRENCY_LIST 'rcd','ghc'

SELECT dbo.RFN_GET_DB_TODAY('rcd') AS CTODAY;

EXEC RSP_GS_GET_CURRENCY_RATE  'rcd','IDR','HUHU','yyyymmdd'

SELECT dbo.RFN_GET_DB_TODAY(@CCOMPANY_ID) AS DTODAY

--upload
EXEC RSP_GL_VALIDATE_RECURRING_UPLOAD 'GHC','bsi',''
EXEC RSP_GL_VALIDATE_BUDGET_UPLOAD