delete from sat_locking where CUSER_ID= 'ghc' 
select * from SAM_USER_LOCKING
EXEC RSP_GS_GET_COMPANY_PARAM 'rcd','ghc'
EXEC RSP_GS_MAINTAIN_COMP_PARAM 
'@CCOMPANY_ID',
1,--'@LPRIMARY_ACCOUNT',
'@CBASE_CURRENCY_CODE',
'@CLOCAL_CURRENCY_CODE',
'@CCENTER_BY',
1,--'@LCASH_FLOW'
'@CACTION',
'@CUSER_ID'

SELECT TOP 1 1 as LIS_PRIMARY FROM GSM_COMPANY (NOLOCK) 
WHERE CCOMPANY_ID <> 'bsi' 
AND LPRIMARY_ACCOUNT = 1

--TAX ----
EXEC RSP_GS_GET_COMPANY_TAX_INFO 'RCD','GHC' 
EXEC RSP_GS_MAINTAIN_TAX_INFO 'RCD','','','','','','','','','','','','',''

--vailidate is editable
EXEC RSP_GS_VALIDATE_COMP_PARAM 'rcd', 'ghc'

