delete from sat_locking where CUSER_ID= 'ghc'
EXEC RSP_GS_GET_PROPERTY_LIST 'bsi', 'ghc'
EXEC RSP_HD_GET_TASK_CHECKLIST_LIST 'rcd','ashmd','ghc'
EXEC RSP_HD_GET_CHECKLIST_LIST 'rcd','ashmd','ghc','TC01'
EXEC RSP_HD_MAINTAIN_CHECKLIST '','','','','','','',''
EXEC RSP_HD_MAINTAIN_TASK_CHECKLIST '','','','','','',''
EXEC RSP_HD_MAINTAIN_CHECKLIST '','','','','','','',''
EXEC RSP_HD_ACTIVE_INACTIVE_TASK_CHECKLIST '','','','',''
EXEC RSP_HD_GET_TASK_CHECKLIST_DT '', '', '', ''
EXEC RSP_HD_GET_CHECKLIST_DT '', '', '', '', ''