delete from sat_locking where CUSER_ID= 'ghc'
EXEC RSP_GS_GET_PROPERTY_LIST 'bsi', 'ghc'
EXEC RSP_HD_GET_PRICELIST_LIST 'rcd','ASHMD','1','en'
EXEC RSP_HD_GET_PRICELIST_DETAIL '','','',''
EXEC RSP_HD_MAINTAIN_PRICELIST '','','','','','','','','','','','','',''
EXEC RSP_GS_GET_COMPANY_PARAM 'bsi','ghc'
EXEC RSP_GS_GET_CURRENCY_LIST 'bsi','ghc'
EXEC RSP_HD_INACTIVE_PRICELIST '','','','',''
select * from HDM_PRICELIST_DT
select * from HDM_PRICELIST_HD

EXEC RSP_PM_GET_CHARGES_TYPE_LIST 'rcd','ashmd','01','ghc','0','1'

begin tran

CREATE TABLE #NEW_PRICELIST(
    NO			INT NOT NULL
    , CPRICELIST_ID	VARCHAR(20) NOT NULL
    , CPRICELIST_NAME     	NVARCHAR(100) NOT NULL
    , CDEPT_CODE     	VARCHAR(20) NOT NULL
    , CCHARGES_ID		VARCHAR(20) NOT NULL
    , CUNIT		VARCHAR(10) NOT NULL
    , CCURRENCY_CODE	VARCHAR(3) NOT NULL
    , IPRICE		INT NOT NULL
    , CDESCRIPTION	NVARCHAR(500)
    , CSTART_DATE		VARCHAR(8)
    )
	insert into #NEW_PRICELIST values(1,'BP02','Batch Pricelist 2','ACC','CH01','Unit','IDR',200000,'batch pricelist1','20250101')

EXEC RSP_HD_ADD_PRICELIST_PROCESS 'RCD','RLT','ghc','test1'
drop table #NEW_PRICELIST
rollback

select * from HDM_PRICELIST_HD
select * from HDM_PRICELIST_DT

EXEC RSP_HD_GET_PRICELIST_LIST @CCOMPANY_ID = 'BSI', @CPROPERTY_ID = 'RLT', @CSTATUS = '1', @CLANG_ID = 'en'
