
delete from sat_locking where CUSER_ID= 'vfm'
EXEC RSP_GS_GET_PROPERTY_LIST 'bsi', 'ghc'

EXEC RSP_PM_GET_SYSTEM_PARAM '','' 
EXEC RSP_GS_GET_GSB_CODE_LIST 'BIMASAKTI','RCD','_BS_UTILITY_CHARGES_TYPE','en','01,02,03,04,05,06,07'
Exec RSP_GS_GET_BUILDING_LIST 'RCD','ASHMD','ghc'

EXEC RSP_PM_GET_UPDATE_UTILITY_CHARGES_LIST
'bsi'--@CCOMPANY_ID
,'ASHMD'--@CPROPERTY_ID
,'00'--@CDEPT_CODE
,''--@CBUILDING_ID
,1--@LALL_BUILDING
,''--@CTENANT_ID
,'01'--@CUTILITY_TYPE
,'en'--@CLANG_ID

BEGIN TRANSACTION

	DECLARE @CGUID_ID VARCHAR(100)
	Set @CGUID_ID = 'updatebatchtest22'

	CREATE TABLE #UTILITY_CHARGES_LIST(
		[CCOMPANY_ID]		[varchar](8)		NOT NULL,
		[CPROPERTY_ID]		[varchar](20)		NOT NULL,
		[CDEPT_CODE]		[varchar](20)		NOT NULL,
		[CTRANS_CODE]		[varchar](10)		NOT NULL,
		[CREF_NO]			[varchar](30)		NOT NULL,
		[CSEQ_NO]			[varchar](3)		NOT NULL,
		[CUNIT_ID]			[varchar](20)		NOT NULL,
		[CCHARGES_ID]		[varchar](20)		NOT NULL,
		[CNEW_CHARGES_ID]	[varchar](20)		NOT NULL,
		[CTAX_ID]			[varchar](20)		NOT NULL,
		[CNEW_TAX_ID]		[varchar](20)		NOT NULL
	) 
	INSERT INTO #UTILITY_CHARGES_LIST VALUES(	
	'BSI','ASHMD','00','802061','LOI-U-2024090009','001','U-B-F3-02','EC01','EC02','VAT','');
	INSERT INTO #UTILITY_CHARGES_LIST VALUES(	
	'BSI','ASHMD','00','802061','LOI-U-2024090011','001','U-B-F4-01','EC02','EC01','VAT','');

	select * from #UTILITY_CHARGES_LIST

	EXEC RSP_PM_PROCESS_UPDATE_UTILITY_CHARGES
	'BSI'--@CCOMPANY_ID
	,'GHC'--@CUSER_ID
	,'updatebatchtest22'--@GUID_KEY

	SELECT * FROM GST_UPLOAD_ERROR_STATUS WHERE CKEY_GUID= 'updatebatchtest22'
	SELECT * FROM GST_UPLOAD_PROCESS_STATUS WHERE CKEY_GUID = 'updatebatchtest22'
ROLLBACK