EXEC RSP_PM_GET_FACILITY_UNIT_INQUIRY
'RCD',--@CCOMPANY_ID
'ASHMD',--@CPROPERTY_ID
'T001',--@CTENANT_ID
'TWR001',--@CBUILDING_ID
'FLR01',--@CFLOOR_ID
'U-C-F1-01',--@CUNIT_ID
'EN'--@CLANG_ID

EXEC RSP_PM_GET_UNIT_INQUIRY_HD
'RCD'--@CCOMPANY_ID
,'ASHMD'--@CPROPERTY_ID
,'01'--@CUNIT_OPTION
,'TWR001'--@CBUILDING_ID
,1--@LALL_BUILDING
,''--@CFROM_FLOOR_ID
,''--@CTO_FLOOR_ID
,'01'--@CUNIT_CATEGORY
,'01'--@CSTATUS_ID
,'EN'--@CLANG_ID

EXEC RSP_PM_GET_UNIT_AGREE_FORM_LIST
'BSI'--@CCOMPANY_ID
,'ASHMD'--@CPROPERTY_ID
,'TW-1'--@CBUILDING_ID
,'FLR05'--@CFLOOR_ID
,'U-F5-01'--@CUNIT_ID
,'en'--@CLANG_ID
,'2024'--@IPERIOD_YEAR

EXEC RSP_PM_GET_HANDOVER_CHECKLIST_LIST
'BSI'--@CCOMPANY_ID
,'ASHMD'--@CPROPERTY_ID
,'02'--@CDEPT_CODE
,'802061 '--@CTRANS_CODE
,'LOI-U-2024100038'--@CREF_NO
,'U-F2-11'--@CUNIT_ID,
,'FLR02' -- @CFLOOR_ID
,'TW-1' -- @CBUILDING_ID

EXEC RSP_PM_GET_UNIT_AGREE_FORM_LIST 'BSI', 'ASHMD', 'TW-1', 'FLR03', 'U-F3-03', 'en', 2024

EXEC [RSP_PM_GET_HANDOVER_CHECKLIST_LIST]

'BSI' 
,'ASHMD'
,'00'
,'802030'
,'AGRU-2024120001-AU' 
,'U-F2-11'
,'flr02'
,'tw-1'