--EXEC RSP_PM_GET_TENANT_CLASS_GRP_LIST 'RCD','ashmd','ghc'
--EXEC RSP_PM_GET_TENANT_CLASS_LIST 'RCD','JBMPC','cg02','ghc'
--EXEC RSP_PM_GET_TENANT_CLASS_DETAIL 'RCD','ashmd','cg01','tcid1','ghc'

--EXEC RSP_PM_MAINTAIN_TENANT_CLASS  'rcd','ashmd','cg01','tcid1','tcn01','ADD','ghc'
--SEBELUM ASSIGN
EXEC RSP_PM_GET_ASSIGN_TENANT_CLASS_LIST 'bsi','APT001','003','M1','ghc'
EXEC RSP_PM_GET_ASSIGN_TENANT_CLASS_LIST 'rcd','JBMPC','food','kfcfrontstore','ghc'

EXEC RSP_PM_GET_TENANT_CLASS_TENANT_LIST  'RCD','ASHMD','testdev2','ghc'

--EXEC RSP_LM_MAINTAIN_TENANT_CLASS_GRP 'RCD','ASHMD','TCG03','TCGNam3','ADD','GHC'
--EXEC RSP_LM_MAINTAIN_TENANT_CLASS_GRP  'RCD','ASHMD','TCG03','TCGNameeeee3','ADD','GHC'
--EXEC RSP_LM_MAINTAIN_TENANT_CLASS_GRP 'RCD','ASHMD','TCG03','TCGNam3','DELETE','GHC'

--EXEC RSP_LM_GET_TENANT_CLASS_GRP_LIST 'RCD','ASHMD','GHC'

--EXEC RSP_LM_GET_TENANT_CLASS_GRP_DETAIL   'RCD','ASHMD','TCG03','GHC'

EXEC RSP_GS_GET_PROPERTY_LIST 'RCD','ghc'

--EXEC RSP_LM_MAINTAIN_TENANT_CLASS_GRP 'RCD','ASHMD','TCG03','TCGNam3','ADD','GHC'
--EXEC RSP_LM_MAINTAIN_TENANT_CLASS_GRP  'RCD','ASHMD','TCG03','TCGNameeeee3','ADD','GHC'
--EXEC RSP_LM_MAINTAIN_TENANT_CLASS_GRP 'RCD','ASHMD','TCG03','TCGNam3','DELETE','GHC'

--EXEC RSP_LM_GET_TENANT_CLASS_GRP_LIST 'RCD','ASHMD','GHC'

--EXEC RSP_LM_GET_TENANT_CLASS_GRP_DETAIL   'RCD','ASHMD','TCG03','GHC'

EXEC RSP_PM_MOVE_TENANT_CLASS 
'RCD',--@CCOMPANY_ID
'ASHMD',--@CPROPERTY_ID
'testdev1',--@CTENANT_CLASSIFICATION_GROUP_ID
'testdev1',--@CFROM_TENANT_CLASSIFICATION_ID
'testdevclass2',--@CTO_TENANT_CLASSIFICATION_ID
'GHC',--@CUSER_LOGIN_ID
'LK002,MR1-T01,T005'--@CTENANT_LIST

delete from sat_locking where CUSER_ID= 'ghc' 

