EXEC RSP_PMR00600_GET_REPORT 
'BSI', --@CCOMPANY_ID
'ASHMD' --@CPROPERTY_ID
, '202409'--@CFROM_PERIOD
, '202411'--@CTO_PERIOD
, 'TW-1'--@CFROM_BUILDING_ID
, 'TW-3'--@CTO_BUILDING_ID
, '00'--@CFROM_DEPT_CODE
, '02'--@CTO_DEPT_CODE
, '1'--@CREPORT_TYPE
, ''--@CFROM_TENANT_ID
, ''--@CTO_TENANT_ID
, ''--@CFROM_SERVICE_ID
, ''--@CTO_SERVICE_ID
, ''--@CSTATUS
,''--@CINVOICE
,'en' --@CLANG_ID

EXEC RSP_GS_GET_PERIOD_YEAR_RANGE 
'RCD'
, ''
, ''

EXEC RSP_GS_GET_PROPERTY_LIST
'BSI'
, 'ghc'


delete from SAT_LOCKING where CUSER_ID='ghc'