SELECT p.name AS ParameterName, t.name AS ParameterType, p.max_length AS ParameterLength
FROM sys.parameters AS p
JOIN sys.types AS t ON t.user_type_id = p.user_type_id
WHERE object_id = OBJECT_ID('RSP_PMR00220_GET_REPORT')

delete from sat_locking where CUSER_ID= 'ghc'
EXEC RSP_GS_GET_PROPERTY_LIST 'rcd','en'
EXEC RSP_GS_GET_PERIOD_YEAR_RANGE 'RCD','',''
SELECT dbo.RFN_GET_DB_TODAY ('RCD')
EXEC RSP_GS_GET_PERIOD_DT_LIST 'RCD', '2023'
EXEC RSP_PMR00200_GET_REPORT
	'RCD'--@CCOMPANY_ID	
	, 'ASHMD'--@CPROPERTY_ID	
	, 'ACC'--@CFROM_DEPARTMENT_ID	
	, 'FIN'--@CTO_DEPARTMENT_ID
	, 'C099'--@CFROM_SALESMAN_ID
	, 'TEST02'	--@CTO_SALESMAN_ID
	, '202401'--@CFROM_PERIOD	
	, '202412'--@CTO_PERIOD
	,'1' --CREPORT_TYPE
	, 1 --@LIS_OUTSTANDING
	, 'EN'--@CLANG_ID	

EXEC RSP_PMR00210_GET_REPORT
	'BSI'--@CCOMPANY_ID	
	, 'ASHMD'--@CPROPERTY_ID	
	, '00'--@CFROM_DEPARTMENT_ID	
	, '02'--@CTO_DEPARTMENT_ID
	, 'SLM001'--@CFROM_SALESMAN_ID
	, 'SLM013'	--@CTO_SALESMAN_ID
	, '202410'--@CFROM_PERIOD	
	, '202501'--@CTO_PERIOD
	,'1' --CREPORT_TYPE
	, 1 --@LIS_OUTSTANDING
	, 'EN'--@CLANG_ID	

EXEC RSP_PMR00220_GET_REPORT
	'BSI'--@CCOMPANY_ID	
	, 'ASHMD'--@CPROPERTY_ID	
	, '00'--@CFROM_DEPARTMENT_ID	
	, '00'--@CTO_DEPARTMENT_ID
	, 'SLM001'--@CFROM_SALESMAN_ID
	, 'SLM012'	--@CTO_SALESMAN_ID
	, '202410'--@CFROM_PERIOD	
	, '202411'--@CTO_PERIOD
	,'1' --CREPORT_TYPE
	, 1 --@LIS_OUTSTANDING
	, 'EN'--@CLANG_ID	


		
	delete from sat_locking where CUSER_ID= 'admin' 

	
		
		
		
		
			