delete from sat_locking where CUSER_ID= 'ghc'
EXEC RSP_GS_GET_PROPERTY_LIST 'rcd', 'en'
EXEC RSP_GS_GET_PERIOD_YEAR_RANGE 'rcd','',''
EXEC RSP_PMR03100_GET_REPORT 
'BSI'--VAR_COMPANY_ID
, 'ASHMD'--CPROPERTY_ID
, '2024'--CCUT_OFF_YEAR
, 'ram'--VAR_USER_ID

