
SELECT p.name AS ParameterName, t.name AS ParameterType, p.max_length AS ParameterLength
FROM sys.parameters AS p
JOIN sys.types AS t ON t.user_type_id = p.user_type_id
WHERE object_id = OBJECT_ID('RSP_PM_GET_AGREEMENT_CHARGES_DISC_LIST')

delete from sat_locking where CUSER_ID= 'ghc' 

EXEC RSP_GS_GET_PROPERTY_LIST 'bsi','vfm'
SELECT CCODE, CDESCRIPTION FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'bsi', '_BS_UNIT_CHARGES_TYPE', '', 'en')
EXEC RSP_GS_GET_PERIOD_DT_LIST 'rcd', '2024'
EXEC RSP_GS_GET_BUILDING_LIST 'rcd','ASHMD','ghc'

EXEC RSP_PM_GET_AGREEMENT_CHARGES_DISC_LIST 
'BSI' --company 
, 'ASHMD' --property
, '02' --charge type
, 'RENTAL' --unit charges
, 'DC-RENT-001' --discount
, '01' --Selected "Discount Type'
, '202410'
, 1--all building
, ''--building
, 'A'--agreement type
, 'GHC'--userid


CREATE TABLE #AGREEMENT_CHARGES_DISCOUNT 
( 
CCOMPANY_ID		VARCHAR(8)
, CPROPERTY_ID		VARCHAR(20)
, CFLOOR_ID		VARCHAR(30)
, CUNIT_ID		VARCHAR(30)
, CTENANT_ID		VARCHAR(30)
, NCHARGES_AMOUNT		NUMERIC(18,2)
, NCHARGES_DISCOUNT	NUMERIC(18,2)
, NNET_CHARGES		NUMERIC(18,2)
, CLINK_TRANS_CODE		VARCHAR(8)
, CLINK_DEPT_CODE		VARCHAR(30)
, CLINK_REF_NO		VARCHAR(40)
, CSTART_DATE		VARCHAR(30)
, CEND_DATE		VARCHAR(30)
)
INSERT INTO #AGREEMENT_CHARGES_DISCOUNT
VALUES ('BSI', 'ASHMD', 'FLR04', 'U-B-F4-01','TNT07', 400000, 0, 40000, '802061', '00', 'LOI-U-2024090011', '20240910', '20250910'  )

EXEC RSP_PM_PROCESS_AGREEMENT_CHARGE_DISCOUNT 'BSI', 'ASHMD', '02', 'INSTALLMENT', 'DC-RENT-001', '2024', '10', 1, '', '1', 'PROCESS', 'RE'

