delete from sat_locking where CUSER_ID= 'ghc'

--first page
EXEC RSP_GS_GET_PROPERTY_LIST 'rcd', 'ghc'
EXEC RSP_GS_GET_BUILDING_LIST 'rcd','ashmd','ghc'
EXEC RSP_GS_GET_BUILDING_UNIT_LIST 'rcd','ashmd','TWR001','','ghc',0,'','','PMT03000','','',''
EXEC RSP_PM_GET_TRX_BY_UNIT
@CCOMPANY_ID	= 'RCD'
,@CPROPERTY_ID	= 'ASHMD'
,@CBUILDING_ID	= 'TWR001'
,@CFLOOR_ID		= 'FLR01'
,@CUNIT_ID		= 'U-C-F1-01'
,@CUSER_ID		= 'CH'



--popup
EXEC RSP_GS_GET_UNIT_TYPE_CTG_FACILITY_LIST 'rcd','ashmd','ST','ghc'
EXEC RSP_PM_GET_TENANT_UNIT_FACILITY 'RCD','ASHMD','T001','TWR001','FLR01','U-C-F1-01','AC','','GHC'
EXEC RSP_PM_GET_TENANT_UNIT_FACILITY 
@CCOMPANY_ID	  = 'BSI'
,@CPROPERTY_ID	  = 'ASHMD'
,@CTENANT_ID	  = 'TNT05'
,@CBUILDING_ID	  = 'TW-1'
,@CFLOOR_ID		  = 'FLR02'
,@CUNIT_ID		  = 'U-F2-12'
,@CFACILITY_TYPE  = 'CP'
,@CSEQUENCE		  = ''
,@CUSER_ID		  = 'ghc'

EXEC RSP_PM_GET_FACILITY_QTY_INFO
'BSI',--@CCOMPANY_ID
'ASHMD',--@CPROPERTY_ID
'TNT05',--@CTENANT_ID
'TW-1',--@CBUILDING_ID
'FLR02',--@CFLOOR_ID
'U-F2-12',--@CUNIT_ID
'CP'--@CFACILITY_TYPE

IF (OBJECT_ID('tempdb..#__SP_ERR_Table') is null) BEGIN
	select SP_Name=cast('' as varchar(50)), Err_Code=cast('' as varchar(20)), Err_Detail=cast('' as nvarchar(max)) into #__SP_ERR_Table where 0=1
end else begin
	truncate table #__SP_ERR_TABLE
end

begin try
	-- Jalankan script SP disini
	EXEC RSP_PM_MAINTAIN_TENANT_UNIT_FACILITY 
		'BSI',--@CCOMPANY_ID
		'ASHMD',--@CPROPERTY_ID
		'TNT05',--@CTENANT_ID
		'TW-1',--@CBUILDING_ID
		'FLR02',--@CFLOOR_ID
		'U-F2-12',--@CUNIT_ID
		'CP',--@CFACILITY_TYPE
		'002',--@CSEQUENCE
		'CardP-002',--@CREGIST_NO
		'20250211',--@CSTART_DATE
		'20250310',--@CEND_DATE
		1,--@LACTIVE
		'ADD',--@CACTION
		'ghc'--@CUSER_ID
end try
begin catch
	select * from #__SP_ERR_TABLE --untuk tahu error code yg di raise
end catch

EXEC RSP_PM_MAINTAIN_TENANT_UNIT_FACILITY 
'RCD',--@CCOMPANY_ID
'ASHMD',--@CPROPERTY_ID
'T001',--@CTENANT_ID
'TWR001',--@CBUILDING_ID
'FLR01',--@CFLOOR_ID
'U-C-F1-01',--@CUNIT_ID
'CP',--@CFACILITY_TYPE
'01',--@CSEQUENCE
'regno-001',--@CREGIST_NO
'20240130',--@CSTART_DATE
'20250131',--@CEND_DATE
1,--@LACTIVE
'EDIT',--@CACTION
'ghc'--@CUSER_ID

EXEC RSP_PM_MAINTAIN_TENANT_UNIT_FACILITY 
'RCD',--@CCOMPANY_ID
'ASHMD',--@CPROPERTY_ID
'T001',--@CTENANT_ID
'TWR001',--@CBUILDING_ID
'FLR01',--@CFLOOR_ID
'U-C-F1-01',--@CUNIT_ID
'CP',--@CFACILITY_TYPE
'02',--@CSEQUENCE
'regno-02',--@CREGIST_NO
'20250128',--@CSTART_DATE
'20250131',--@CEND_DATE
1,--@LACTIVE
'DELETE',--@CACTION
'ghc'--@CUSER_ID

EXEC RSP_PM_ACTIVE_INACTIVE_TENANT_UNIT_FACILITY
'',--@CCOMPANY_ID
'',--@CPROPERTY_ID
'',--@CTENANT_ID
'',--@CBUILDING_ID
'',--@CFLOOR_ID
'',--@CUNIT_ID
'',--@CFACILITY_TYPE
'',--@CSEQUENCE
0,--@LACTIVE
''--@CUSER_ID
