SELECT 
    COLUMN_NAME 
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
WHERE TABLE_NAME = 'PQM_USER_MENU' 
AND CONSTRAINT_NAME IN 
    (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'PQM_USER_MENU' AND CONSTRAINT_TYPE = 'PRIMARY KEY');

EXEC RSP_GS_GET_USER_LIST 'rcd'--@CCOMPANY_ID

EXEC RSP_GS_GET_COMPANY_INFO '' --@CCOMPANY_ID


EXEC RSP_PQ_GET_MENU 
'rcd',--@CCOMPANY_ID
''--@CMENU_ID

EXEC RSP_PQ_GET_USER_MENU
'bsi'--@CCOMPANY_ID
,'test'--@CMENU_ID
,''--@CUSER_ID

EXEC RSP_PQ_MAINTAIN_USER_MENU
'bsi'--@CCOMPANY_ID
,'test'--@CMENU_ID
,''--@selected CUSER_ID from lookup
,'ghc'--@CUSER_LOGIN
,'A'--@CACTION_MODE