<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="FAF00100FrontResources_msgrsc.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FAF00100FrontResources_msgrsc.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="FAF00100FrontResources_msgrsc.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>FAF00100FrontResources_msgrsc.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
