//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMR02000BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMR02000BackResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMR02000BackResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMR02000BackResources.PMR02000BackResources_msgrsc", typeof(PMR02000BackResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        internal static string LABEL_ALLOCATION {
            get {
                return ResourceManager.GetString("LABEL_ALLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string LABEL_AMOUNT {
            get {
                return ResourceManager.GetString("LABEL_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Apply.
        /// </summary>
        internal static string LABEL_BEGINNING_APPLY {
            get {
                return ResourceManager.GetString("LABEL_BEGINNING_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curr..
        /// </summary>
        internal static string LABEL_CURRENCY {
            get {
                return ResourceManager.GetString("LABEL_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string LABEL_CUSTOMER {
            get {
                return ResourceManager.GetString("LABEL_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        internal static string LABEL_CUSTOMER_TYPE {
            get {
                return ResourceManager.GetString("LABEL_CUSTOMER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LABEL_DATE {
            get {
                return ResourceManager.GetString("LABEL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string LABEL_DEPARTMENT {
            get {
                return ResourceManager.GetString("LABEL_DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain / Loss.
        /// </summary>
        internal static string LABEL_GAIN_LOSS {
            get {
                return ResourceManager.GetString("LABEL_GAIN_LOSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string LABEL_GRANDTOTAL {
            get {
                return ResourceManager.GetString("LABEL_GRANDTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOI/Agrmnt. No..
        /// </summary>
        internal static string LABEL_LOI_AGRMT_NO {
            get {
                return ResourceManager.GetString("LABEL_LOI_AGRMT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string LABEL_NO {
            get {
                return ResourceManager.GetString("LABEL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        internal static string LABEL_PARAM_BASE_CURR {
            get {
                return ResourceManager.GetString("LABEL_PARAM_BASE_CURR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string LABEL_PARAM_CURRENCY {
            get {
                return ResourceManager.GetString("LABEL_PARAM_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Off Date.
        /// </summary>
        internal static string LABEL_PARAM_CUTT_OFF_DATE {
            get {
                return ResourceManager.GetString("LABEL_PARAM_CUTT_OFF_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Based On.
        /// </summary>
        internal static string LABEL_PARAM_DATA_BASED_ON {
            get {
                return ResourceManager.GetString("LABEL_PARAM_DATA_BASED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string LABEL_PARAM_FILTER {
            get {
                return ResourceManager.GetString("LABEL_PARAM_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Category.
        /// </summary>
        internal static string LABEL_PARAM_FILTER_CUSTCTG {
            get {
                return ResourceManager.GetString("LABEL_PARAM_FILTER_CUSTCTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string LABEL_PARAM_FILTER_DEPT {
            get {
                return ResourceManager.GetString("LABEL_PARAM_FILTER_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        internal static string LABEL_PARAM_FILTER_TRANSTYPE {
            get {
                return ResourceManager.GetString("LABEL_PARAM_FILTER_TRANSTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency.
        /// </summary>
        internal static string LABEL_PARAM_LOCAL_CURR {
            get {
                return ResourceManager.GetString("LABEL_PARAM_LOCAL_CURR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string LABEL_PARAM_PERIOD {
            get {
                return ResourceManager.GetString("LABEL_PARAM_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string LABEL_PARAM_PROPERTY {
            get {
                return ResourceManager.GetString("LABEL_PARAM_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Based On.
        /// </summary>
        internal static string LABEL_PARAM_REMAINING_BASED_ON {
            get {
                return ResourceManager.GetString("LABEL_PARAM_REMAINING_BASED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string LABEL_PARAM_REPORT_TYPE {
            get {
                return ResourceManager.GetString("LABEL_PARAM_REPORT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Currency.
        /// </summary>
        internal static string LABEL_PARAM_TRANS_CURR {
            get {
                return ResourceManager.GetString("LABEL_PARAM_TRANS_CURR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product/Charge.
        /// </summary>
        internal static string LABEL_PRIDUCTCHARGE {
            get {
                return ResourceManager.GetString("LABEL_PRIDUCTCHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Department.
        /// </summary>
        internal static string LABEL_PRODUCTDEPT {
            get {
                return ResourceManager.GetString("LABEL_PRODUCTDEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Discount.
        /// </summary>
        internal static string LABEL_PRODUCTLINEDISC {
            get {
                return ResourceManager.GetString("LABEL_PRODUCTLINEDISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        internal static string LABEL_PRODUCTMEASUREMENT {
            get {
                return ResourceManager.GetString("LABEL_PRODUCTMEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Tax.
        /// </summary>
        internal static string LABEL_PRODUCTOTHERTAX {
            get {
                return ResourceManager.GetString("LABEL_PRODUCTOTHERTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string LABEL_PRODUCTQTY {
            get {
                return ResourceManager.GetString("LABEL_PRODUCTQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Amount.
        /// </summary>
        internal static string LABEL_PRODUCTTOTALAMOUNT {
            get {
                return ResourceManager.GetString("LABEL_PRODUCTTOTALAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string LABEL_PRODUCTTOTPRICE {
            get {
                return ResourceManager.GetString("LABEL_PRODUCTTOTPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string LABEL_PRODUCTUNITPRICE {
            get {
                return ResourceManager.GetString("LABEL_PRODUCTUNITPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Date.
        /// </summary>
        internal static string LABEL_REFDATE {
            get {
                return ResourceManager.GetString("LABEL_REFDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string LABEL_REFERENCE {
            get {
                return ResourceManager.GetString("LABEL_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No..
        /// </summary>
        internal static string LABEL_REFNO {
            get {
                return ResourceManager.GetString("LABEL_REFNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        internal static string LABEL_REMAINING {
            get {
                return ResourceManager.GetString("LABEL_REMAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total based on.
        /// </summary>
        internal static string LABEL_SUBTOTAL {
            get {
                return ResourceManager.GetString("LABEL_SUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string LABEL_TAX {
            get {
                return ResourceManager.GetString("LABEL_TAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trx Type.
        /// </summary>
        internal static string LABEL_TRANS_TYPE {
            get {
                return ResourceManager.GetString("LABEL_TRANS_TYPE", resourceCulture);
            }
        }
    }
}
