//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMR03100BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMR03100BackResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMR03100BackResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMR03100BackResources.PMR03100BackResources_msgrsc", typeof(PMR03100BackResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total PPh Amount.
        /// </summary>
        internal static string FOOTER_TOTPPHAMT {
            get {
                return ResourceManager.GetString("FOOTER_TOTPPHAMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Bukti Potong Amt.
        /// </summary>
        internal static string HEADER_CACUTTEDAMT {
            get {
                return ResourceManager.GetString("HEADER_CACUTTEDAMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Ref No.
        /// </summary>
        internal static string HEADER_CAREFNO {
            get {
                return ResourceManager.GetString("HEADER_CAREFNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPP(Neto).
        /// </summary>
        internal static string HEADER_DPPNETO {
            get {
                return ResourceManager.GetString("HEADER_DPPNETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Amt Excl.
        /// </summary>
        internal static string HEADER_INVAMTEXCL {
            get {
                return ResourceManager.GetString("HEADER_INVAMTEXCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Year.
        /// </summary>
        internal static string HEADER_MONTHYEAR {
            get {
                return ResourceManager.GetString("HEADER_MONTHYEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPh Amount.
        /// </summary>
        internal static string HEADER_PPHAMOUNT {
            get {
                return ResourceManager.GetString("HEADER_PPHAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Off Year.
        /// </summary>
        internal static string PARAM_CUTOFF_YEAR {
            get {
                return ResourceManager.GetString("PARAM_CUTOFF_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string PARAM_PROPERTY {
            get {
                return ResourceManager.GetString("PARAM_PROPERTY", resourceCulture);
            }
        }
    }
}
