using System;
using System.Collections.Generic;
using System.Text;

namespace PMI00300COMMON
{
    public class ContextConstant
    {
        public const string PMI00300_GET_UNIT_INQUIRY_HEADER_LIST_STREAMING_CONTEXT = "PMI00300_GET_UNIT_INQUIRY_HEADER_LIST_STREAMING_CONTEXT";
        public const string PMI00300_GET_UNIT_INQUIRY_LEFT_DETAIL_LIST_STREAMING_CONTEXT = "PMI00300_GET_UNIT_INQUIRY_LEFT_DETAIL_LIST_STREAMING_CONTEXT";
        public const string PMI00300_GET_UNIT_INQUIRY_RIGHT_DETAIL_LIST_STREAMING_CONTEXT = "PMI00300_GET_UNIT_INQUIRY_RIGHT_DETAIL_LIST_STREAMING_CONTEXT";
        public const string PMI00300_GET_AGREEMENT_FORM_LIST_STREAMING_CONTEXT = "PMI00300_GET_AGREEMENT_FORM_LIST_STREAMING_CONTEXT";
        public const string PMI00300_GET_LS_STATUS_LIST_STREAMING_CONTEXT = "PMI00300_GET_LS_STATUS_LIST_STREAMING_CONTEXT";
    }
}
