<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="FAT00100FrontResources_msgrsc.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FAT00100FrontResources_msgrsc.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="FAT00100FrontResources_msgrsc.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>FAT00100FrontResources_msgrsc.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="FAT00100FrontResources_msgrsc.id.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>FAT00100FrontResources_msgrsc.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>

