//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR00600FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CBR00600FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CBR00600FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CBR00600FrontResources.CBR00600FrontResources_msgrsc", typeof(CBR00600FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        internal static string _AdditionalInfo {
            get {
                return ResourceManager.GetString("_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        internal static string _Allocation {
            get {
                return ResourceManager.GetString("_Allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Bank Message.
        /// </summary>
        internal static string _CashBankMessage {
            get {
                return ResourceManager.GetString("_CashBankMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _Date {
            get {
                return ResourceManager.GetString("_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _Department {
            get {
                return ResourceManager.GetString("_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Description {
            get {
                return ResourceManager.GetString("_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered By.
        /// </summary>
        internal static string _FilteredBy {
            get {
                return ResourceManager.GetString("_FilteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string _From {
            get {
                return ResourceManager.GetString("_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        internal static string _Include {
            get {
                return ResourceManager.GetString("_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string _Invoice {
            get {
                return ResourceManager.GetString("_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string _Journal {
            get {
                return ResourceManager.GetString("_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Type.
        /// </summary>
        internal static string _MessageType {
            get {
                return ResourceManager.GetString("_MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Receipt.
        /// </summary>
        internal static string _OfficialReceipt {
            get {
                return ResourceManager.GetString("_OfficialReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string _Period {
            get {
                return ResourceManager.GetString("_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _Print {
            get {
                return ResourceManager.GetString("_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print CB Transaction.
        /// </summary>
        internal static string _PrintCBTransaction {
            get {
                return ResourceManager.GetString("_PrintCBTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        internal static string _Receipt {
            get {
                return ResourceManager.GetString("_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No..
        /// </summary>
        internal static string _ReferenceNo {
            get {
                return ResourceManager.GetString("_ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string _Saveas {
            get {
                return ResourceManager.GetString("_Saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string _To {
            get {
                return ResourceManager.GetString("_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        internal static string _TransactionType {
            get {
                return ResourceManager.GetString("_TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Property!.
        /// </summary>
        internal static string V01 {
            get {
                return ResourceManager.GetString("V01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Department!.
        /// </summary>
        internal static string V02 {
            get {
                return ResourceManager.GetString("V02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Transaction Type!.
        /// </summary>
        internal static string V03 {
            get {
                return ResourceManager.GetString("V03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Reference No. is required!.
        /// </summary>
        internal static string V04 {
            get {
                return ResourceManager.GetString("V04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Reference No. is required!.
        /// </summary>
        internal static string V05 {
            get {
                return ResourceManager.GetString("V05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date is required!.
        /// </summary>
        internal static string V06 {
            get {
                return ResourceManager.GetString("V06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date is required!.
        /// </summary>
        internal static string V07 {
            get {
                return ResourceManager.GetString("V07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include at least one type of report!.
        /// </summary>
        internal static string V08 {
            get {
                return ResourceManager.GetString("V08", resourceCulture);
            }
        }
    }
}
