//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLM00400FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GLM00400FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GLM00400FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLM00400FrontResources.GLM00400FrontResources_msgrsc", typeof(GLM00400FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation No. is required!.
        /// </summary>
        internal static string _4001 {
            get {
                return ResourceManager.GetString("4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation No. Maximum 20 Character.
        /// </summary>
        internal static string _4002 {
            get {
                return ResourceManager.GetString("4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Name is required!.
        /// </summary>
        internal static string _4003 {
            get {
                return ResourceManager.GetString("4003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Name Maximum 100 Character.
        /// </summary>
        internal static string _4004 {
            get {
                return ResourceManager.GetString("4004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Department!.
        /// </summary>
        internal static string _4005 {
            get {
                return ResourceManager.GetString("4005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in From Allocation No..
        /// </summary>
        internal static string _4006 {
            get {
                return ResourceManager.GetString("4006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in To Allocation No..
        /// </summary>
        internal static string _4007 {
            get {
                return ResourceManager.GetString("4007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string _Account {
            get {
                return ResourceManager.GetString("_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string _AccountName {
            get {
                return ResourceManager.GetString("_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string _AccountNo {
            get {
                return ResourceManager.GetString("_AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        internal static string _Alloc {
            get {
                return ResourceManager.GetString("_Alloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Entry.
        /// </summary>
        internal static string _AllocEntry {
            get {
                return ResourceManager.GetString("_AllocEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Name.
        /// </summary>
        internal static string _AllocName {
            get {
                return ResourceManager.GetString("_AllocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation No..
        /// </summary>
        internal static string _AllocNo {
            get {
                return ResourceManager.GetString("_AllocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Period.
        /// </summary>
        internal static string _AllocPriod {
            get {
                return ResourceManager.GetString("_AllocPriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Year.
        /// </summary>
        internal static string _AllocYear {
            get {
                return ResourceManager.GetString("_AllocYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaiblable Centers.
        /// </summary>
        internal static string _AvaibCenter {
            get {
                return ResourceManager.GetString("_AvaibCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaiblable Account.
        /// </summary>
        internal static string _AvaiblAccount {
            get {
                return ResourceManager.GetString("_AvaiblAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS/IS.
        /// </summary>
        internal static string _BsSi {
            get {
                return ResourceManager.GetString("_BsSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _CancelBtn {
            get {
                return ResourceManager.GetString("_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Code.
        /// </summary>
        internal static string _CenterCode {
            get {
                return ResourceManager.GetString("_CenterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name.
        /// </summary>
        internal static string _CenterName {
            get {
                return ResourceManager.GetString("_CenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string _CloseBtn {
            get {
                return ResourceManager.GetString("_CloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreateBy {
            get {
                return ResourceManager.GetString("_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreateDate {
            get {
                return ResourceManager.GetString("_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Center.
        /// </summary>
        internal static string _CurrentCenter {
            get {
                return ResourceManager.GetString("_CurrentCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db/Cr.
        /// </summary>
        internal static string _DbCr {
            get {
                return ResourceManager.GetString("_DbCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _Dept {
            get {
                return ResourceManager.GetString("_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        internal static string _EditAccount {
            get {
                return ResourceManager.GetString("_EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Value.
        /// </summary>
        internal static string _FormulaVal {
            get {
                return ResourceManager.GetString("_FormulaVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string _From {
            get {
                return ResourceManager.GetString("_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string _Period {
            get {
                return ResourceManager.GetString("_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _Print {
            get {
                return ResourceManager.GetString("_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _ProcessBtn {
            get {
                return ResourceManager.GetString("_ProcessBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string _Refresh {
            get {
                return ResourceManager.GetString("_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Centers.
        /// </summary>
        internal static string _SelecCenter {
            get {
                return ResourceManager.GetString("_SelecCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Account.
        /// </summary>
        internal static string _SelectAccount {
            get {
                return ResourceManager.GetString("_SelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Center.
        /// </summary>
        internal static string _SourceCenter {
            get {
                return ResourceManager.GetString("_SourceCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation by Period.
        /// </summary>
        internal static string _TabAllocPeriod {
            get {
                return ResourceManager.GetString("_TabAllocPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Center &amp; Allocation.
        /// </summary>
        internal static string _TabTargetCenter {
            get {
                return ResourceManager.GetString("_TabTargetCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Center.
        /// </summary>
        internal static string _TargetCenter {
            get {
                return ResourceManager.GetString("_TargetCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string _To {
            get {
                return ResourceManager.GetString("_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdateBy {
            get {
                return ResourceManager.GetString("_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdateDate {
            get {
                return ResourceManager.GetString("_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string _Year {
            get {
                return ResourceManager.GetString("_Year", resourceCulture);
            }
        }
    }
}
