--Password: CD-r5fdbsvr1#
rollback
delete from SAT_LOCKING where CUSER_ID='admin'

SELECT IMIN_YEAR=CAST(MIN(CYEAR) AS INT)
      ,IMAX_YEAR=CAST(MAX(CYEAR) AS INT)


FROM GSM_PERIOD (NOLOCK)
WHERE CCOMPANY_ID = 'rcd';


SELECT CCODE,CDESCRIPTION	FROM RFT_GET_GSB_CODE_INFO('BIMASAKTI', 'RCD', '_GL_TRIAL_BAL_TYPE', '', 'EN') 


SELECT CCODE ,CDESCRIPTION	FROM RFT_GET_GSB_CODE_INFO('BIMASAKTI', 'RCD', '_GL_TRIAL_BAL_PRINT_METHOD', '', 'EN')

RSP_GL_GET_BUDGET_FOR_TB_LIST 'BSI', '2023','B', 'EN'
RSP_GL_GET_BUDGET_FOR_TB_LIST 'RCD', '2023','L', 'EN'

rollback

RSP_GL_GET_BUDGET_FOR_TB_LIST

SELECT LINCREMENT_FLAG,LAPPROVAL_FLAG FROM GSM_TRANSACTION_CODE (NOLOCK) 
                                      WHERE CCOMPANY_ID = 'RCD' AND CTRANS_CODE ='000020'


--GENERATE REPORT
RSP_GL_REP_TRIAL_BALANCE

--LOOKUP Account
exec RSP_GS_GET_COA_LOOKUP_LIST 'rcd', 'N', 'en'
exec RSP_GS_GET_COA_LOOKUP_LIST 'rcd', 'S', 'hmc'

--LOOKUP CENTER
exec RSP_GS_GET_CENTER_LIST 'RCD', 'HMC'

--INITIAL PROCESS

EXEC RSP_GL_GET_SYSTEM_PARAM 'RCD','EN'
EXEC RSP_GL_GET_SYSTEM_PARAM 'rcd', 'en'


USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_GL_REP_TRIAL_BALANCE]
		@CUSER_ID = 'hmc',
		@CCOMPANY_ID = 'rcd',
		@CTB_TYPE = 'N',
		@CJOURNAL_ADJ_MODE = 'S',
		@CCURRENCY_TYPE = 'L',
		@CFROM_ACCOUNT_NO = '16.10.0001',
		@CTO_ACCOUNT_NO = '16.10.9999',
		@CFROM_CENTER_CODE = '',
		@CTO_CENTER_CODE = '',
		@CYEAR = '2023',
		@CFROM_PERIOD_NO = '03',
		@CTO_PERIOD_NO = '03',
		@CPRINT_METHOD = '00',
		@CBUDGET_NO = '',
		@CLANGUAGE_ID = 'EN'
SELECT	'Return Value' = @return_value
GO

EXEC [dbo].[RSP_GL_REP_TRIAL_BALANCE]
			 'HMC'				
			,'RCD'			
			,'N'--@CTB_TYPE					
			,'S'--@CJOURNAL_ADJ_MODE		
			,'L'--@CCURRENCY_TYPE			
			,'15.10.0001'--@CFROM_ACCOUNT_NO		
			,'15.10.9999'--@CTO_ACCOUNT_NO			
			,'MMKT'--@CFROM_CENTER_CODE		
			,'MMKT'--@CMTO_CENTER_CODE			
			,'2023'--@CYEAR						
			,'03'--@CFROM_PERIOD_NO			
			,'03'--@CTO_PERIOD_NO			
			,'00'--@CPRINT_METHOD			
			,'B2023'--@CBUDGET_NO				
			,'EN'

			RSP_GL_REP_TRIAL_BALANCE

EXEC [dbo].[RSP_GL_REP_TRIAL_BALANCE]
@CBUDGET_NO= '',
@CCOMPANY_ID= 'BSI', 
@CCURRENCY_TYPE= 'L', 
@CFROM_ACCOUNT_NO= '0A100', 
@CFROM_CENTER_CODE= '', 
@CFROM_PERIOD_NO= '01', 
@CJOURNAL_ADJ_MODE= 'M', 
@CLANGUAGE_ID= 'en', 
@CPRINT_METHOD= '10', 
@CTB_TYPE= 'N', 
@CTO_ACCOUNT_NO= '0E999', 
@CTO_CENTER_CODE= '', 
@CTO_PERIOD_NO= '01', 
@CUSER_ID= 'HMC', 
@CYEAR= '2024'


Parameter
{'@CBUDGET_NO': '', '@CCOMPANY_ID': 'BSI', 
'@CCURRENCY_TYPE': 'L', 
'@CFROM_ACCOUNT_NO': '0A100', 
'@CFROM_CENTER_CODE': '', 
'@CFROM_PERIOD_NO': '12', 
'@CJOURNAL_ADJ_MODE': 'M', 
'@CLANGUAGE_ID': 'en', 
'@CPRINT_METHOD': '10', 
'@CTB_TYPE': 'N', 
'@CTO_ACCOUNT_NO': '0E999', 
'@CTO_CENTER_CODE': '', 
'@CTO_PERIOD_NO': '12', 
'@CUSER_ID': 'HMC', 
@CYEAR': '2023'}
			
			*/


-----------------------------------------------------------------------------CR1------------------------------------------
RSP_GS_GET_PERIOD_YEAR_RANGE 'RCD', '',''

USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_GS_GET_PERIOD_YEAR_RANGE]
		@CCOMPANY_ID = N'rcd',
		@CYEAR = NULL,
		@CMODE = NULL

SELECT	'Return Value' = @return_value
GO

RSP_GL_GET_SYSTEM_PARAM 'rcd', 'en'

--BEFORE
SELECT CCODE,CDESCRIPTION	FROM RFT_GET_GSB_CODE_INFO('BIMASAKTI', 'RCD', '_GL_TRIAL_BAL_TYPE', '', 'EN');
--AFTER
exec RSP_GS_GET_GSB_CODE_LIST'BIMASAKTI','RCD', '_GL_TRIAL_BAL_TYPE', 'EN'

--BEFORE
SELECT CCODE ,CDESCRIPTION	FROM RFT_GET_GSB_CODE_INFO('BIMASAKTI', 'RCD', '_GL_TRIAL_BAL_PRINT_METHOD', '', 'EN')
--AFTER
exec RSP_GS_GET_GSB_CODE_LIST 'BIMASAKTI','RCD', '_GL_TRIAL_BAL_PRINT_METHOD', 'EN'

RSP_GS_GET_COA_LOOKUP_LIST 'rcd', 'N', 'hmc'

----------------CR02
--	Jalankan RSP_GS_GET_MIN_MAX_GLACCOUNT_NO dengan parameter, simpan hasil ke VAR_GLACCOUNT_NO_INFO
--VAR_COMPANY_ID
--	N
RSP_GS_GET_MIN_MAX_GLACCOUNT_NO 'rcd', 'N'
RSP_GS_GET_PERIOD_YEAR_RANGE 'rcd','',''

RSP_GS_GET_PERIOD_DT_LIST 'rcd', 2025
select * from GSM_PERIOD 
select * from GSM_PERIOD_DT

RSP_GL_GET_BUDGET_FOR_TB_LIST 'rcd', '2023', 'L', 'EN''

USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_GL_REP_TRIAL_BALANCE]
		@CUSER_ID = 'hmc',
		@CCOMPANY_ID = 'BSI',
		@CLANGUAGE_ID = 'EN',
		@CTB_TYPE = 'N',
		@CJOURNAL_ADJ_MODE = 'M',
		@CCURRENCY_TYPE = 'L',
		@CFROM_ACCOUNT_NO = '0A100',
		@CTO_ACCOUNT_NO = 'OA002',
		@CFROM_CENTER_CODE = '',
		@CTO_CENTER_CODE = '',
		@CYEAR = '2024',
		@CFROM_PERIOD_NO = '08',
		@CTO_PERIOD_NO = '08',
		@CPRINT_METHOD = '00',
		@CBUDGET_NO = ''
SELECT	'Return Value' = @return_value
GO