RSP_GS_GET_COMPANY_INFO 'rcd'

RSP_GL_GET_SYSTEM_PARAM'rcd', 'en'

RSP_GS_GET_DEPT_LOOKUP_LIST 'rcd','hmc'

RSP_GS_GET_PERIOD_DT_INFO 'rcd', '2023', '07'

RSP_GS_GET_TRANS_CODE_INFO 'rcd', '000000'

RSP_GL_GET_JOURNAL 'rcd', 'hmc'

RSP_GS_GET_PERIOD_YEAR_RANGE 'rcd','',''

RSP_GS_GET_GSB_CODE_LIST 'BIMASAKTI', 'RCD', '_GL_JOURNAL_STATUS', 'EN'

RSP_GS_GET_CURRENCY_LIST 'RCD', 'hmc'

RSP_GS_GET_CENTER_LIST 'rcd','hmc'

RSP_GL_SEARCH_REVERSING_LIST 'rcd', 'hmc', 'ACC', '202312', '', '', 'en'

RSP_GL_GET_JOURNAL 'rcd', 'hmc', '2C6AFFF4-848E-405F-9A0C-C6E9AD240748', 'en'

RSP_GL_GET_JOURNAL_DETAIL_LIST '2C6AFFF4-848E-405F-9A0C-C6E9AD240748', 'en'


RSP_GL_GET_JOURNAL 'rcd','hmc'

RSP_GL_GET_JOURNAL_DETAIL_LIST