USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_LM_MAINTAIN_UNIT_TYPE_BILLING_RULE]
		@CCOMPANY_ID = N'RCD',
		@CPROPERTY_ID = N'JBMPC',
		@CUNIT_TYPE_ID = N'1BRoom',
		@CBILLING_RULE_CODE = N'Rule5',
		@CBILLING_RULE_NAME = N'RULE',
		@LBOOKING_FEE = 1,
		@CBOOKING_FEE_CHARGES_ID = N'G909',
		@LWITH_DP = 1,
		@IDP_PERCENTAGE = 1,
		@IDP_INTERVAL = 1,
		@CDP_PERIOD_MODE = N'02',
		@CDP_CHARGE_ID = NULL,
		@LINSTALLMENT = 1,
		@IINSTALLMENT_PERCENTAGE = 1,
		@IINSTALLMENT_INTERVAL = 1,
		@CINSTALLMENT_PERIOD_MODE = N'02',
		@CINSTALLMENT_CHARGE_ID = N'G909',
		@LBANK_CREDIT = 1,
		@IBANK_CREDIT_PERCENTAGE = 1,
		@IBANK_CREDIT_INTERVAL = 1,
		@LACTIVE = 1,
		@CACTION = N'EDIT',
		@CUSER_ID = N'hmc'

SELECT	'Return Value' = @return_value

GO
