USE gy_bima_rcd
delete from SAT_LOCKING where CUSER_ID='hmc'
CTRANS_STATUS_LIST

USE [BIMASAKTI_11]
GO

DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_PM_GET_AGREEMENT_LIST]
		@CCOMPANY_ID = 'BSI',
		@CPROPERTY_ID = 'ASHMD',
		@CUSER_ID = 'HMC',
		@CTRANS_CODE = '802030,802061',
        @CTRANS_STATUS_LIST = '80,30',
        @CPROGRAM_ID  = 'PMT05500'
SELECT	'Return Value' = @return_value
GO

USE [BIMASAKTI_11]
GO

DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_PM_GET_AGREEMENT_LIST]
		@CCOMPANY_ID = 'BSI',
		@CPROPERTY_ID = 'ASHMD',
		@CUSER_ID = 'HMC',
		@CTRANS_CODE = '802030,802061',
        @CTRANS_STATUS_LIST = '80,30',
        @CPROGRAM_ID  = 'PMT05500' ---LOI-U-2024100002
SELECT	'Return Value' = @return_value
GO


USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_LM_GET_AGREEMENT_DEPOSIT_LIST]
		@CCOMPANY_ID = NULL,
		@CPROPERTY_ID = NULL,
		@CDEPT_CODE = NULL,
		@CTRANS_CODE = NULL,
		@CREF_NO = NULL,
		@CUSER_ID = NULL

SELECT	'Return Value' = @return_value

GO

RSP_LM_GET_AGREEMENT_DEPOSIT_LIST 
RSP_LM_GET_DEPOSIT_UNIT_LIST 'rcd'
RSP_PM_GET_DEPOSIT_Header 'rcd'
RSP_LM_GET_DEPOSIT_LIST  'rcd'
@CCHARGES_TYPE
RSP_LM_GET_DEPOSIT_INFO 'rcd', 'jbmpc'
RSP_LM_GET_DEPOSIT_INFO 'rcd','jbmpc', ''
RSP_LM_GET_DEPOSIT_INFO '', '', '', '','','',''

RSP_LM_MAINTAIN_AGREEMENT_DEPOSIT

RSP_LM_GET_DEPOSIT_INFO

RSP_LM_GET_AGREEMENT_DEPOSIT_LIST  'rcd', 'jbmpc', 'hmc'

select * from SAM_USER_LOCKING

RSP_LM_GET_DEPOSIT_LIST 'RCD', 'JBMPC', 'ACC', '802200', 'REF_28022024', 'HMC'

--INFO
RSP_LM_GET_DEPOSIT_INFO 'rcd', 'jbmpc', 'acc', '802200','REF_28022024','001','hmc'

--AGREEMENT
RSP_LM_GET_AGREEMENT_DEPOSIT_LIST 'rcd', 'JBMPC',  'hmc'
--DEPOSIT UNIT LIST
EXEC RSP_PM_GET_DEPOSIT_UNIT_LIST  
		@CCOMPANY_ID = NULL,
		@CPROPERTY_ID = NULL,
		@CDEPT_CODE = NULL,
		@CTRANS_CODE = NULL,
		@CREF_NO = NULL,
		@CUSER _ID = NULL;

		RSP_LM_GET_AGREEMENT_DEPOSIT_LIST 'rcd', 'ashmd', 'hmc'
		RSP_LM_GET_DEPOSIT_LIST 




		exec RSP_LM_GET_DEPOSIT_LIST 'RCD', 'JBMPC', 'ACC', '802200', 'REF_28022024', 'HMC'
		exec RSP_LM_GET_DEPOSIT_INFO 'RCD','JBMPC','ACC', '802200', 'REF_28022024','2','hmc'





		RSP_LM_GET_DEPOSIT_INFO

		select*from LMT_AGREEMENT_DEPOSIT
			
		RSP_LM_GET_DEPOSIT_HEADER  '','','','','',''
		RSP_LM_MAINTAIN_AGREEMENT_DEPOSIT


RSP_LM_GET_DEPOSIT_INFO 'rcd','jbmpc'
RSP_LM_GET_DEPOSIT_INFO 
EXEC RSP_LM_GET_UTILITY_METER_DT

USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_LM_MAINTAIN_AGREEMENT_DEPOSIT]
		@CCOMPANY_ID = 'RCD',
		@CPROPERTY_ID = 'JBMPC',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802200',
		@CREF_NO = 'REF_28022024',
		@CSEQ_NO = 002,
		@LCONTRACTOR = 1,
		@CCONTRACTOR_ID = 'Total',
		@CDEPOSIT_JRNGRP_CODE = 'DP01',
		@CDEPOSIT_DATE = '20240308',
		@CDEPOSIT_AMT = 500,
		@CDESCRIPTION = 'New Agreement Deposit',
		@CACTION = 'Add',
		@CUSER_ID = 'hmc'

SELECT	'Return Value' = @return_value

GO

RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'ashmd', '', 'hmc'

GSM_JRNGRP
RSP_LM_GET_AGREEMENT_DEPOSIT_LIST 
exec RSP_PM_GET_AGREEMENT_DEPOSIT_LIST 'rcd','jbmpc','','','','hmc'

EXEC RSP_PM_GET_DEPOSIT_LIST 'RCD', 'JBMPC', 'ACC', '802200', 'REF_28022024', 'HMC'

select * from SAM_USER_LOCKING

update SAM_USER_LOCKING 
set CUSER_ID='hmm' 
where CPROGRAM_ID='GSM04500'



exec RSP_PM_GET_DEPOSIT_UNIT_LIST 'rcd', 'jbmpc','ACC','802030', 'REF_20022024', 'hmc'

exec RSP_PM_GET_AGREEMENT_UNIT_INFO_LIST 'rcd', 'jbmpc','ACC','802030', 'REF_20022024', 'hmc'

exec RSP_PM_GET_DEPOSIT_HEADER 'rcd', 'jbmpc','ACC','802030', 'REF_20022024', 'hmc'

exec RSP_PM_GET_DEPOSIT_LIST 'rcd', 'jbmpc','ACC','802030', 'REF_20022024', 'hmc'

exec RSP_PM_GET_DEPOSIT_DETAIL_LIST 'rcd', 'jbmpc','ACC','802030', 'REF_20022024', 'hmc'

exec RSP_PM_GET_DEPOSIT_INFO '','','','','','',''

exec RSP_PM_MAINTAIN_AGREEMENT_DEPOSIT '','','','','','','','','','','',''

exec RSP_PM_GET_DEPOSIT_LIST 'rcd', 'jbmpc','ACC','802030', 'REF_20022024', 'hmc'

exec RSP_PM_GET_AGREEMENT_LIST 'rcd', 'jbmpc','hmc'
exec RSP_PM_GET_DEPOSIT_HEADER 'rcd','jbmpc', 'ACC', '802030', 'REF_20022024','hmc'

EXEC RSP_PM_GET_DEPOSIT_LIST
		@CCOMPANY_ID = 'RCD',
		@CPROPERTY_ID = 'JBMPC',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'REF_20022024',
		@CUSER_ID = 'hmc'

RSP_PM_GET_DEPOSIT_LIST 
select * from PMT_AGREEMENT
select * from DEP
-- CCURRENCY_CODE	CCURRENCY_NAME
--IDR	Indonesian Rupiah

EXEC	RSP_PM_GET_AGREEMENT_DETAIL
		@CCOMPANY_ID = 'RCD',
		@CPROPERTY_ID = 'JBMPC',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'REF_20022024',
		@CUSER_ID = 'hmc'


		--dibutuhkan 
		--CREF_NO, CUNIT_NAME_LIST, CUNIT_ID, CUNIT_NAME, CCURENCY
EXEC RSP_PM_GET_DEPOSIT_DETAIL_LIST
		@CCOMPANY_ID = 'bsi',
		@CPROPERTY_ID = 'ASHMD',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'CheckACC-20240600002-PM',
		@CSEQ_NO = '006',
		@CUSER_ID = 'hmc'

		--CheckACC-20240500003-PM ,, --CheckACC-20240600002-PM

USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_PM_GET_DEPOSIT_DETAIL_LIST]
		@CCOMPANY_ID = 'BSI',
		@CPROPERTY_ID = 'ASHMD',
		@CDEPT_CODE = '00',
		@CTRANS_CODE = '802061',
		@CREF_NO = 'LOI-U-2024100006',  --CheckACC-20240500003-PM
		@CSEQ_NO = '001', --001 --002
		@CUSER_ID = 'hmc'
SELECT	'Return Value' = @return_value
GO

EXEC RSP_PM_GET_DEPOSIT_LIST
		@CCOMPANY_ID = 'RCD',
		@CPROPERTY_ID = 'JBMPC',
		@CUSER_ID = 'hmc',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'CheckACC-20240300000-PM', --CheckACC-20240300000-PM
		@CSEQ_NO = '001'




exec RSP_PM_GET_DEPOSIT_INFO
		@CCOMPANY_ID = 'RCD',
		@CPROPERTY_ID = 'JBMPC',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'REF_20022024',
		@CSEQ_NO = '006',
		@CUSER_ID = 'hmc'

		-- info (belum sesuai)
		--CDEPOSIT_ID, CDEPOSIT_NAME, CDEPOSIT_DATE, NDEPOSIT_AMOUNT

		--CDEPOSIT_AMT
		RSP_PM_MAINTAIN_AGREEMENT_DEPOSIT
		RSP_PM_GET_DEPOSIT_LIST

		SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'rcd', '_PERIOD_MODE', '', 'en' )

select * from PMT_AGREEMENT_DEPOSIT

exec RSP_PM_GET_DEPOSIT_INFO
		@CCOMPANY_ID = 'RCD',
		@CPROPERTY_ID = 'JBMPC',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'REF_20022024',
		@CSEQ_NO = '001',
		@CUSER_ID = 'hmc'
		

-------------------------------------NEW CR--------------------------------
RSP_PM_GET_AGREEMENT_LIST 'rcd', 'jbmpc', 'hmc'
--BUILDING ID
--CCHARGE_MODE

/*
, @CCHARGE_MODE		VARCHAR(2)
	, @CBUILDING_ID		VARCHAR(20)

	, @CFLOOR_ID		VARCHAR(20)
	, @CUNIT_ID			VARCHAR(20)
*/
--UNIT INFO LIST
[RSP_PM_GET_AGREEMENT_UNIT_INFO_LIST]
		@CCOMPANY_ID = 'rcd',
		@CPROPERTY_ID = 'jbmpc',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'REF_20022024',
		@CUSER_ID = 'hmc'




-----DEPOSITLIST
[RSP_PM_GET_DEPOSIT_LIST]
		@CCOMPANY_ID = 'rcd',
		@CPROPERTY_ID = 'ashmd',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'CheckACC-20240600002-PM',
		@CCHARGE_MODE = '01',
		@CBUILDING_ID = 'TW-A',
		@CFLOOR_ID = 'L02', --Lt20
		@CUNIT_ID = 'UNT0A002002', --A01,--B001
		@CUSER_ID = 'hmc'

		EXEC RSP_PM_GET_DEPOSIT_LIST
		@CCOMPANY_ID = 'RCD',
		@CPROPERTY_ID = 'JBMPC',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'CheckACC-20240600002-PM',
		@CUSER_ID = 'hmc'
		EXEC RSP_PM_GET_DEPOSIT_LIST 'rcd','ASHMD','ACC','802030','CheckACC-20240600002-PM','01','TW-A','L01','A0102','ghc'

NBBASE_RATE_AMOUNT	NBCURRENCY_RATE_AMOUNT	NLBASE_RATE_AMOUNT	NLCURRENCY_RATE_AMOUNT
1.000000	1.000000	1.000000	1.000000
select * from GSM_COA
---------- DEPOSIT INFO------------------
		USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_PM_GET_DEPOSIT_INFO]
		@CCOMPANY_ID = NULL,
		@CPROPERTY_ID = NULL,
		@CDEPT_CODE = NULL,
		@CTRANS_CODE = NULL,
		@CREF_NO = NULL,
		@CSEQ_NO = NULL,
		@CUSER_ID = NULL

SELECT	'Return Value' = @return_value

GO

--------deposit header

USE [BIMASAKTI_11]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_PM_GET_DEPOSIT_HEADER]
		@CCOMPANY_ID = 'rcd',
		@CPROPERTY_ID = 'jbmpc',
		@CDEPT_CODE = 'FIN',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'REF_202404001',
		@CUSER_ID = 'hmc'

SELECT	'Return Value' = @return_value

GO

RSP_WRITEUPLOADPROCESSSTATUS

USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_PM_GET_DEPOSIT_LIST]
		@CCOMPANY_ID = 'RCD',
		@CPROPERTY_ID ='ASHMD',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'LMACC-20240800009-PM',
		@CCHARGE_MODE = '01',
		@CBUILDING_ID = 'TWR001',
		@CFLOOR_ID = 'GF',
		@CUNIT_ID = 'U-C-GF-02',
		@CUSER_ID = 'hmc'
SELECT	'Return Value' = @return_value
GO

select * from PMT_AGREEMENT --RSP_PM_GET_DEPOSIT_DETAIL_LIST
where DEPOSI 28,982,=892	
where CREF_NO = 'LMACC-20240700001-PM'
order by DCREATE_DATE desc

select * from PMT_AGREEMENT_DEPOSIT
where CSEQ_NO='004'

USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].RSP_PM_GET_DEPOSIT_INFO
		@CCOMPANY_ID = 'BSI',
		@CUSER_ID = 'hmc',
		@CPROPERTY_ID ='ASHMD',
		@CDEPT_CODE = '00',
		@CTRANS_CODE = '802061',
		@CREF_NO = 'LOI-U-2024100082',
		@CSEQ_NO = '001'
SELECT	'Return Value' = @return_value
GO

USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_PM_GET_DEPOSIT_LIST]
		@CCOMPANY_ID = 'RCD',
		@CPROPERTY_ID ='ASHMD',
		@CDEPT_CODE = 'ACC',
		@CTRANS_CODE = '802030',
		@CREF_NO = 'LMACC-20240800009-PM',
		@CCHARGE_MODE = '',
		@CBUILDING_ID = 'TWR001',
		@CFLOOR_ID = '',
		@CUNIT_ID = '',
		@CUSER_ID = 'hmc'
SELECT	'Return Value' = @return_value
GO

select * from PMT_AGREEMENT_DEPOSIT
where CTRANS_CODE ='802030' and CREF_NO = 'LMACC-20240800009-PM'

select * from PMT_AGREEMENT 
where CTRANS_CODE ='802030' and CREF_NO = 'LMACC-20240800009-PM'
CPAYMENT_TERM_CODE
T20

USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_PM_GET_DEPOSIT_LIST] --CCHARGES_TYPE
		@CCOMPANY_ID = 'BSI',
		@CPROPERTY_ID = 'ASHMD',
		@CDEPT_CODE = '00',
		@CTRANS_CODE = '802061',
		@CREF_NO = 'LOI-U-2024100083',
		@CCHARGE_MODE = '01',
		@CBUILDING_ID = 'TW-3',
		@CFLOOR_ID = '',
		@CUNIT_ID = '',
		@LINVOICED = 1,
		@CUSER_ID = 'hmc'
SELECT	'Return Value' = @return_value
GO
/*
--{'@CBUILDING_ID': 'TW-1', '@CCHARGE_MODE': '01', '@CCOMPANY_ID': 'BSI', 
'@CDEPT_CODE': '00', '@CFLOOR_ID': 'FLR01', '@CPROPERTY_ID': 'ASHMD', 
'@CREF_NO': 'LOI-U-2024100035', '@CTRANS_CODE': '802061', '@CUNIT_ID': 
'U-F1-21', '@CUSER_ID': 'HMC', '@LINVOICED': true}
 */
--{'@CCOMPANY_ID': 'BSI', '@CDEPT_CODE': '00', '@CPROPERTY_ID': 'ASHMD', '@CREF_NO': 'LOI-U-2024100007', '@CSEQ_NO': '003', '@CTRANS_CODE': '802061', '@CUSER_ID': 'HMC'}
USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_PM_GET_DEPOSIT_DETAIL_LIST]
	@CCOMPANY_ID = 'BSI',
		@CPROPERTY_ID = 'ASHMD',
		@CDEPT_CODE = '00',
		@CTRANS_CODE = '802061',
		@CREF_NO = 'LOI-U-2024100002',--heckACC-20240500003-PM
		@CSEQ_NO = '001',--001 --002
		@CUSER_ID = 'hmc'
SELECT	'Return Value' = @return_value
GO

-- CTRX_CODE ==190010 [CASH Payment Journal]
--CTRX_CODE ==190020 [Cheque Payment Journal] View Udah oke ERC
--CTRX_CODE ==190030 [Wire Payment Journal]
--

--
--
RSP_PM_GET_DEPOSIT_DETAIL_LIST
Parameter
{'@CCOMPANY_ID': 'BSI', '@CDEPT_CODE': '00', '@CPROPERTY_ID': 'ASHMD', '@CREF_NO': 'LOI-U-2024100002', '@CSEQ_NO': '001', '@CTRANS_CODE': '802061', '@CUSER_ID': 'HMC'}

SELECT * FROM GST_UPLOAD_ERROR_STATUS
WHERE CKEY_GUID = '5d6012fc9f544d14ab70ed57129b42ee' --'6fceb20131d64269b7771cd8de025e72

SELECT * FROM GST_UPLOAD_ERROR_STATUS
WHERE CKEY_GUID = '6fceb20131d64269b7771cd8de025e72'


SELECT * FROM PMT_AGREEMENT 
WHERE CCOMPANY_ID = 'BSI'
AND CDEPT_CODE = '00'
AND CTRANS_CODE = '802063'
AND CTRANS_STATUS = '30'

RSP_PM_MAINTAIN_AMORTIZATION

RSP_PM_UPDATE_AMORTIZATION_STATUS 
@CRF_NO
@CACTION

250000.00
255000.00
200000.00

PARAM_NDE
PARAM_NDEPOSIT_AMOUNT
250000.00
255000.00
200000.00

SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'rcd', '_BS_JOURNAL_GRP_TYPE', '', 'en')