PMT00100


EXEC RSP_GET_REPORT_TEMPLATE_LIST
@CCOMPANY_ID = 'BSI',
@CPROPERTY_ID ='ASHMD',
@CPROGRAM_ID ='PMT01100',
@CTEMPLATE_ID =''

EXEC RSP_PM_PRINT_AGREEMENT 
@CCOMPANY_ID = 'bsi',
@CPROPERTY_ID ='ashmd',
@CDEPT_CODE='00',
@CTRANS_CODE='',
@CREF_NO='',
@CUSER_ID=''
CCOMPANY_ID	CCOMPANY_NAME	CCOMPANY_ADDRESS	CCOMPANY_CITY	CPROPERTY_ID	CPROPERTY_NAME	CDEPT_CODE	CTRANS_CODE	CREF_NO

CREF_DATE	CPROPERTY_CADDRESS	CPROPERTY_CITY	CPROPERTY_PROVINCE	CBUILDING_ID	CBUILDING_NAME	CSTART_DATE	CSTART_TIME	CEND_DATE	
CEND_TIME	IMONTHS	IYEARS	IDAYS	IHOURS	CSALESMAN_ID	CSALESMAN_NAME	CTENANT_ID	CTENANT_NAME	CTENANT_ADDRESS	CTENANT_CITY	
CTENANT_POSTAL_CODE	CTENANT_EMAIL	CTENANT_PHONE1	CTENANT_PHONE2	CTENANT_ATTENTION1_NAME	CTENANT_ATTENTION1_POSITION	CTENANT_GROUP_NAME	
CUNIT_DESCRIPTION	CNOTES	CCURRENCY_CODE	CCURRENCY_NAME	CUNIT_LIST	NTOTAL_GROSS_AREA	NTOTAL_NET_AREA	NTOTAL_ACTUAL_AREA	NTOTAL_COMMON_AREA	
NBOOKING_FEE	CLEASE_MODE	CLEASE_MODE_DESCR	CCHARGE_MODE	CCHARGE_MODE_DESCR	CTRANS_STATUS	CTRANS_STATUS_DESCR	CAGREEMENT_STATUS	CAGREEMENT_STATUS_DESCR	CUNIT_TYPE_CATEGORY_ID	CUNIT_TYPE_CATEGORY_NAME	ITOTAL_UNIT	CEXPIRED_DATE	CBILLING_RULE_TYPE	CBILLING_RULE_CODE	CBILLING_RULE_NAME	LWITH_DP	IDP_PERCENTAGE	IDP_INTERVAL	CDP_PERIOD_MODE	IINSTALLMENT_PERCENTAGE	IINSTALLMENT_INTERVAL	CINSTALLMENT_PERIOD_MODE	NLEASE_AMT	NLEASE_TOTAL_AMT	NLEASE_DP_AMT	NLEASE_INSTALLMENT_AMT	NCHARGES_AMT	NCHARGES_TOTAL_AMT	NDEPOSIT_TOTAL_AMT	NCAPACITY	CTC_CODE	IREVISE_SEQ_NO	LWITH_FO	CHO_PLAN_DATE	CHO_ACTUAL_DATE	CACTUAL_START_DATE	CACTUAL_START_TIME	CACTUAL_END_DATE	CACTUAL_END_TIME	CREC_ID	CSOLD_DATE	NACTUAL_PRICE	NSELL_PRICE	CUNIT_ID	CUNIT_NAME	CFLOOR_NAME