delete from SAT_LOCKING where CUSER_ID='hmc'


exec RSP_GS_GET_BUILDING_LIST 
@CCOMPANY_ID	 = 'rcd',
@CPROPERTY_ID= 'ashmd',
@CUSER_ID	 = 'hmc'

exec RSP_GS_GET_BUILDING_UNIT_LIST
@CCOMPANY_ID	= 'rcd',
@CPROPERTY_ID = 'ASHMD',
@CBUILDING_ID= 'Tower B',
@CFLOOR_ID= '',
@CUSER_ID= 'hmc',
@CUNIT_CATEGORY_LIST= '01,03'



--CSALESMAN_ID, CSALESMAN_NAME, CREF_DATE, NBOOKING_FEE, LPAID, CBOOK_STATUS_DESCR

exec RSP_PM_GET_AGREEMENT_DETAIL 
@CCOMPANY_ID	= 'rcd',
@CPROPERTY_ID = 'ASHMD',
@CDEPT_CODE= 'FIN',
@CTRANS_CODE='802011',
@CREF_NO='LOOFIN-20250100001-',
@CUSER_ID='hmc'

exec RSP_GS_GET_BUILDING_UNIT_LIST
@CCOMPANY_ID	= 'rcd',
@CPROPERTY_ID = 'ASHMD',
@CBUILDING_ID= 'Tower B',
@CFLOOR_ID= '',
@CUSER_ID= 'hmc',
@CUNIT_CATEGORY_LIST= '01,03'

exec RSP_PM_GET_AGREEMENT_BY_UNIT
@CCOMPANY_ID	= 'RCD',
@CPROPERTY_ID = 'ASHMD',
@CBUILDING_ID= 'Tower B',
@CFLOOR_ID='Floor1',
@CUNIT_ID='UNT09',
@LOTHER_UNIT=false,
@CTRANS_CODE = '802011',
@CUSER_ID='hmc'


RSP_PM_GET_AGREEMENT_UNIT_INFO_DT
@CCOMPANY_ID
@CPROPERTY_ID
@CDEPT_CODE
@CTRANS_CODE
@CREF_NO
@CUNIT_ID
@CFLOOR_ID
@CBUILDING_ID
@CUSER_ID


RSP_PM_MAINTAIN_AGREEMENT_UNIT
@CCOMPANY_ID
@CPROPERTY_ID
@CDEPT_CODE
@CTRANS_CODE
@CREF_NO
@CUNIT_ID
@CFLOOR_ID
@CBUILDING_ID
@NACTUAL_AREA_SIZE
@NCOMMON_AREA_SIZE
@CACTION
@CUSER_ID
RSP_PM_MAINTAIN_AGREEMENT_UNIT

RSP_GS_GET_CURRENCY_LIST 'rcd', 'hmc'

exec RSP_GS_GET_BUILDING_LIST 
@CCOMPANY_ID	 = 'rcd',
@CPROPERTY_ID= 'ashmd',
@CUSER_ID	 = 'hmc'

exec RSP_GS_GET_BUILDING_UNIT_LIST
@CCOMPANY_ID	= 'rcd',
@CPROPERTY_ID = 'ASHMD',
@CBUILDING_ID= 'Tower B',
@CFLOOR_ID= '',
@CUSER_ID= 'hmc',
@CUNIT_CATEGORY_LIST= '01,03'

exec RSP_PM_CHANGE_BOOK_UNIT
@CCOMPANY_ID
@CPROPERTY_ID
@CDEPT_CODE
@CTRANS_CODE
@CREF_NO
@CBUILDING_ID
@CFLOOR_ID
@CUNIT_ID
@CBILLING_RULE_TYPE
@CBILLING_RULE_CODE
@NACTUAL_PRICE
@NBOOKING_FEE
@CUSER_ID

exec RSP_GS_GET_BUILDING_UNIT_LIST
@CCOMPANY_ID	= 'rcd',
@CPROPERTY_ID = 'ASHMD',
@CBUILDING_ID= 'Tower B',
@CFLOOR_ID= '',
@CUSER_ID= 'hmc',
@CUNIT_CATEGORY_LIST= '01,03'

exec RSP_PM_GET_AGREEMENT_BY_UNIT
@CCOMPANY_ID	= 'rcd',
@CPROPERTY_ID = 'ASHMD',
@CBUILDING_ID= 'Tower B',
@CFLOOR_ID='Floor1',
@CUNIT_ID='UNT09',
@LOTHER_UNIT=false,
@CTRANS_CODE='802011',
@CUSER_ID='hmc'

rollback

exec RSP_PM_GET_AGREEMENT_UNIT_INFO_DT
@CCOMPANY_ID ='rcd',
@CPROPERTY_ID  = 'ASHMD',
@CDEPT_CODE = 'Acc',
@CTRANS_CODE = '802030',
@CREF_NO = 'LMACC-20240700001-PM',
@CUNIT_ID ='ut001',
@CFLOOR_ID = 'Floor2',
@CBUILDING_ID = 'Tower B',
@CUSER_ID ='hmc'
select * from PMT_AGREEMENT where CTRANS_CODE='802011'


exec RSP_PM_GET_AGREEMENT_UNIT_INFO_DT
@CCOMPANY_ID ='rcd',
@CPROPERTY_ID  = 'ASHMD',
@CDEPT_CODE = 'Acc',
@CTRANS_CODE = '802030',
@CREF_NO = 'LMACC-20240700001-PM',
@CUNIT_ID ='ut001',
@CFLOOR_ID = 'Floor2',
@CBUILDING_ID = 'Tower B',
@CUSER_ID ='hmc'

--kurang NSELL_PRICE, NACTUAL_PRICE, NBOOKING_FEE


RSP_GS_GET_BUILDING_FLOOR_LIST
@CCOMPANY_ID = 'rcd',
@CPROPERTY_ID ='ashmd',
@CBUILDING_ID ='Tower B',
@CUSER_ID ='hmc',
@LAGREEMENT =false,
@CPROGRAM_ID ='PMT00100',
@CTRANS_CODE ='802011',
@CREF_NO = 'LMACC-20240700001-PM'

exec RSP_PM_GET_ASSIGN_LOO_LIST 'BSI','ASHMD','802011','802012’','20240904','en'

exec RSP_PM_GET_AGREEMENT_DETAIL 
@CCOMPANY_ID	= 'rcd',
@CPROPERTY_ID = 'ASHMD',
@CDEPT_CODE= 'FIN',
@CTRANS_CODE='802011',
@CREF_NO='LOOFIN-20250100001-',
@CUSER_ID='hmc'

--jika parameter dari hendri tidak lengkap maka, minta field dari agreement detail

begin transaction --(error saat exec agreement unit) 

exec RSP_PM_MAINTAIN_AGREEMENT
@CCOMPANY_ID='RCD',
@CPROPERTY_ID='ASHMD',
@CDEPT_CODE='ACC',
@CTRANS_CODE='802011',
@CREF_NO='',
@CDOC_NO='',
@CDOC_DATE='',
@CREF_DATE='20250105',
@CBUILDING_ID='"Tower B"',
@CSTART_DATE='20250105',
@CEND_DATE='20250105',
@CSALESMAN_ID='S0003',
@CTENANT_ID='TJ',
@CNOTES='notes',
@CCURRENCY_CODE='ZMW',
@CBILLING_RULE_CODE='bIlling01',
@NACTUAL_PRICE=1200000,
@NBOOKING_FEE=1000000,
@CHO_PLAN_DATE=20250105,
@CACTION='ADD',
@CUSER_ID='HMC',
@CUNIT_DESCRIPTION='',
@CLEASE_MODE='',
@CCHARGE_MODE=''


exec RSP_PM_MAINTAIN_AGREEMENT_UNIT
@CCOMPANY_ID='RCD',
@CPROPERTY_ID='ASHMD',
@CDEPT_CODE='ACC',
@CTRANS_CODE='802011',
@CREF_NO='LOS-ACC-202501-00002',
@CUNIT_ID='UNT09',
@CFLOOR_ID='Floor1',
@CBUILDING_ID = 'Tower B',
@NACTUAL_AREA_SIZE =9999999,
@NCOMMON_AREA_SIZE=9999999,
@CACTION ='ADD',
@CUSER_ID='hmc'


RSP_PM_MAINTAIN_AGREEMENT
RSP_PM_MAINTAIN_AGREEMENT_UNIT

@CBILLING_RULE_TYPE

rollback
--apakah ada syarat validasi sehingga change unit bisa dilakukan dengan kriteria tertentu (2)
begin transaction
exec RSP_PM_CHANGE_BOOK_UNIT
@CCOMPANY_ID='RCD',
@CPROPERTY_ID='ASHMD',
@CDEPT_CODE='ACC',
@CTRANS_CODE='802011',
@CREF_NO ='LOOFIN-20250100004-',
@CBUILDING_ID = 'TW-A',
@CFLOOR_ID ='Floor1',
@CUNIT_ID = 'UNT3',
@CBILLING_RULE_TYPE ='', --???? diambil ketika pilih loookup
@CBILLING_RULE_CODE ='004',
@NACTUAL_AREA_SIZE =120,
@NCOMMON_AREA_SIZE=100,
@CUSER_ID ='hmc'


BEGIN TRANSACTION

IF (OBJECT_ID('tempdb..#__SP_ERR_Table') is null) BEGIN
	select SP_Name=cast('' as varchar(50)), Err_Code=cast('' as varchar(20)), Err_Detail=cast('' as nvarchar(max)) into #__SP_ERR_Table where 0=1
end else begin
	truncate table #__SP_ERR_TABLE
end

begin try
exec RSP_PM_CHANGE_BOOK_UNIT
@CCOMPANY_ID='RCD',
@CPROPERTY_ID='ASHMD',
@CDEPT_CODE='ACC',
@CTRANS_CODE='802011',
@CREF_NO ='LOOFIN-20250100004-',
@CBUILDING_ID = 'TW-A',
@CFLOOR_ID ='Floor1',
@CUNIT_ID = 'UNT3',
@CBILLING_RULE_TYPE ='', --???? diambil ketika pilih loookup
@CBILLING_RULE_CODE ='004',
@NACTUAL_PRICE =22200000,
@NBOOKING_FEE=1000000,
@CUSER_ID ='hmc'

end try
begin catch
	select * from #__SP_ERR_TABLE --untuk tahu error code yg di raise
end catch

ROLLBACK


select * from GSM_PROPERTY_UNIT
where CCOMPANY_ID='RCD' and CBUILDING_ID='TW-A'


begin transaction

exec RSP_PM_CHANGE_BOOK_UNIT
@CCOMPANY_ID='RCD',
@CPROPERTY_ID='ASHMD',
@CDEPT_CODE='ACC',
@CTRANS_CODE='802011',
@CREF_NO ='LOOFIN-20250100004-',
@CBUILDING_ID = 'TW-A',
@CFLOOR_ID ='GF',
@CUNIT_ID = 'UNIT01',
@CBILLING_RULE_TYPE ='', --???? diambil ketika pilih loookup
@CBILLING_RULE_CODE ='004',
@NACTUAL_PRICE =22200000,
@NBOOKING_FEE=1000000,
@CUSER_ID ='hmc'
 
 rollback

select * from PMT_AGREEMENT where CTRANS_CODE = '802011'



EXEC RSP_GS_GET_UNIT_TYPE_IMAGE_LIST
@CCOMPANY_ID ='rcd',
@CPROPERTY_ID ='ashmd',
@CUNIT_TYPE_ID = '1BRoom'

 exec RSP_PM_GET_AGREEMENT_BY_UNIT
@CCOMPANY_ID	= 'rcd',
@CPROPERTY_ID = 'ASHMD',
@CBUILDING_ID= 'TW-A',
@CFLOOR_ID='GF',
@CUNIT_ID='UNIT02',
@LOTHER_UNIT=false,
@CTRANS_CODE = '802011',
@CUSER_ID='hmc'

RSP_PM_UPDATE_AGREEMENT_TRANS_STS 

/*CPROPERTY_ID = _viewModelPMT00200.propertyValue, =ASHMD
                CDEPT_CODE = _viewModelPMT00200.DeptCode, =FIN
                CTRANS_CODE = _viewModelPMT00200.TransCode, = '802011'
                CREF_NO = _viewModelPMT00200.RefNo, ='LOOFIN-20250100004-'
                CFLOOR_ID = _viewModelPMT00200.loEntity.CFLOOR_ID, =Floor1
                CUNIT_ID = _viewModelPMT00200.loEntity.CUNIT_ID, UNT09
                CUNIT_NAME = _viewModelPMT00200.loEntity.CUNIT_NAME, Unit 9
                CUNIT_TYPE_ID = _viewModelPMT00200.loEntity.CUNIT_TYPE_ID, 2BRoom
                CUNIT_TYPE_NAME = _viewModelPMT00200.loEntity.CUNIT_TYPE_NAME,  Two Bath Room
                CCALLER_ACTION = "VIEW",*/
exec RSP_PM_GET_ASSIGN_LOO_LIST 
@CCOMPANY_ID = 'rcd',
@CPROPERTY_ID ='ashmd',
@CLOO_TRANS_CODE = '802011',
@CLOC_TRANS_CODE = '802012',
@CFROM_DATE = '20250101',
@CLANG_ID ='en'



exec RSP_GS_GET_BUILDING_UNIT_LIST
@CCOMPANY_ID	= 'rcd',
@CPROPERTY_ID = 'ASHMD',
@CBUILDING_ID= 'Tower B',
@CFLOOR_ID= '',
@CUSER_ID= 'hmc',
@CUNIT_CATEGORY_LIST= '01,03'

exec RSP_PM_GET_AGREEMENT_BY_UNIT
@CCOMPANY_ID	= 'RCD',
@CPROPERTY_ID = 'ASHMD',
@CBUILDING_ID= 'Tower B',
@CFLOOR_ID='Floor1',
@CUNIT_ID='UNT09',
@LOTHER_UNIT=false,
@CTRANS_CODE='802011',
@CUSER_ID='hmc'

exec RSP_PM_GET_AGREEMENT_DETAIL
@CCOMPANY_ID = 'rcd',
@CPROPERTY_ID ='ashmd',
@CDEPT_CODE ='ACC',
@CTRANS_CODE = '802011',
@CREF_NO = 'LOS-ACC-202501-00006',
@CUSER_ID =  'hmc'

select * from 


select * from PMT_AGREEMENT Where CTRANS_CODE = '802011'
order by DCREATE_DATE desc

select * from STORAGE_DATA_TABLE order by DCREATE_DATE desc

EXEC RSP_PM_PMA00300 'BSI', 'ASHMD', '202501', 'D','UN' --unit
EXEC RSP_PM_PMA00300D 'BSI', 'ASHMD', '202501', 'D','UT' --utility

CCOMPANY_ID	CPROPERTY_ID	CCUSTOMER_ID	CREF_NO	CCHARGES_TYPE	CMETER_NO	NBLOCK1_START	NBLOCK2_START	NBLOCK1_END	NBLOCK2_END	NBEBAN_BERSAMA	NBLOCK1_USAGE	NBLOCK2_USAGE	NKVA	NCF	NUSAGE_MIN_CHARGE	NMIN_CHARGE_AMT	NADDITIONAL_AMT	NTOTAL_USAGE_KVA	NSTANDING_CONSUMP_AMT	NSUB_TOTAL_AMT	NADMIN_FEE_AMT	NVAT_AMT	NADMIN_FEE_TAX_AMT	NTOTAL_AMT	CFROM_SEQ_NO
BSI	ASHMD	TNT05	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
SELECT * FROM GSB_CODE_DT WHERE CCLASS_ID IN ('_BS_UNIT_CHARGES_TYPE', '_BS_UTILITY_CHARGES_TYPE')
select * 


BEGIN TRANSACTION
IF (OBJECT_ID('tempdb..#__SP_ERR_Table') is null) BEGIN
	select SP_Name=cast('' as varchar(50)), Err_Code=cast('' as varchar(20)), Err_Detail=cast('' as nvarchar(max)) into #__SP_ERR_Table where 0=1
end else begin
	truncate table #__SP_ERR_TABLE
end

begin try

exec RSP_PM_GET_AGREEMENT_BY_UNIT
@CCOMPANY_ID	= 'RCD',
@CPROPERTY_ID = 'ASHMD',
@CBUILDING_ID= 'Tower B',
@CFLOOR_ID='Floor1',
@CUNIT_ID='UNT09',
@LOTHER_UNIT=false,
@CTRANS_CODE='802012',
@CUSER_ID='hmc'
/*
exec RSP_PM_MAINTAIN_AGREEMENT
@CACTION= 'ADD', @CBILLING_RULE_CODE= '005', @CBILLING_RULE_TYPE= '', 
@CBUILDING_ID= 'Tower B', @CCHARGE_MODE= '', @CCOMPANY_ID= 'RCD', 
@CCURRENCY_CODE= 'IDR', @CDEPT_CODE= 'FIN', @CDOC_DATE= '', @CDOC_NO= '', 
@CEND_DATE= '', @CEND_TIME= '', @CEXPIRED_DATE= '', @CFOLLOW_UP_DATE= '', 
@CHO_PLAN_DATE= '20250101', @CLEASE_MODE= '', @CLINK_REF_NO= 'LOOFIN-20250100004-', 
@CLINK_TRANS_CODE= '802011', @CNOTES= 'noteddddd[1]', @CORIGINAL_REF_NO= '', 
@CPROPERTY_ID= 'ASHMD', @CREF_DATE= '20250101', @CREF_NO= '', @CSALESMAN_ID= 'HNM008', 
@CSTART_DATE= '20250101', @CSTART_TIME= '', @CTAX_ID= 'PPN', @CTC_CODE= '', 
@CTENANT_ID= 'MR1-T01', @CTRANS_CODE= '802012', @CUNIT_DESCRIPTION= '', @CUSER_ID= 'HMC', 
@IDAYS= 0, @IHOURS= 0, @IMONTHS= 0, @IYEARS= 0, @LWITH_FO= false, @NACTUAL_PRICE= 123, 
@NBOOKING_FEE= 123


exec RSP_PM_MAINTAIN_AGREEMENT_UNIT
@CACTION= 'ADD', @CBUILDING_ID= 'Tower B', 
@CCOMPANY_ID= 'RCD', @CDEPT_CODE= 'FIN', 
@CFLOOR_ID= 'Floor1', @CPROPERTY_ID= 'ASHMD', 
@CREF_NO= 'LOCFIN-20250100001-', @CTRANS_CODE= '802012', 
@CUNIT_ID= 'UNT09', @CUSER_ID= 'HMC', @NACTUAL_AREA_SIZE= 0, @NCOMMON_AREA_SIZE= 0
*/
end try
begin catch
	select * from #__SP_ERR_TABLE --untuk tahu error code yg di raise
end catch

ROLLBACK


rollback

RSP_PM_GET_ASSIGN_LOO_LIST
@CCOMPANY_ID= 'BSI', 
@CFROM_DATE= '20250101', 
@CLANG_ID= 'en',
@CLOC_TRANS_CODE= '802012',
@CLOO_TRANS_CODE= '802011', 
@CPROPERTY_ID= 'ASHMD'

exec RSP_PM_GET_AGREEMENT_BY_UNIT
@CCOMPANY_ID	= 'RCD',
@CPROPERTY_ID = 'ASHMD',
@CBUILDING_ID= 'Tower B',
@CFLOOR_ID='Floor1',
@CUNIT_ID='UNT09',
@LOTHER_UNIT=false,
@CTRANS_CODE='802011',
@CUSER_ID='hmc'

 --{@CCOMPANY_ID= 'BSI', @CDEPT_CODE= '00', @CPROPERTY_ID= 'ASHMD', @CREF_NO= 'LOO-SU-00-20250200001', @CTRANS_CODE= '802011', @CUSER_ID= 'HMC'}
exec RSP_PM_GET_AGREEMENT_DETAIL 
@CCOMPANY_ID= 'BSI', @CDEPT_CODE= '00', @CPROPERTY_ID= 'ASHMD', 
@CREF_NO= 'LOC-SU-00-2025020001', @CTRANS_CODE= '802012', @CUSER_ID= 'HMC'
exec RSP_PM_GET_AGREEMENT_DETAIL 
@CCOMPANY_ID= 'BSI', @CDEPT_CODE= '00', @CPROPERTY_ID= 'ASHMD', 
@CREF_NO= 'LOO-SU-00-20250200001', @CTRANS_CODE= '802011', @CUSER_ID= 'HMC'

RSP_PM_GET_AGREEMENT_UTILITIES_DT
@CBUILDING_ID= 'TW-1', @CCHARGES_ID= 'EC02', 
@CCHARGES_TYPE= '01', @CCOMPANY_ID= 'BSI', 
@CDEPT_CODE= '02', @CFLOOR_ID= 'GF', 
@CPROPERTY_ID= 'ASHMD', @CREF_NO= 'LOO-E-02-2025020001', 
@CSEQ_NO= '001', 
@CTRANS_CODE= '802043', @CUNIT_ID= 'BZ015', @CUSER_ID= 'HMC'

RSP_PM_GET_AGREEMENT_UTILITIES_LIST
@CBUILDING_ID= 'TW-1', @CCOMPANY_ID= 'BSI', 
@CDEPT_CODE= '02', @CFLOOR_ID= 'GF', 
@CPROPERTY_ID= 'ASHMD', @CREF_NO= 'LOO-E-02-2025020001', 
@CTRANS_CODE= '802043', @CUNIT_ID= 'BZ015', @CUSER_ID= 'HMC'