//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_GL_RECURRING_UPLOADResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_GL_RECURRING_UPLOADResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_GL_RECURRING_UPLOADResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_GL_RECURRING_UPLOADResources.RSP_GL_RECURRING_UPLOADResources_msgrsc", typeof(RSP_GL_RECURRING_UPLOADResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount cannot be 0!.
        /// </summary>
        internal static string AMOUNT_INVALID {
            get {
                return ResourceManager.GetString("AMOUNT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Journal Amount! Journal Amount can only be either Debit or Credit.
        /// </summary>
        internal static string AMOUNT_INVALID1 {
            get {
                return ResourceManager.GetString("AMOUNT_INVALID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount cannot be 0!.
        /// </summary>
        internal static string AMOUNT_ZERO {
            get {
                return ResourceManager.GetString("AMOUNT_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Base Rate must be &gt; 0!.
        /// </summary>
        internal static string BC_BASE_INVALID {
            get {
                return ResourceManager.GetString("BC_BASE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Rate must be &gt; 0!.
        /// </summary>
        internal static string BC_CURRENCY_INVALID {
            get {
                return ResourceManager.GetString("BC_CURRENCY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Code does not exist!.
        /// </summary>
        internal static string CENTER_NOT_FOUND {
            get {
                return ResourceManager.GetString("CENTER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code is mandatory!.
        /// </summary>
        internal static string CURRENCY_EMPTY {
            get {
                return ResourceManager.GetString("CURRENCY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code does not exist!.
        /// </summary>
        internal static string CURRENCY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CURRENCY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code is more than 3 characters!.
        /// </summary>
        internal static string CURRENTY_LENGTH {
            get {
                return ResourceManager.GetString("CURRENTY_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department is mandatory!.
        /// </summary>
        internal static string DEPT_EMPTY {
            get {
                return ResourceManager.GetString("DEPT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depatment does not exist!.
        /// </summary>
        internal static string DEPT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEPT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is mandatory!.
        /// </summary>
        internal static string DESC_EMPTY {
            get {
                return ResourceManager.GetString("DESC_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No. is mandatory!.
        /// </summary>
        internal static string DOC_NO_EMPTY {
            get {
                return ResourceManager.GetString("DOC_NO_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No. is more than 30 characters!.
        /// </summary>
        internal static string DOC_NO_LENGTH {
            get {
                return ResourceManager.GetString("DOC_NO_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process failed! unable to preview Recurring Journal {0}.
        /// </summary>
        internal static string Error900 {
            get {
                return ResourceManager.GetString("Error900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate data {0}.
        /// </summary>
        internal static string Error901 {
            get {
                return ResourceManager.GetString("Error901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Fixed Rate Value! Valid Fixed Rate value: 0,1!.
        /// </summary>
        internal static string FIXED_RATE_INVALID {
            get {
                return ResourceManager.GetString("FIXED_RATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency must be &gt; 0!.
        /// </summary>
        internal static string FREQUENCY_INVALID {
            get {
                return ResourceManager.GetString("FREQUENCY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No. is mandatory!.
        /// </summary>
        internal static string GLNO_EMPTY {
            get {
                return ResourceManager.GetString("GLNO_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No. is more than 20 characters!.
        /// </summary>
        internal static string GLNO_LENGTH {
            get {
                return ResourceManager.GetString("GLNO_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No. does not exist!.
        /// </summary>
        internal static string GLNO_NOT_FOUND {
            get {
                return ResourceManager.GetString("GLNO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval must be &gt; 0!.
        /// </summary>
        internal static string INTERVAL_INVALID {
            get {
                return ResourceManager.GetString("INTERVAL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency Base Rate must be &gt; 0!.
        /// </summary>
        internal static string LC_BASE_INVALID {
            get {
                return ResourceManager.GetString("LC_BASE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency Rate must be &gt; 0!.
        /// </summary>
        internal static string LC_CURRENCY_INVALID {
            get {
                return ResourceManager.GetString("LC_CURRENCY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Name is mandatory!.
        /// </summary>
        internal static string RECUR_NAME_EMPTY {
            get {
                return ResourceManager.GetString("RECUR_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Name. is more than 200 characters!.
        /// </summary>
        internal static string RECUR_NAME_LENGTH {
            get {
                return ResourceManager.GetString("RECUR_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring No. is mandatory!.
        /// </summary>
        internal static string RECUR_NO_EMPTY {
            get {
                return ResourceManager.GetString("RECUR_NO_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring No. aleady exists!.
        /// </summary>
        internal static string RECUR_NO_EXIST {
            get {
                return ResourceManager.GetString("RECUR_NO_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring No. is more than 30 characters!.
        /// </summary>
        internal static string RECUR_NO_LENGTH {
            get {
                return ResourceManager.GetString("RECUR_NO_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is mandatory!.
        /// </summary>
        internal static string START_DATE_EMPTY {
            get {
                return ResourceManager.GetString("START_DATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Start Date value!.
        /// </summary>
        internal static string START_DATE_INVALID {
            get {
                return ResourceManager.GetString("START_DATE_INVALID", resourceCulture);
            }
        }
    }
}
